defibus-client/src/main/java/cn/webank/defibus/client/common/DeFiBusClientConfig.java
defibus-client/src/main/java/cn/webank/defibus/client/impl/producer/DeFiBusProducerImpl.java
defibus-client/src/main/java/cn/webank/defibus/client/impl/producer/HealthyMessageQueueSelector.java
defibus-client/src/test/java/cn/webank/defibus/client/producer/HealthyMessageQueueSelectorTest.java

this pr works for [issue #7  ](https://github.com/WeBankFinTech/DeFiBus/issues/7)
Calculating MessageQueue num of each broker, if the num of MQ in a broker is not greatter than theashold, it will send msg to all brokers not only brokers in the same idc.

[ISSUE #7]not send nearby if local mq less than threshold

---

defibus-broker/src/main/java/cn/webank/defibus/broker/client/AdjustQueueNumStrategy.java

it may cause overflow when calculate with int and assigns to long.
assign int value to a long variable and then do calculating to avoid overflow.

fix potential overflow and limit upper bound

---

build.gradle

The original fastjson version has security issues, upgrade to 1.2.71

[ISSUE #21]update fastjson version to 1.2.71

---

defibus-namesrv/src/main/java/cn/webank/defibus/namesrv/DeFiBusNamesrvStartup.java

Reverts WeBankFinTech/EventMesh#40

Revert "add init rocketmq home path"

---

eventmesh-connector-rocketmq/src/main/java/com/webank/eventmesh/connector/rocketmq/producer/ProducerImpl.java
eventmesh-connector-rocketmq/src/main/java/com/webank/eventmesh/connector/rocketmq/producer/RocketMQProducerImpl.java

this problem because of sendcallback setting in RocketMQProducerImpl

[ISSUE #226]eventMesh-rocketmq-connector tcp pub throw operation time out exception

---

eventmesh-connector-api/gradle.properties
eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/AbstractContext.java
eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/RRCallback.java
eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/consumer/MeshMQPushConsumer.java
eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/producer/MeshMQProducer.java

#278 Changed 'eventmesh-connector-api' code package name to apache.

[ISSUE #278]Refactor  'eventmesh-connector-api' package name to org.apache

---

eventmesh-runtime/bin/start.sh
eventmesh-runtime/bin/stop.sh
eventmesh-runtime/bin/watchdog.sh
eventmesh-runtime/conf/server.env
eventmesh-runtime/gradle.properties
eventmesh-runtime/scripts/before_shutdown.sh
eventmesh-runtime/scripts/client_manage.sh
eventmesh-runtime/scripts/connections.sh
eventmesh-runtime/scripts/histo.sh
eventmesh-runtime/scripts/histo_suspects.sh
eventmesh-runtime/scripts/jstack.sh
eventmesh-runtime/scripts/monitor_connections.sh
eventmesh-runtime/scripts/monitor_histo_suspects.sh
eventmesh-runtime/scripts/monitor_threads.sh
eventmesh-runtime/scripts/session.sh
eventmesh-runtime/scripts/threads.sh
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/SSLContextFactory.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/DeFiBusConstant.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/plugin/MQWrapper.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/Client.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/MessageClientIDSetter.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/OMSUtil.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java

changed:  
1. add licenses of apache for runtime module  
2. replace com.webank to org.apache fro files of other than java files  
fixed #295

[ISSUE #295] add licenses of apache for runtime module

---

docs/cn/instructions/eventmesh-runtime-quickstart.zh-CN.md
docs/cn/instructions/eventmesh-sdk-java-quickstart.zh-CN.md
docs/en/instructions/eventmesh-runtime-quickstart.md
docs/en/instructions/eventmesh-sdk-java-quickstart.md
eventmesh-connector-rocketmq/gradle.properties
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/CommonConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/ConfigurationWraper.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/domain/ConsumeRequest.java
gradle.properties

[ISSUE #322] Rename package name "com.webank.eventmesh" to "org.apache.eventmesh"

---

eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/AsyncPublishInstance.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/sub/service/SubService.java

Enhance Http Demo Subscriber by using ExecutorService, CountDownLatch and PreDestroy hook
- Remove Thread.sleep()
- Leveraging ExecutorService to manage the Thread lifecycle.
- Leveraging PreDestroy annotation to manage the JVM Runtime Shutdown hook

[Issue #337] Enhance Http Demo Subscriber by using ExecutorService, CountDownLatch and PreDestroy hook

---

README.md
README.zh-CN.md
docs/README.md
docs/cn/README.md
docs/en/README.md

LGTM is a variant analysis platform that automatically checks code for real CVEs and vulnerabilities. Learn more at https://lgtm.com/help/lgtm/about-lgtm .
Here are some alerts in our project reported by LGTM: https://lgtm.com/projects/g/apache/incubator-eventmesh/alerts/?mode=list
I'd like to add LGTM badges in the README.md, it makes easier for people who want to get alerts and then contribute to EventMesh.

[ISSUE #353] Add LGTM Badges 

---

.github/workflows/codeql-analysis.yml

This PR will enable auto Github workflows for CodeQL scans. This can help us improve code quality.
About code scanning:
> Code scanning is a feature that you use to analyze the code in a GitHub repository to find security vulnerabilities and coding errors. Any problems identified by the analysis are shown in GitHub.
> 
> You can use code scanning to find, triage, and prioritize fixes for existing problems in your code. Code scanning also prevents developers from introducing new problems. You can schedule scans for specific days and times, or trigger scans when a specific event occurs in the repository, such as a push.
> 
> If code scanning finds a potential vulnerability or error in your code, GitHub displays an alert in the repository. After you fix the code that triggered the alert, …

[ISSUE #355] Setup Github workflows for CodeQL scans

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByIpPortHandlerTest.java

[ISSUE #384] RedirectClientByIpPortHandlerTest.java doesn't have the Apache license header

---

.github/workflows/ci.yml

[To 1.3.0][ISSUE #411] Enable CI workflows running on `[0-9]+.[0-9]+.[0-9]+**` branches

---

.github/workflows/ci.yml

See #411.
It worked in the repo I forked.

[ISSUE #411] Enable CI workflows running on `[0-9]+.[0-9]+.[0-9]+**` branches

---

.github/workflows/ci.yml
.github/workflows/greetings.yml
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/consumer/LiteConsumer.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/EventMeshCommon.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/SimplePubClientImpl.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/SimpleSubClientImpl.java

[Issues #405]code polish and fix typo

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/LiteMessageTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/command/HttpCommandTest.java

For #374 
- add unit test for LiteMessage class.
- add unit test for HttpCommand class.

[ISSUE #374] Add unit test class.

---

eventmesh-spi/build.gradle
eventmesh-spi/gradle.properties
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshExtensionFactory.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshExtensionLoader.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshSPI.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/ExtensionException.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/EventMeshExtensionFactoryTest.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/ExtensionA.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/TestExtension.java
eventmesh-spi/src/test/resources/META-INF/eventmesh/org.apache.eventmesh.spi.TestExtension

[ISSUE #367]Enhance SPI plugins

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/body/BaseResponseBodyTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/BaseRequestHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/BaseResponseHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/AbstractRequestHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/AbstractResponseHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/HeartbeatRequestHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/HeartbeatResponseHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/RegRequestHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/RegResponseHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/SubscribeRequestHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/SubscribeResponseHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/UnRegRequestHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/UnRegResponseHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/UnSubscribeRequestHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/client/UnSubscribeResponseHeaderTest.java

For #374 .
- add unit test for http protocol header client class.

[ISSUE #374] add unit test for http protocol header client class.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation_related.md
.github/ISSUE_TEMPLATE/enhancement_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

[ISSUE #425] Using templates to encourage useful issues and PRs

---

eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/consumer/MeshMQPushConsumer.java
eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/producer/MeshMQProducer.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshExtensionLoader.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/EventMeshExtensionFactoryTest.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/example/PrototypeExtension.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/example/SingletonExtension.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/example/TestPrototypeExtension.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/example/TestSingletonExtension.java
eventmesh-spi/src/test/resources/META-INF/eventmesh/org.apache.eventmesh.spi.example.TestPrototypeExtension
eventmesh-spi/src/test/resources/META-INF/eventmesh/org.apache.eventmesh.spi.example.TestSingletonExtension

Change producer and consumer spi to prototype

[ISSUE #367] Support prototype spi instance

---

eventmesh-connector-plugin/eventmesh-connector-standalone/build.gradle
eventmesh-connector-plugin/eventmesh-connector-standalone/gradle.properties
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/MessagingAccessPointImpl.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/broker/MessageQueue.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/broker/StandaloneBroker.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/broker/model/MessageEntity.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/broker/model/TopicMetadata.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/broker/task/HistoryMessageClearTask.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/broker/task/SubScribeTask.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/consumer/StandaloneConsumer.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/consumer/StandaloneMeshMQPushConsumerAdaptor.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/producer/StandaloneMeshMQProducerAdaptor.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/producer/StandaloneProducer.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/resource/StandaloneConnectorResourceService.java
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.connector.ConnectorResourceService
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.consumer.MeshMQPushConsumer
eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.producer.MeshMQProducer
eventmesh-connector-plugin/eventmesh-connector-standalone/src/test/java/org/apache/eventmesh/connector/standalone/broker/StandaloneBrokerTest.java
eventmesh-runtime/build.gradle
eventmesh-runtime/conf/eventmesh.properties

Add standalone connector plugin, close issue #375 
How to use:
1. Config the connector type in eventmesh.properties
```
#connector plugin
eventMesh.connector.plugin.type=standalone
```
2. install the standalone plugin
You can add the dependency in eventmesh-runtime/build.gradle
```
implementation project(":eventmesh-connector-plugin:eventmesh-connector-standalone")
```
Or execute 
```
./gradlew clean jar dist copyConnectorPlugin
```

[ISSUE #375] In memory as event store

---

eventmesh-schema-registry/eventmesh-schema-registry-server/src/main/java/org/apache/eventmesh/schema/registry/server/exception/OpenSchemaExceptionHandler.java
eventmesh-schema-registry/eventmesh-schema-registry-server/src/main/java/org/apache/eventmesh/schema/registry/server/service/SubjectService.java

rename ```import org.apache.eventmesh.openschemaregistry.domain.*;``` to ```org.apache.eventmesh.schema.registry.server.domain.*;```
Fixes ISSUE #541.
Seems that part of the package name of schema registry is renamed from openschemaregistry to schema.registry.server, but one of the packages imported in SubjectService.java is not changed.
change import org.apache.eventmesh.openschemaregistry.domain.*; to import org.apache.eventmesh.schema.registry.server.domain.*;

[ISSUE #541] rename issue

---

.gitignore
build.gradle
eventmesh-connector-plugin/build.gradle
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/ConnectorResourceService.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/consumer/MeshMQPushConsumer.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/producer/MeshMQProducer.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/RocketMQConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/RocketMQProducerImpl.java
eventmesh-registry-plugin/build.gradle
eventmesh-registry-plugin/eventmesh-registry-api/src/main/java/org/apache/eventmesh/api/registry/RegistryService.java
eventmesh-runtime/build.gradle
eventmesh-security-plugin/build.gradle
eventmesh-security-plugin/eventmesh-security-api/src/main/java/org/apache/eventmesh/api/acl/AclService.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshExtensionFactory.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshExtensionType.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshSPI.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/EventMeshUrlClassLoader.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/ExtensionClassLoader.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/JarExtensionClassLoader.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/MetaInfExtensionClassLoader.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/example/TestPrototypeExtension.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/example/TestSingletonExtension.java

1. Optimize plugin load, support load plugin by plugin instance name, these means we needn't load all plugin
2. Optimize install plugin, suppory install plugin by ./gradlew jar dist
3. Make UrlClassLoader siglenton

[ISSUE #367] Optimize plugin load

---

docs/en/features/eventmesh-cloudevents-sdk-binding.md

support feature design in eventmesh-cloudevents-sdk-binding.md

[Feature #564] Support CloudEvents protocols for pub/sub in EventMesh

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/Header.java
eventmesh-examples/build.gradle
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/AsyncSubscribe.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/AsyncSubscribeBroadcast.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/SyncResponse.java
eventmesh-sdk-java/build.gradle
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/EventMeshClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/SimplePubClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/EventMeshCommon.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/MessageUtils.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/PropertyConst.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/ReceiveMsgHook.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/DefaultEventMeshClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/SimplePubClientImpl.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/AsyncSubscribe.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/AsyncSubscribeBroadcast.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/SyncResponse.java

Fixes ISSUE #563 .
•add the CloudEvents identifier in package header
•use CloudEventBuilder build the CloudEvent and put it into the package body

[ISSUE #563] SDK SUPPORT CLOUD EVENT

---

.github/workflows/ci.yml
CONTRIBUTING.md
CONTRIBUTING.zh-CN.md
build.gradle
eventmesh-connector-plugin/eventmesh-connector-standalone/gradle.properties
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/gradle.properties
eventmesh-protocol-plugin/eventmesh-protocol-openmessage/gradle.properties
eventmesh-registry-plugin/eventmesh-registry-namesrv/gradle.properties
eventmesh-security-plugin/eventmesh-security-acl/gradle.properties

The check style will not be trigger in build, you need to manually execute `./gradlew check`.
And this pr also change the plugin package code, when add a new plugin, need to add a gradle.properties file, and defined the plugin name.
close #580

[ISSUE #580] Add checkstyle gradle plugin

---

eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/MessagingAccessPointImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/cloudevent/RocketMQMessageFactory.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/cloudevent/impl/RocketMQBinaryMessageReader.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/cloudevent/impl/RocketMQHeaders.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/cloudevent/impl/RocketMQMessageWriter.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/PushConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/RocketMQConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/exception/RMQMessageFormatException.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/exception/RMQTimeoutException.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/AbstractProducer.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/ProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/RocketMQProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/utils/CloudEventUtils.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/test/java/org/apache/rocketmq/consumer/PushConsumerImplTest.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/test/java/org/apache/rocketmq/producer/ProducerImplTest.java

connector support cloud event

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/CloudEventProducer.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/EventMeshMessageProducer.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/EventMeshCommon.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/MessageUtils.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPPubClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPPubClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPSubClient.java

update java sdk

---

.github/workflows/ci.yml
build.gradle

[ISSUE #582] Add jdk11 compile/test in ci

---

eventmesh-connector-plugin/eventmesh-connector-rocketmq/build.gradle
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/admin/command/Command.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ClientConfiguration.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ConfigurationWrapper.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/RocketMQConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/ProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/RocketMQProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/test/java/org/apache/eventmesh/connector/rocketmq/config/ConfigurationWrapperTest.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/test/java/org/apache/rocketmq/producer/ProducerImplTest.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/test/resources/rocketmq-client.properties
eventmesh-runtime/build.gradle
style/checkStyle.xml

close #630 
This pr remove the refresh config from the file, since no one will actuallu use it that way, we may need to design how to adapt to configutation center like apollo or nacos

[ISSUE #630] RocketMQProducerImpl cannot load config properties from classpath

---

README.md
README.zh-CN.md

Fixes ISSUE #702 
- change slack link

[Issue #702] Fix Slack Join link

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/cloudevents/AsyncPublish.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/cloudevents/SyncRequest.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/eventmeshmessage/AsyncPublish.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/eventmeshmessage/AsyncPublishBroadcast.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/eventmeshmessage/SyncRequest.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/cloudevents/AsyncSubscribe.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/cloudevents/SyncResponse.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/AsyncSubscribe.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/AsyncSubscribeBroadcast.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/SyncResponse.java

Fix args typo in examples
rename `agrs` to `args`

[ISSUE #405] Fix args typo in examples

---

docs/cn/instructions/eventmesh-runtime-quickstart-with-docker.md
docs/cn/instructions/eventmesh-runtime-quickstart.md
docs/cn/instructions/eventmesh-sdk-java-quickstart.md
docs/en/instructions/eventmesh-runtime-quickstart-with-docker.md
docs/en/instructions/eventmesh-runtime-quickstart.md
docs/en/instructions/eventmesh-sdk-java-quickstart.md
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/pub/eventmeshmessage/BatchPublishInstance.java

Fixes ISSUE #417.
Create getting started instructions for Grpc transport protocol
Create getting started instructions for Grpc transport protocol
- eventmesh-runtime-quickstart
- eventmesh-runtime-quickstart-with-docker
- eventmesh-sdk-java-quickstart
- If yes, how is the feature documented? yes

[Issue #417] Create getting started instructions for Grpc transport

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPPubClient.java

Fix #726 
If we throw an exception, then we don't need to trigger the callback anymore.
Remove the annotation

[ISSUE #726] Remove the misleading annotation

---

build.gradle

Fixes ISSUE #742 .
add "eventmesh-admin-rocketmq" into rootProject, so eventmesh-admin-rocketmq-xxx.jar will be added into apps folder.

[ISSUE #742] add eventmesh-admin-rocketmq into rootProject

---

build.gradle
eventmesh-common/build.gradle
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/IPUtils.java
eventmesh-runtime/build.gradle
eventmesh-runtime/conf/eventmesh.properties
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
tools/third-party-dependencies/known-dependencies.txt
tools/third-party-licenses/licenses/LICENSE-ipaddress.txt

Fixes ISSUE #758
Validate Subscriber url for security reason.
In Eventmesh Common module, provide API to validate the subscriber url.

[Issue #758] validate subscriber Url

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/cloudevents/AsyncPublish.java
eventmesh-runtime/conf/eventmesh.properties
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java

Fixes ISSUE #655
In Eventmesh runtime publish APIs, we need to check the message body size and batch message size, to avoid overwhelming the runtime with too large messages. This is the security requirement of production environment.
Adding send message constraints for message size and batch size

[Issue #655] Adding send message constraints for message size and batch size

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ConfigurationWrapper.java
eventmesh-metrics-plugin/eventmesh-metrics-opentelemetry/src/main/java/org/apache/eventmesh/metrics/opentelemetry/config/OpenTelemetryConfiguration.java
eventmesh-metrics-plugin/eventmesh-metrics-opentelemetry/src/test/java/org/apache/eventmesh/metrics/opentelemetry/config/OpenTelemetryConfigurationTest.java
eventmesh-metrics-plugin/eventmesh-metrics-opentelemetry/src/test/resources/opentelemetry.properties
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/RRCallbackResponseHandlerAdapter.java

[MINOR] Fix plugin cannot load properties from classpath

---

eventmesh-runtime/bin/start.sh
eventmesh-runtime/bin/stop.sh

Allow run script in other directory.
Currently, it must be run in the bin directory
use `dirname` instead

[MINOR] Allow run script in other directory

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/SubscriptionItem.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/ConsumerGroupConf.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/ConsumerGroupTopicConf.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java

<!--
Fixes ISSUE #768
This is to fix the bug of updating HTTP subscriber, and it is not taking effect.
update `ConsumerManager` notification method to use object.clone() instead of the same object reference.

[Issue #768] fix issue in update HTTP subscriber

---

docs/en/instructions/eventmesh-runtime-quickstart-with-docker.md

Fixes ISSUE https://github.com/apache/incubator-eventmesh/issues/795
Modifications：fixed doc eventmesh-runtime-quickstart-with-docker.md，change eventMesh.properties -> eventmesh.properties。

[ISSUE #795] Fix doc eventmesh-runtime-quickstart-with-docker.md

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/ThreadPoolFactory.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/BatchMessageWrapper.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/SimpleMessageWrapper.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/BaseRequestBody.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/SubStreamHandler.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/EventMeshGrpcProducer.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/util/EventMeshClientUtil.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/AbstractHttpClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/RequestContext.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/openmessage/OpenMessageTCPClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/openmessage/OpenMessageTCPPubClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/openmessage/OpenMessageTCPSubClient.java

optimize some code format.
Some of the code in the project is not well-formed
update eventmesh-sdk-java and eventmesh-common module part code format.

Format the code in `eventmesh-sdk-java` and `eventmesh-common`

---

.licenserc.yaml

- update licenserrc.yaml ignore go.sum
- add license header for some go files

[Go SDK] Update licenserrc.yaml to ignore go.sum

---

eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/util/JsonUtils.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/pub/cloudevents/AsyncPublishInstance.java
eventmesh-runtime/build.gradle
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/controller/ClientManageController.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/DeleteWebHookConfigHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/InsertWebHookConfigHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/QueryWebHookConfigByIdHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/QueryWebHookConfigByManufacturerHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/UpdateWebHookConfigHandler.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManage.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/ManufacturerObject.java
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookConfig.java
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookConfigOperation.java
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookOperationConstant.java
eventmesh-webhook/eventmesh-webhook-receive/build.gradle
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/ManufacturerProtocol.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookController.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookMQProducer.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookRequest.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/protocol/GithubProtocol.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/protocol/ProtocolManage.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/AbstractWebHookConfigOperation.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/HookConfigOperationManage.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/WebhookFileListener.java

Fixes ISSUE #<865>.
repair exception handling && send webhook CloudEvents
- Enhance the integrity of code functionality
- Fix some bad code

[ISSUE #865] EM-Webhook: repair exception handling && send webhook CloudEvents

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java

Fixes ISSUE #923 
- Removing the ClientGroupWrapper from map not work, because the key is not right.
- Modify the removed key same with when putted.

[ISSUE #923] Fix the key when removing item from ClientGroupMap

---

eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/http/SendMessageRequestProtocolResolver.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPMessageHandler.java

Fixes ISSUE #957 .
- In cloud-native application scenarios, the flow of events is very complex and common, event tracking is very meaningful and important for analyzing problems
- Add trace buried point for http protocol in eventmesh-runtime
- Record specific attributes to the trace, for example, the time of the event life cycle, the eventmesh ip that the event passed through

[ISSUE #957] add trace for http protocol in eventmesh-runtime

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java

When the Eventmesh application runs on a Linux Platform using IDE, there will be errors on reading the properties and setting files. The error was due to the mix-use of forward-slash and backward-slash. The bug impacts developers who use IDE on Mac or Linux Platform
Replace all the / and \ with proper file separators that work both for Linux and Windows
- No
- No new feature introduced

Fix Error when Running/Debugging the Application on Linux Platform

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java

Fixes ISSUE #987.
use try-with-resource to close the BufferedReader.

[ISSUE #987] try-with-resource to close the BufferedReader

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPClient.java

Fixes ISSUE #995 .
None.
- Add `EventMeshMessageTCPClient#validateMessage` method in `EventMeshMessageTCPClient` .
None.

[ISSUE #995] Add parameter checking before sending message for EventMeshMessageTCPClient .

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/codec/Codec.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ClientConfiguration.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/pub/cloudevents/CloudEventsPublishInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/pub/cloudevents/CloudEventsRequestInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/pub/eventmeshmessage/AsyncPublishBroadcast.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/pub/eventmeshmessage/AsyncPublishInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/pub/eventmeshmessage/RequestReplyInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/pub/eventmeshmessage/AsyncPublishInstance.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshGrpcConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshConstants.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/MessageUtils.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/EventMeshCommon.java

Fixes ISSUE #980 .
Some fileds need to be made final.
I have made some fields are final .

[ISSUE #980]Made some fileds are final

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/trace/Trace.java

Fixed ISSUE #1021 
When I run the `eventmesh-runtime` in debug model. I find a bug which is NullpointException at line 432 in file `ClientGroupWrapper ` . So I want to  Fix it.
I read some information about the telemetry. I think the method `createSpan` in file `Trace` should not return `null`, at least return a invalid Span .
- Does this pull request introduce a new feature? 
- no

[ISSUE #1021]Fix the case that span is null

---

eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/service/SubService.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/service/SubService.java

replace `System.exit(0) ` with `throw new RuntimeException();`
Fixes ISSUE #988 .

[ISSUE #790] [Bug] Method invokes System.exit(0)

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerGroupManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java

Fixes ISSUE #1052 .
When other instances of the same group subscribe, update the subscription information in `EventMeshConsumer`

[ISSUE #1052]fix push msg only the first started instance with same group

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpEventWrapper.java

Fixes ISSUE #1056 
check the length of `requestUri` before using `substring` method.

[ISSUE #1056]Fix StringIndexOutOfBoundsException

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/AdminShutdownProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java

Fixes ISSUE #1047 
Fix send response twice problem in http server.
- Remove the send response operation in `AbstractHttpServer.java`;
- All the response operation and logic moved into processors.

[ISSUE #1047] fix send response twice in eventmesh http server

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/controller/ClientManageControllerTest.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java

Fixes ISSUE #1064 .
When running the ClientManageController unit test, NPE will appear. The reason is that due to the new Webhook feature, it is necessary to add related Mock adaptations.
add AdminWebHookConfigOperationManage mock logic in ClientManageController unit test file.
modify unit test,no need to add new documents

[ISSUE #1064]Fix NullPointException Of ClientManageControllerTest

---

docs/en/roadmap.md
docs/zh/roadmap.md

Fixes ISSUE #1107 
Update roadmap docs
Update roadmap docs

[ISSUE #1107] Update roadmap docs

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshConstants.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/producer/EventMeshProducer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java

Fixes #<1152>.
ClientGroupWrapper EventMeshProducer classes using the redundant plain strings as property keys and values, which in turn will cause inconsistency in the project. In future if any of that String literal needs to be changed/reused its better to extract and collate them in single EventMeshConstants class, which will ease the maintainability of code.
Introduced a new constants and also reused few of existing constants from EventMeshConstants and have replaced the Constant values in ClientGroupWrapper, EventMeshProducer.
Since the change not introducing any new feature/ functional change, documentation …

[ISSUE  #1152] Extraction of constants [ClientGroupWrapper EventMeshProducer]

---

.licenserc.yaml
eventmesh-sdk-rust/.gitignore
eventmesh-sdk-rust/Cargo.toml
eventmesh-sdk-rust/eventmesh/Cargo.toml
eventmesh-sdk-rust/eventmesh/build.rs
eventmesh-sdk-rust/eventmesh/proto/eventmesh-client.proto
eventmesh-sdk-rust/eventmesh/src/constants.rs
eventmesh-sdk-rust/eventmesh/src/grpc/config.rs
eventmesh-sdk-rust/eventmesh/src/grpc/consumer.rs
eventmesh-sdk-rust/eventmesh/src/grpc/mod.rs
eventmesh-sdk-rust/eventmesh/src/grpc/producer.rs
eventmesh-sdk-rust/eventmesh/src/http/config.rs
eventmesh-sdk-rust/eventmesh/src/http/mod.rs
eventmesh-sdk-rust/eventmesh/src/http/producer.rs
eventmesh-sdk-rust/eventmesh/src/http/protocol_key.rs
eventmesh-sdk-rust/eventmesh/src/http/request_code.rs
eventmesh-sdk-rust/eventmesh/src/lib.rs
eventmesh-sdk-rust/eventmesh/src/message.rs
eventmesh-sdk-rust/examples/Cargo.toml
eventmesh-sdk-rust/examples/grpc-consumer-stream.rs
eventmesh-sdk-rust/examples/grpc-consumer.rs
eventmesh-sdk-rust/examples/grpc-producer-batch-publish.rs
eventmesh-sdk-rust/examples/grpc-producer-publish.rs
eventmesh-sdk-rust/examples/grpc-producer-request.rs
eventmesh-sdk-rust/examples/http-producer-publish.rs
eventmesh-sdk-rust/examples/http-producer-request.rs

#1223 
There are some CI errors due to the lack of the license header of Rust SDK files. 
Add file license headers.
None

[Enhancement] Add rust sdk license headers

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/selector/Selector.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/selector/SelectorException.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/selector/SelectorFactory.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/selector/ServiceInstance.java

Fixes #1244  
the sdk currently lacks name service addressing capabilities, so a selector module is added to support name service addressing. the sdk is responsible for defining the interface, and users need to implement the naming selector by themselves.
1. add selector interface

[ISSUE#1244]java sdk add selector interface

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/protocol/processor/WebHookProcessorTest.java

[ISSUE #1350] Fix WebHookProcessorTest test error

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/DefaultConsumer.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/PullConsumerImpl.java

Fixed #1307.
*Support cluster-mode and broadcast-mode listener in Knative-Connector.*
*This PR will be merged into knative-connector branch first.*
Listener (cluster or broadcast mode) calls ```consume``` method after ```subscribe``` according to action type (CommitMessage, ReconsumeLater, or ManualACK).
- Added broadcast-mode message listener
- Added ```consume``` statement calling in ```subscribe``` method
Same as the integration test steps in demo (see [document](https://github.com/apache/incubator-eventmesh/blob/master/docs/zh/connector-knative/01-eventmesh-connector-knative.md) for details)
- Does this pull request introduce a new feature? Yes.
- If yes, how is the feature documented? Not documented.
- If a feature is not documented yet in this PR, please create a followup issue for …

[ISSUE #1307] Knative Connector: Support Cluster-Mode and Broadcast-Mode Listener.

---

eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/PravegaConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/PravegaProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/PravegaClient.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/SubscribeTask.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/test/java/org/apache/eventmesh/connector/pravega/client/PravegaClientTest.java

Fixes issue #1243. Related PR #1203.
Upgrade pravega connector
- SubscribeTask supports EventMeshAsyncConsumeContext.commit
- Consumer support broadcast and clustering message model
- Upgrade the creation of ReaderGroup and Reader. 
- Use `{consumerGroup}-{topic}` for clustering model or UUID for broadcast model as ReaderGroup name
- Set `AUTOMATIC_RELEASE_AT_LAST_CHECKPOINT` as the retention strategy of all ReaderGroup

[ISSUE #1243] Upgrade pravega connector 

---

eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/MeshMessageProtocolAdaptor.java
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/MeshMessageProtocolConstant.java

Fixes #839.
extract constant into MeshMessageProtocolConstant
replace Strings with constants in MeshMessageProtocolConstant

[ISSUE #839] Extraction of constants [eventmesh-protocol-meshmessage]

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/catalog/EventMeshCatalogClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/catalog/config/EventMeshCatalogClientConfig.java

Fixes #1092 . 
add eventmesh-catalog java client
java sdk add eventmesh-catalog java client

[ISSUE #1092] Add eventmesh-catalog java client

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/QueryOperationsResponse.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java

Fixes #1535 
Motivation
This method uses an integer-based for loop to iterate over a java.util.List, by calling List.get(i) each time through the loop. The integer is not used for other reasons.
Modifications
Instead for loop, replaced it with foreach loop
Documentation
- Does this pull request introduce a new feature?   no

[ISSUE #1535] Method uses integer based for loops to iterate over a List [QueryOperationsResponse]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Heartbeat.java

Fixes #1537
Integer-based for loop is used to iterate over a java.util.List, by calling List.get(i) each time through the loop. The integer is not used for other reasons. It is better to use an Iterator instead, as depending on List implementation, iterators can perform better, and they also allow for exchanging of other collection types without issue.
* Update existing integer based for loop with the enhanced for loop.
- Does this pull request introduce a new feature? (yes / no) **No**
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) **NA**
- If a feature is not applicable for documentation, explain why? **NA**
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation **NA**

[ISSUE #1537] Replace integer based for loop with foreach loop

---

docs/en/instruction/01-store-with-docker.md

Fixes #1167.
two links in file docs/en/instruction/01-store-with-docker.md was not working 
Updated the files relative path in docs/en/instruction/01-store-with-docker.md
- Does this pull request introduce a new feature? NO
- If a feature is not applicable for documentation, explain why? It is just a link change

[ISSUE #1167]Updated the link path in 01-store-with-docker.md

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerRunner.java

Fixes #1557
Make use of SLF4J parameterized logging instead of String concatenation

[ISSUE #1557] Uses Parameterized logging in KafkaConsumerRunner instead of String Concatenation

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Subscription.java

Fixes #1536.
There are two for loops in the method writeTo that use integer based loops to iterate over the subscriptionItems list. Because the integer is not used for any other reason, it's better to use an iterator or a for-each loop. 
I changed the integer based for loops in the writeTo method to for-each loops 
none

[ISSUE #1536] Method uses integer based for loops to iterate over a List [Subscription]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/IPUtils.java

Fixes #1533 
This method prints a stack trace to the console. I have updated them to log it using the appropriate loggers. 
- Does this pull request introduce a new feature? (yes / no) No 

[ISSUE #1533] | Method prints the stack trace to the console

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerGroupManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java

Fixes #1627 .
When one consumer group subscribes multiple topics, only the first subscription can invoke the url.
Set the consumerGroupConfig of EventMeshConsumer, when invoke the refresh method of ConsumerGroupManager.
- no

[ISSUE #1627] refresh consumerGroupConfig of eventMeshConsumer

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/config/ConfigurationWrapper.java

Fixes #1558 
ConfigurationWrapper is using the default encoding while reading the data from a file in configPath, and this might cause application behaviour to vary between platforms, as described in https://github.com/apache/incubator-eventmesh/issues/1558
I have made changes to read the contents of the file in a fixed UTF-8 format, and this is possible by using the InputStreamReader.
- Does this pull request introduce a new feature? No, it's a fix to handle edge cases.

[ISSUE #1558] Replacing default encoding with UTF-8 in ConfigurationWrapper

---

eventmesh-sdk-go/grpc/client.go
eventmesh-sdk-go/grpc/producer.go

Fixes #1674.
fix golang-sdk publish error: connection closed before server preface received
remove the external grpc conn close logic.

[ISSUE #1674] remove external grpc conn close logic

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/producer/SendMessageContext.java

Fixes [#1686](https://github.com/apache/incubator-eventmesh/issues/1686)
Add final keyword to avoid vulnerability

[1686] Field isn't final but should be [grpc SendMessageContext]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPMessageHandler.java

Fixes #1688
Add final keyword to avoid vulnerability

[ISSUE #1688] Field isn't final but should be [HTTPMessageHandler]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java

Fixes #1654 .
It occurs an NullPonterException when broadcastEventListener consumes message.
Change the nonexistent fields to others.
- no

[ISSUE #1654] fix NullPointerException of broadcastEventListener

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HelloTask.java

Fixes #1697 
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HelloTask.java line 76
The code invokes toString on an array, which will generate a fairly useless result. This needs to be updated to use Arrays.toString() instead
In line 76, modified invocation of toString to an array [Arrays.toString()].
- Does this pull request introduce a new feature?  (no)
- If a feature is not applicable for documentation, explain why?(minor enhancement fix)
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation(-)

[ISSUE #1697] Modify Invocation of toString on an array 

---

eventmesh-connector-plugin/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/client/RedissonClient.java

Fixs #1821.
Enhancement Request
[method](https://github.com/apache/incubator-eventmesh/blob/fcac8f39fef729b239a6c0c3a269cd4d0fe35da8/eventmesh-connector-plugin/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/client/RedissonClient.java#L48) needlessly boxes a boolean constant
Describe the solution you'd like
use false instead of BOOLEAN.FALSE

[ISSUE #1821]method needlessly boxes a boolean constant 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java

Fixes #1719.
Unused field: org.apache.eventmesh.runtime.boot.EventMeshTCPServer.tcpRegisterTask
This field is never used
Remove unused field

[ISSUE #1719]Remove unused field

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshStartup.java

Fixes #1684.
Add final keyword to avoid vulnerability

[ISSUE #1684]Field isn't final but should be [EventMeshStartup]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/SSLContextFactory.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/producer/SendMessageContext.java

Fixes #1818 .
**Motivation**
Handled IOException in eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/SSLContextFactory.java
Enclose inputStream.close() in try-catch block and caught IOException.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) Not applicable
- If a feature is not applicable for documentation, explain why? Minor issue which comes under code cleanup.

[ISSUE #1818] Fix IOException in SSLContextFactory

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/producer/SendMessageContext.java

Fixes #1687.
**Motivation**
The static field is public but not final, and could be changed by malicious code or by accident from another package. This vulnerability can be avoided by making the field final.
Added final modifier to Logger to avoid vulnerability
- Does this pull request introduce a new feature? (yes / no): No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented): Not applicable
- If a feature is not applicable for documentation, explain why? Minor issue which comes under code cleanup.

[ISSUE #1687] Add final modifier to Logger to avoid vulnerability

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java

- Use `Objects.requireNonNull` achieve fail fast
Fixes [#1705](https://github.com/apache/incubator-eventmesh/issues/1705).
* Added NPE check with `Objects.requireNonNull`
* As for the potential null ptr on line `234`, the data of the event could be empty, so we will return empty string instead of throw exception.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) Not applicable 
- If a feature is not applicable for documentation, explain why? This is a minor issue …

ISSUE (#1705): add NPE exception check

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java

Fixes #1699.
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed
Added NPE check
- Does this pull request introduce a new feature? (yes / no)No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)not applicable
- If a feature is not applicable for documentation, explain why?This is a minor issue that comes under code cleanup

[ISSUE #1699] Refactor. Add NPE check

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java

Fixes #1702.
**Motivation**
The return value from a method is dereferenced without a null check. This may lead to a NullPointerException when the code is executed.
Added NullPointerException check to return value
- Does this pull request introduce a new feature? (yes / no): No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented): Not applicable
- If a feature is not applicable for documentation, explain why? Minor issue that comes under code cleanup.

[ISSUE #1702] Add Null Pointer Exception check

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/impl/KnativeBinaryMessageReader.java

Fixes #1845 .
located at:
org/apache/eventmesh/connector/knative/cloudevent/impl/KnativeBinaryMessageReader.java line 34
explanation：
This line has the form String str = str.equals("someOtherString")
If the string variable str is null, a NullPointerException may occur. if the code is adapted to String str = "someOtherString".equals(str)
That is, if you call equals() on a string literal, passing the variable as an argument, then this exception will not occur because equals() will check for null.
before 
```java
@Override
protected boolean isContentTypeHeader(String key) {
return key.equals(KnativeHeaders.CONTENT_TYPE);
}
```
after
```java
@Override
protected boolean isContentTypeHeader(String key) {
return KnativeHeaders.CONTENT_TYPE.equals(key);
}
```
- Does this pull request introduce a …

[ISSUE #1845]Method makes literal string comparisons passing the literal as an argument

---

eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/config/PravegaConnectorConfigWrapper.java

Fixes #<1844>.
org/apache/eventmesh/connector/pravega/config/PravegaConnectorConfigWrapper.java line 65
Replace the code in the image using the method that has been extracted.
this method is located at:
org/apache/eventmesh/common/utils/PropertiesUtils.java loadPropertiesWhenFileExist
Replace the code in the image using the method that has been extracted.
this method is located at:
org/apache/eventmesh/common/utils/PropertiesUtils.java loadPropertiesWhenFileExist

[ISSUE #1844] [Enhancement] Use the methods that have been extracted [PravegaConnectorConfigWrapper]

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/cloudevents/AsyncSubscribe.java

Fixes #1848 .
located at:
org/apache/eventmesh/tcp/demo/sub/cloudevents/AsyncSubscribe.java line 71
Add NPE to check for exceptions.
before:
```java
@Override
public Optional<CloudEvent> handle(CloudEvent msg) {
String content = new String(msg.getData().toBytes(), StandardCharsets.UTF_8);
log.info("receive async msg: {}|{}", msg, content);
return Optional.empty();
}
```
after:
```java
@Override
public Optional<CloudEvent> handle(CloudEvent msg) {
if (msg.getData() == null) {
log.warn("receive async msg's data is null.");
return Optional.empty();
}
String content = new String(msg.getData().toBytes(), StandardCharsets.UTF_8);
log.info("receive async msg: {}|{}", msg, content);
return Optional.empty();
}
```

fix #1848：Possible null pointer dereference due to return value of called method [AsyncSubscribe]

---

eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java

located at:
org.apache.eventmesh.protocol.meshmessage.resolver.tcp.TcpMessageProtocolResolver.java lines 104
Add NPE to check for exceptions.
close: #1850

[ISSUE #1850]Possible null pointer dereference due to return value of called method [TcpMessageProtocolResolver]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java

Fixes #1728.
This method accesses the value of a Map entry, using a key that was retrieved from a keySet iterator. It is more efficient to use an iterator on the entrySet of the map, to avoid the Map.get(key) lookup.
Follow the advice in this issue, we replace key set iteration by using `entrySet`.
What's more, unlike style of proposed method in the issue, we use 'happy path' in the for loop.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) Not applicable
- If a feature is not applicable for documentation, explain why? This is a minor issue that comes under code cleanup.

[ISSUE #1728] use entrySet replace key set iterator

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/config/ConfigurationWrapper.java

Fixes #1565.
**Motivation**
The method catches an exception, and throws a different exception, without incorporating the original exception. Doing so hides the original source of the exception, making debugging and fixing these problems difficult.
Added logger to record raw exception information.
- Does this pull request introduce a new feature? (yes / no): No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented): Not applicable
- If a feature is not applicable for documentation, explain why? Minor issue to help debugging

[ISSUE #1565] Add logger to record raw exception information

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/ConsumerImpl.java

Fixes #1566 .
This method catches an exception, and throws a different exception, without incorporating the original exception. Doing so hides the original source of the exception, making debugging and fixing these problems difficult.
Added logger to record raw exception information
- Does this pull request introduce a new feature? (yes / no)No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)not applicable
- If a feature is not applicable for documentation, explain why?This is a minor issue that helps in debugging.

[ISSUE #1566]Added logger to record the catched exception

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java

Fixes https://github.com/apache/incubator-eventmesh/issues/1725.
Motivation
This method accesses the value of a Map entry, using a key that was retrieved from a keySet iterator. It is more efficient to use an iterator on the entrySet of the map, to avoid the Map.get(key) lookup.
Modifications
we replace key set iteration by using entrySet.
Documentation
Does this pull request introduce a new feature? (yes / no) No
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) Not applicable
If a feature is not applicable for documentation, explain why? This is a minor issue that comes under code cleanup.

[ISSUE #1725] use entrySet replace key set iterator

---

eventmesh-examples/build.gradle
eventmesh-examples/src/main/java/org/apache/eventmesh/common/ExampleConstants.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/pub/eventmeshmessage/WorkflowAsyncPublishInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowAsyncSubscribe.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowOrderAsyncSubscribe.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowPaymentAsyncSubscribe.java
eventmesh-examples/src/main/java/org/apache/eventmesh/selector/NacosSelector.java
eventmesh-examples/src/main/resources/application.properties

Fixes #1927 .
Add workflow demo
Add workflow demo

[ISSUE #1927]add workflow demo

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java

Fixes #1724.
This method accesses the value of a Map entry, using a key that was retrieved from a keySet iterator. It is more efficient to use an iterator on the entrySet of the map, to avoid the Map.get(key) lookup.
Replaced  keySet iterator with entrySet in AsyncHTTPPushRequest

[ISSUE #1724]Replace keySet iterator with entrySet in AsyncHTTPPushRequest

---

eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/producer/AbstractProducer.java

Fixes #1958 .
Method calls String.format on a static (non parameterized) format string  [AbstractProducer]
located at:
org/apache/eventmesh/connector/pulsar/producer/AbstractProducer.java line 46 and 48.
add the %s string.

[ISSUE #1958] FIX: Method calls String.format on a static (non parameterized) format string [AbstractProducer]

---

eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/AsyncSyncRequestInstance.java

Fixes #1960
the field logger should add final
public static final Logger logger = LoggerFactory.getLogger(AsyncSyncRequestInstance.class);

[ISSUE #1960] Field isn't final but should be [AsyncSyncRequestInstance]

---

eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java

Drop useless code  
fix #1969 
Condition 'webHookFilePath != null' is always 'true'
This condition is always true, no need to judge.
Drop useless code  
ref #1969 
* Does this pull request introduce a new feature? (no)

[ISSUE #1969]Drop useless code 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java

Replace with Objects.equals()
ref #1966   Fixes #1966
'context != null ? !context.equals(session.context) : session.context != null' replaceable by 'Objects.equals()' expression.
Replace with Objects.equals()

[ISSUE #1966] Replace with Objects.equals()

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java

Fixes #1707.
Motivation
Modifications
Added null pointer exception check
Documentation
Does this pull request introduce a new feature? (yes / no) no
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable
If a feature is not applicable for documentation, explain why? This is a minor issue that comes under code cleanup

[ISSUE #1707]Add null pointer exception

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HttpProcessor.java

Fixes #1976.
Motivation
Modifier 'public' is redundant for interface members. All methods in an interface are implicitly public and abstract.
Modifications
Removed redundant modifiers
Documentation
- If a feature is not applicable for documentation, explain why? It is a minute issue which comes under code cleanup

[ISSUE #1976]Remove redundant modifiers

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/util/EventMeshClientUtil.java

Fixes #2010
Add NPE check
- If a feature is not applicable for documentation, explain why? It is a minor issue that comes under code cleanup

[ISSUE #2010] Add NPE check

---

eventmesh-connector-plugin/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/config/ConfigurationWrapper.java

Fixes #2022 .
* Use the methods that have been extracted
* org/apache/eventmesh/connector/redis/config/ConfigurationWrapper.java

[ISSUE #2022]Use the methods that have been extracted [redis ConfigurationWrapper]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java

Fixes https://github.com/apache/incubator-eventmesh/issues/1700 .
Motivation
Modifications
If we get null, we will simply return empty string.
Documentation
Does this pull request introduce a new feature? (yes / no) No
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) Not applicable
If a feature is not applicable for documentation, explain why? This is a minor issue that comes under code cleanup

[ISSUE #1700] add NPE check

---

eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/http/SendMessageRequestProtocolResolver.java

Fixes #1992
Possible null  pointer dereference due to return value of called method [SendMessageRequestProtocolResolver],line 65 and line 84
Add null pointer check

[ISSUE #1992] Possible null pointer dereference due to return value of called method [SendMessageRequestProtocolResolver]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java

Fixes #1727 .
This pull request uses entrySet in place of keySet in UnSubscribeProcessor for effective iteration of conf.
Used entrySet in place of keySet in UnSubscribeProcessor
- If a feature is not applicable for documentation, explain why? This does not change any functionality as it involves only refactoring
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation. Not Applicable

[ISSUE #1727]Used entrySet in place of keySet in UnSubscribeProcessor

---

eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/EventmeshAsyncSubscribe.java

Fixes #2065 .
located at:
org/apache/eventmesh/grpc/sub/EventmeshAsyncSubscribe.java line 40
Field of handler should be final.
Add final modifier.

[ISSUE #2065] Field of handler in EventmeshAsyncSubscribe.java isn't final but should be

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RejectClientByIpPortHandler.java

Fixes #2056 .
Motivation
Change try-catch-finally to try-with-resource to manage resources in a class.
Modifications
Change try-catch-finally to try-with-resource in the class of org.apache.eventmesh.runtime.admin.handler.RejectClientByIpPortHandler at line 57.
Documentation
Does this pull request introduce a new feature? (yes / no) no
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

[ISSUE #2056] Use try-with-resources to manage resources

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java

Fixes #2160
Method stores return result in local before immediately returning it [ConsumerManager]

[ISSUE #2160] Method stores return result in local before immediately returning it [ConsumerManager]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java

[ISSUE #2163]  This method needlessly uses a String literal as a Charset encoding [SendSyncMessageProcessor] 

---

eventmesh-connector-plugin/eventmesh-connector-redis/src/test/java/org/apache/eventmesh/connector/redis/consumer/RedisConsumerTest.java

Fixes #2167 .
Reliance on default encoding
add encode

[ISSUE #2167]fix_encoding

---

eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookConfigOperation.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2257
Interface methods are public by default, so you can remove the keyword public

[ISSUE #2257] remove interface public keywords

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/config/EventMeshGrpcClientConfig.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2267

[ISSUE #2267] Simplify the code

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/IOTinyUtilsTest.java

[ISSUE #2251]Reliance on default encoding [IOTinyUtilsTest]

---

eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/pub/eventmeshmessage/SyncRequestInstance.java

update log format in SyncRequestInstance.class
Fixes #2277.

[ISSUE #2277]update log format in SyncRequestInstance.class

---

eventmesh-webhook/eventmesh-webhook-admin/src/test/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperationTest.java

Fixes #2249
'assertTrue()' is simplified to 'assertEquals()'

[ISSUE #2249] 'assertTrue()' can be simplified to 'assertEquals()'

---

eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/config/PinpointConfiguration.java

[ISSUE #2239] BufferedReader creates an IO stream object, does not assign it to any fields, pass it to other methods that might close it, or return it, and does not appear to close the stream on all paths out of the method.

[ISSUE #2239] fix BufferedReader doesn't auto-close bug and use UTF-8.

---

eventmesh-connector-plugin/eventmesh-connector-redis/src/test/java/org/apache/eventmesh/connector/redis/connector/UnitTest.java

Fixes #2341
refacotr UnitTest.java line 90

[ISSUE #2341]Method encodes String bytes without specifying the character encoding

---

eventmesh-connector-plugin/eventmesh-connector-pravega/src/test/java/org/apache/eventmesh/connector/pravega/client/PravegaClientTest.java

Fixes #2349
refactor PravegaClientTest.java line 163
- If yes, how is the feature documented? ot documented)

[ISSUE #2349] Method encodes String bytes without specifying the character encoding

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/cloudevent/RabbitmqCloudEventTest.java

Fixes #2346 .
refactor eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/cloudevent/RabbitmqCloudEventTest.java line 43
add character encoding.

[ISSUE #2346] Method encodes String bytes without specifying the character encoding

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/consumer/RabbitmqConsumerTest.java

Fixes #2347 .
refactor RabbitmqProducerTest.java line 71,add character encoding.

[ISSUE #2347]  Method encodes String bytes without specifying the character encoding

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/producer/RabbitmqProducerTest.java

Fixes #2348
refactor eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/producer/RabbitmqProducerTest.java line 71
add character encoding.

[ISSUE #2348] Method encodes String bytes without specifying the character encoding

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java

Fixes #2383 .
remove Method concatenates the result of a toString() call
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java line 41
remove toString() method call.

[ISSUE #2383] Method concatenates the result of a toString() call

---

eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver/HttpRequestProtocolResolver.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java

Fixes #2384 .
refactor eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver/HttpRequestProtocolResolver.java line 76
using entrySet() replace keySet() method.

[ISSUE #2384] Inefficient use of keySet iterator instead of entrySet iterator

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java

Fixes #2382 .
Method concatenates the result of a toString() call
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java line 110
remove toString() method call.

[ISSUE #2382] Method concatenates the result of a toString()

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/HeartbeatProcessor.java

[ISSUE #2379]use != to compare two enum values

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/StreamPushRequest.java

Fixes #2375 .
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/StreamPushRequest.java line 105 107 115 117.

[ISSUE #2375] Method calls equals on an enum instance

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcp2Client.java

Fixes #2370 .
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcp2Client.java line 156,replace equals method with "==".

[ISSUE #2370] Method calls equals on an enum instance

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java

Fixes #2372 .
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java,replace equals method with '=='.

[ISSUE #2372] Method calls equals on an enum instance

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/MessageHandler.java

Fixes #2376 .
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/MessageHandler.java line 87.
replace equals method with "==".

[ISSUE #2376] Method calls equals on an enum instance

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java

Fixes #2374 .
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java line 239 241 250 252, replace equals method with "==".

[ISSUE #2374] Method calls equals on an enum instance

---

eventmesh-protocol-plugin/eventmesh-protocol-webhook/src/main/java/org/apache/eventmesh/protocol/webhook/WebHookProtocolAdaptor.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2539

[ISSUE #2539] Method stores return result in local before immediately returning it [WebHookProtocolAdaptor]

---

eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/config/PinpointConfiguration.java

Fixes #2542 .
Method uses immediate execution of a block of code that is often not used
refactor eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/config/PinpointConfiguration.java

[ISSUE #2542] Method uses immediate execution of a block of code that is often not used

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Subscription.java

Fixes #<XXXX>.
Local variables are returned immediately after assignment.
#2533 
Returned values immediately
- Does this pull request introduce a new feature? (yes / ~no~)
- If yes, how is the feature documented? (~not applicable~ / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why? Refactoring

[ISSUE #2533] - Fixed return statement warnings

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/workflow/protos/ExecuteResponse.java

Fixes #2536 
Method stores return result in local before immediately returning it [ExecuteResponse]
refactor eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/workflow/protos/ExecuteResponse.java

[ISSUE #2536] Method stores return result in local before immediately returning it [ExecuteResponse]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/BaseRequestBody.java

Fixes #2534 .
Method stores return result in local before immediately returning it [BaseRequestBody]
refactor eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/BaseRequestBody.java

[ISSUE #2534] Method stores return result in local before immediately returning it [BaseRequestBody]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/SimpleMessage.java

Fixes #2532 .
Method stores return result in local before immediately returning it [SimpleMessage]
refactor eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/SimpleMessage.java

[ISSUE #2532] Method stores return result in local before immediately returning it [SimpleMessage]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Response.java

Fixes #2531 .
Method stores return result in local before immediately returning it [Response]
refactor eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Response.java 

[ISSUE #2531] Method stores return result in local before immediately returning it [Response]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/tcp/EventMeshTcpMonitor.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2594

[ISSUE #2594]Method passes a simple String.format result to an SLF4J's or Log4j2's format string [EventMeshTcpMonitor]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/RegistryResponse.java

Fixes #2527 .
Method stores return result in local before immediately returning it [RegistryResponse]
refactor
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/RegistryResponse.java

[ISSUE #2527] Method stores return result in local before immediately returning it [RegistryResponse]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/RegistryRequest.java

Fixes #2526 .
Method stores return result in local before immediately returning it [RegistryRequest]
refactor
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/RegistryRequest.java

[ISSUE #2526] Method stores return result in local before immediately returning it [RegistryRequest]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/HttpTinyClient.java

Fixes #2598 .
This method needlessly uses a String literal as a Charset encoding [HttpTinyClient]
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/HttpTinyClient.java

[ISSUE #2598] This method needlessly uses a String literal as a Charset encoding [HttpTinyClient]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/HeartbeatService.java

Fixes #2595 .
Method specifies an unrelated class when allocating a Logger [HeartbeatService]
refactor 
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/HeartbeatService.java

[ISSUE #2595] Method specifies an unrelated class when allocating a Logger [HeartbeatService]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/AbstractPushRequest.java

Fixes #2596 .
Method specifies an unrelated class when allocating a Logger [AbstractPushRequest] 
refactor located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/AbstractPushRequest.java

[ISSUE #2596] Method specifies an unrelated class when allocating a Logger [AbstractPushRequest] 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/AbstractTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/GoodbyeTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HeartBeatTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HelloTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/ListenTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageAckTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/RecommendTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/SubscribeTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/UnSubscribeTask.java

Fixes #2601 .
Method calls equals on an enum instance [MessageTransferTask]
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java AbstractTask.java and sub Classes.

[ISSUE #2601] Method calls equals on an enum instance [MessageTransferTask]

---

eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver/HttpRequestProtocolResolver.java

Fixes #2629 .
pmd warn:
1.PreserveStackTrace .
2.UseLocaleWitchCaseConversions.
1.throw new Exception with the cause exception.
2.add default locale.

[ISSUE #2629]HttpRequestProtocolResolver pmdTest warn

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java

Fixes #2677 
Original code call then same method redundantly, this pr is about to fix it. 
refactor eventmesh-eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java; use temporary variable to avoid redundantly calling same method.

[ISSUE #2677] Method appears to call the same method on the same object redundantly [UnSubscribeProcessor]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/exception/EventMeshException.java

Fixes #2643 .
Class defines a computed serialVersionUID that doesn't equate to the calculated value [EventMeshException]
recompute the serialVersionUID using IDE.

[ISSUE #2643] Class defines a computed serialVersionUID that doesn't equate to the calculated value [EventMeshException]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java

Fixes #2661 .
Method uses immediate execution of a block of code that is often not used [AbstractEventProcessor]
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java
use Optional.orElseGet()

[ISSUE #2661] Method uses immediate execution of a block of code that is often not used [AbstractEventProcessor]

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPPubClient.java

Fixes #2652 .
Method rr(EventMeshMessage, long) throws alternative exception from catch block without history
use the logger to record exception messages.

[ISSUE #2652] Method rr(EventMeshMessage, long) throws alternative exception from catch block without history

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2693

[ISSUE #2693] SendAsyncEventProcessor judgment blanks can be simplified

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2695

[ISSUE #2695] AbstractEventProcessor can be defined as an abstract class and then implement AsyncHttpProcessor to make the structure clearer

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java

Fixes #2675.
* Redundant function call in `eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java` lines  `82` and `91`.
* Method call combined with a local variable.
- Does this pull request introduces a new feature?  no

[ISSUE #2675] [Enhancement] Method appears to call the same method on the same object redundantly [SubscribeProcessor]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/AbstractTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/SubscribeTask.java

Fixes #2722 .
Method run() uses integer based for loops to iterate over a List
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/SubscribeTask.java, repalce for with foreach.

[ISSUE #2722] Method run() uses integer based for loops to iterate over a List

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPClientPool.java

Fixes #2725 .
Method shutdown() creates iterators on synchronized collections
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPClientPool.java 

[ISSUE #2725] Method shutdown() creates iterators on synchronized collections

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/RemotingHelperTest.java

Fixes #2710 .
Method stores return result in local before immediately returning it [RemotingHelper] 
refacotr 
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java,
Returns the value assigned to the local variable directly, redefine as abstract class.

[ISSUE #2710] Method stores return result in local before immediately returning it [RemotingHelper] 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java

Fixes #2707 .
Method stores return result in local before immediately returning it [AbstractRemotingServer]
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java 
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java

[ISSUE #2707] Method stores return result in local before immediately returning it [AbstractRemotingServer]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/http/HTTPMetricsServer.java

Fixes #2724 .
Method passes a concatenated string to SLF4J's or Log4j2's format string [HTTPMetricsServer]
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/http/HTTPMetricsServer.java ,
use {} markers to inject dynamic content into the string.

[ISSUE #2724] Method passes a concatenated string to SLF4J's or Log4j2's format string [HTTPMetricsServer]

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/config/ClientConfiguration.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/KnativeConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/producer/KnativeProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/test/java/org/apache/eventmesh/connector/knative/config/ClientConfigurationTest.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/test/java/org/apache/eventmesh/connector/knative/producer/KnativeProducerImplTest.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/test/resources/knative-client.properties

Fixes #2576.
Enhancement the config manage for project
[1] KnativeConsumerImpl and KnativeProducerImpl config improve
[2] KnativeConsumerImpl and KnativeProducerImpl config UT

[ISSUE #2576] Improve configuration management of Knative SPI Impl

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientBySubSystemHandler.java

Fixes #2703 .
Method handle(HttpExchange) manually handles closing an auto-closeable resource [RedirectClientBySubSystemHandler]
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientBySubSystemHandler.java,
change to use try-with-resources to manage resources.

[ISSUE #2703] Method handle(HttpExchange) manually handles closing an auto-closeable resource [RedirectClientBySubSystemHandler]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RejectAllClientHandler.java

Fixes #2704 .
Method handle(HttpExchange) manually handles closing an auto-closeable resource [RejectAllClientHandler] 
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RejectAllClientHandler.java,
change to use try-with-resources to manage resources.

[ISSUE #2704] Method handle(HttpExchange) manually handles closing an auto-closeable resource [RejectAllClientHandler] 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/SSLContextFactory.java

Fixes #2706 .
Method handle(HttpExchange) manually handles closing an auto-closeable resource [SSLContextFactory]
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/SSLContextFactory.java,
change to use try-with-resources to manage resources.

[ISSUE #2706] Method handle(HttpExchange) manually handles closing an auto-closeable resource [SSLContextFactory]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/Client.java

Fixes #2654 .
Method uses immediate execution of a block of code that is often not used [LocalSubscribeEventProcessor] 
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java ,
use Optional.orElseGet().

[ISSUE #2654] Method uses immediate execution of a block of code that is often not used [LocalSubscribeEventProcessor] 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/Client.java

Fixes #2729 .
Method check a map with containsKey(), before using get() [UnSubscribeProcessor]
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java ,
fetch the value with get, and checking for non null instead.

[ISSUE #2729] Method check a map with containsKey(), before using get() [UnSubscribeProcessor]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/dispatch/FreePriorityDispatchStrategy.java

Fixes #2709 .
Method stores return result in local before immediately returning it [FreePriorityDispatchStrategy] 
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/dispatch/FreePriorityDispatchStrategy.java.

[ISSUE #2709] Method stores return result in local before immediately returning it [FreePriorityDispatchStrategy] 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java

Fixes #2656 .
Method uses immediate execution of a block of code that is often not used [LocalUnSubscribeEventProcessor]
replace Optional.orElse() with Optional.orElseGet().

[ISSUE #2656] Method uses immediate execution of a block of code that is often not used [LocalUnSubscribeEventProcessor]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java

Fixes #2726 .
Method check a map with containsKey(), before using get() [LocalSubscribeEventProcessor]
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java ,
It is much simpler to just fetch the value with get, and checking for non null instead.

[ISSUE #2726] Method check a map with containsKey(), before using get() [LocalSubscribeEventProcessor]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/header/message/SendMessageBatchV2ResponseHeader.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java

Fixes #2676 .
To avoid calling the same method on the same object redundantly.
* add  `parseChannelLocalAddr` in RemotingHelper to get local address from channel.
* assign `eventMeshIp` in `buildHeader` by using IPUtil instead of passing the value to it.

[ISSUE #2676] fix call the same method on the BatchSendMessageV2Processor redundantly

---

eventmesh-dashboard/components/navigation/MenuItem.tsx
eventmesh-dashboard/components/navigation/Menus.tsx
eventmesh-dashboard/components/navigation/MenusMobile.tsx
eventmesh-dashboard/pages/eventCatalogs/EventCatalogs.tsx
eventmesh-dashboard/pages/eventCatalogs/SchemaView.tsx
eventmesh-dashboard/pages/eventCatalogs/index.ts
eventmesh-dashboard/pages/eventCatalogs/types.ts
eventmesh-dashboard/pages/workflows/create.tsx
eventmesh-dashboard/pages/workflows/details.tsx
eventmesh-dashboard/pages/workflows/index.ts
eventmesh-dashboard/pages/workflows/workflows.tsx

Fixes #2828 Missing Apache header in some code files of the Dashboard.
Added Apache header in navigation menu, workflows, event catalogs files
Added Apache header in navigation menu, workflows, event catalogs files
No need

[ISSUE #2828] Added Apache header in navigation menu, workflows, event catalogs files

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/WebhookUtil.java

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>
Fixes #2803.
When an exception occurs in a statement inside `try`, the program will simply crash. Catching exceptions in time helps to reduce the impact of exceptions.
Catch the IOException directly. 

[ISSUE #2803] Fix SpringBootDemoApplication crash

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/WebhookUtil.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/WebhookUtilTest.java

Fixes #2849 .
fix bug:
org.apache.eventmesh.runtime.util.WebhookUtilTest > testObtainDeliveryAgreement FAILED
modify assertion

[ISSUE #2849] org.apache.eventmesh.runtime.util.WebhookUtilTest > testObtainDeliveryAgreement FAILED

---

eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumerTest.java

Fixes #2819 .
fix EventMeshGrpcConsumerTest.testSubscribeWithUrl() sometimes fail
add wait time to 20_000 ms.

[ISSUE #2819]  fix EventMeshGrpcConsumerTest.testSubscribeWithUrl() sometimes fail

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/consumergroup/StreamTopicConfig.java

Fixes #2739 .
Method calls equals on an enum instance [EventMeshConsumer]
Change it to use "==" or "! =".

[ISSUE #2739] Method calls equals on an enum instance [StreamTopicConfig]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java

Fixes #2740 .
Method calls equals on an enum instance [EventMeshConsumer]
Change it to use "==" or "! =".

[ISSUE #2740] Method calls equals on an enum instance [EventMeshConsumer]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/HTTPClientHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumer/ClientInfo.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumer/SubscriptionManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/ConsumerGroupConf.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java

Fixes #2852 .
- add `SubscriptionManager` to manage client info adn sub topics;
- reduce redundant code for updating client info and sub topics info;
- add `SubscriptionManager` and move 'localConsumerGroupMapping' 'localClientInfoMapping' from `EventMeshHTTPServer` to `SubscriptionManager`;
- use `SubscriptionManager` to registerClient on `SubscribeProcessor`;
- use `SubscriptionManager` to registerClient on `LocalSubscribeEventProcessor`;
- use `SubscriptionManager` to update sub topics on `SubscribeProcessor`;
- use `SubscriptionManager` to update sub topics on `LocalSubscribeEventProcessor`;

[ISSUE #285] add SubscriptionManager

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java

Fixes #2674 .
Method appears to call the same method on the same object redundantly [SendSyncMessageProcessor]
These method calls could be combined by assigning the result into a temporary variable, and using the variable the second time.

[ISSUE #2674] Method appears to call the same method on the same object redundantly [SendSyncMessageProcessor]

---

eventmesh-metrics-plugin/eventmesh-metrics-api/src/main/java/org/apache/eventmesh/metrics/api/model/TcpSummaryMetrics.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/controller/EventMeshAdminController.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ConfigurationHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/HTTPClientHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/MetricsHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/tcp/EventMeshTcpMonitor.java

Fixes #2671  
Method appears to call the same method on the same object redundantly [SendAsyncEventProcessor]
These method calls could be combined by assigning the result into a temporary variable, and using the variable the second time.

[ISSUE #2671] Method appears to call the same method on the same object redundantly [SendAsyncEventProcessor]

---

eventmesh-sdk-go/README.md
eventmesh-server-go/Makefile
eventmesh-server-go/README.md

Fixes #2863 .
eventmesh-server-go module add golangci-lint command in Makefile
modify Makefile add lint command .
- If yes, how is the feature documented? (docs)
see README.md

[ISSUE #2863] eventmesh-server-go module add golangci-lint command in Makefile 

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigFiled.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigService.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/convert/converter/ObjectConverter.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/config/ConfigServiceTest.java
eventmesh-common/src/test/resources/newConfiguration-common.properties
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/boot/EventMeshServerTest.java
eventmesh-runtime/src/test/resources/newConfiguration-runtime.properties
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManage.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/config/AdminConfiguration.java
eventmesh-webhook/eventmesh-webhook-admin/src/test/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManageTest.java
eventmesh-webhook/eventmesh-webhook-admin/src/test/java/org/apache/eventmesh/webhook/config/AdminConfigurationTest.java
eventmesh-webhook/eventmesh-webhook-admin/src/test/resources/eventmesh.properties
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookOperationConstant.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookController.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/config/ReceiveConfiguration.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/HookConfigOperationManage.java
eventmesh-webhook/eventmesh-webhook-receive/src/test/java/org/apache/eventmesh/webhook/receive/config/ReceiveConfigurationTest.java
eventmesh-webhook/eventmesh-webhook-receive/src/test/resources/eventmesh.properties

Fixes #2576.
Enhancement the config manage for project
[1] WebHook config improve
[2] WebHook config UT

[ISSUE #2576] Improve configuration management of WebHook

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpEventWrapper.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPClientPool.java

Fixes #2878.
fix issue 2878 
remove invalid imports.
fix issue 2878 
remove invalid imports.

[ISSUE 2878] Fix WebHook deserialization exception

---

eventmesh-connector-plugin/eventmesh-connector-redis/build.gradle

Fixes #2875 .
eventmesh-connector-redis:test jvm crash when using openjdk8.
gradle test task add systemProperty "io.netty.tryUnsafe", "false".

[ISSUE #2875] eventmesh-connector-redis:test jvm crash when using openjdk8

---

eventmesh-connector-plugin/eventmesh-connector-redis/src/test/java/org/apache/eventmesh/connector/redis/config/RedisPropertiesTest.java
eventmesh-connector-plugin/eventmesh-connector-redis/src/test/resources/redis-client.properties

Fixes #2925 .
fix :eventmesh-connector-plugin:eventmesh-connector-redis:test error.
modiy redis-client.properties 
eventMesh.server.redis.redisson.threads=2
eventMesh.server.redis.redisson.nettyThreads=2

[ISSUE #2925] eventmesh-connector-plugin:eventmesh-connector-redis:test error

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/BatchMessageWrapper.java

Fixes #2646 .
The computed SerialVersionUID was not a computed value. the new value is computed using Intellij IDEA
SerialVersionUID is recomputed for BatchMessageWrapper.java class using Intellij IDEA
- Does this pull request introduce a new feature?  (no)

[ISSUE #2646] Recomputing SerialVersionUID for BatchMesageWrapper

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java

Fixes #1538 .
The method uses an integer-based for loop to iterate over a java.util.List, by calling List.get(i) each time through the loop. This can lead to poor performance and issues when using other collection types. The goal of this change is to improve performance and flexibility by using iterators or foreach loops instead.
Replaced the integer-based for loop with an iterator or foreach loop in the method located at org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java line 1558 and 1560
- If a feature is not applicable for documentation, explain why? This pull request does not introduce a new feature, it only improves the performance and flexibility of the …

[ISSUE #1538] Fixes issue with integer-based for loop in BatchMessage.java

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java

Fixes #2715 
Motivation
Top reasons to use isEmpty instead of size()
it is more expressive (the code is easier to read and to maintain)
it is faster, in some cases by orders of magnitude.
Modifications
Changed the size() method on a collection to isEmpty()
Documentation

Issue #2715 Update ClientSessionGroupMapping.java

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpEventWrapper.java

Fixes #2649.
To know more about serialVersionUID and this issue.
Generated a new serialVersionUID to fix this issue.
- Does this pull request introduce a new feature?: No

[ISSUE #2649] Class defines a computed serialVersionUID that doesn't equate to the calculated value [HttpEventWrapper]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/ProducerGroupConf.java

Fixes #<2988>.
implemeted equals() method for comparison
Changes in ProducerGroupConf.java file
This is not applicable for documentation because it only changes the way String values are compared. The core functionality remains same

[ISSUE #2988] implemented equals() in String values comparison (#2988)

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java

Fixes #2987.
Boxed sendBackTimes to prevent NullPointerException
modifications in ClientGroupWrapper.java file
This is not applicable for documentation because it only manages the NullPointerException .The core functionality remains same

[ISSUE #2987] Boxed sendBackTimes to prevent NullPointerException

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java

This method concatenates the output of a toString() call into a StringBuffer or StringBuilder. It is simpler just to pass the object you want to append to the append call, as that form does not suffer the potential for NullPointerExceptions, and is easier to read.

[ISSUE #2984] Method concatenates the result of a toString() call[SendAsyncEventProcessor]

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/SubStreamHandler.java

[ISSUE #2973]Method passes a concatenated string to SLF4J's or Log4j2's format string[SubStreamHandler]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java

fix #2978 
Can be replaced with single 'Map.computeIfAbsent' method call[HeartBeatProcessor]

[ISSUE #2978] [Enhancement] Can be replaced with single 'Map.computeIfAbsent' method call[HeartBeatProcessor]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/retry/RetryContext.java

[ISSUE #3090] Can be replaced with 'Long.compare' [tcp RetryContext]

---

eventmesh-registry-plugin/eventmesh-registry-zookeeper/src/main/java/org/apache/eventmesh/registry/zookeeper/service/ZookeeperRegistryService.java

Fixes #3105 .
*NPE check brefore calling a method if there is needed, add NPE check via Objects::requireNonNull.*
*- line 158: EventMeshInstance::getMetaData;*
*- line 206: EventMeshInstance::getMetaData;*
*- line 259: String::getBytes*

[ISSUE #3105] Check for NPE

---

eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolAdaptor.java

Fixes #3106 
Method:
public static <T> T requireNonNull(T obj, String message)
The Objects.requireNonNull() method is used to check that the values associated with the keys CONSTANTS_KEY_HEADERS and CONSTANTS_KEY_BODY are not null before calling the JsonUtils.serialize and getBytes methods on them. If either of the values is null, the method throws a NullPointerException with the specified error message.
line 105 : added requireNonNull method and message "Headers must not be null");
line 106 : added requireNonNull method and message "Bodymust not be null");

[ISSUE #3106] Null check for dataContentMap in HttpProtocolAdaptor.java

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/EventHandler.java

Fixes #3097 
Added `requireNonNull` on serialize, deserialize, getBytes method invocations.

[ISSUE #3097] Require non-null for methods serialize/deserialize

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/EventHandler.java

Fixes #3006.
It is a good practice to make use of auto closable resources with try-with-resources.
Replaced finally blocks with try-with-resources for closing OutputStream. 

[ISSUE #3006] Replaced finally blocks with try-with-resources

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/producer/ProducerManager.java

Fixes #3100 .
Here the final keyword is used to stop the value change in eventMeshGrpcServer and producerTable
Made the variables final in line 33, 35

[ISSUE #3100] Field may be 'final'[ProducerManager]

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/openmessage/OpenMessageTCPClient.java

Fixes #3092 .
Removed the if statements at line 101,109 as the conditions are always true so it doesn't effect the functionality.

[ISSUE #3092] Conditions are always 'true' [OpenMessageTCPClient]

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java

Fixes #3170.
Hi i'am new to opensource hoping to contribute to projects i find interesting...
Checks and throws for NPE before sending null to as an argument to the function.
located at:
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java line 84:53
Added the null pointer check so that it throws before sending the null as an argument.

[ISSUE #3170] function argument NPE check fix

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/file/WatchFileManagerTest.java

Fixes #3168 
I have changed the api s used to read to and write from the file
previous --> Line 53 - 57
updated --> Line 56 - 68
made sure the resources are closed by enclosing it with try with resources.
made sure the test fails if it fails to read from the given file or fails to write to it.

[ISSUE #3168] IO streams closed, encoding set to UTF_8, test fails if file change not occurred

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/acl/Acl.java
eventmesh-security-plugin/eventmesh-security-acl/src/main/java/org/apache/eventmesh/acl/impl/AclServiceImpl.java
eventmesh-security-plugin/eventmesh-security-acl/src/test/java/org/apache/eventmesh/acl/impl/AclServiceImplTest.java
eventmesh-security-plugin/eventmesh-security-api/src/main/java/org/apache/eventmesh/api/acl/AclProperties.java
eventmesh-security-plugin/eventmesh-security-api/src/main/java/org/apache/eventmesh/api/acl/AclService.java
eventmesh-security-plugin/eventmesh-security-api/src/test/java/org/apache/eventmesh/api/acl/AclServiceTest.java

Fixes #3181 
The AclService interface has been modified so that its methods can receive custom objects
AclService method field fix

[ISSUE #3181] The method parameter properties of the aclService is adjusted to an object parameter, providing extended fields

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/GrpcClientHandler.java

Fixes #2999.
literal string comparision changed in 4 lines in handle(HttpExchange httpExchange) method in GrpcClientHandler.java

[ISSUE #2999]Method makes literal string comparisons passing the literal as an argument [GrpcClientHandler]

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/SubClientImpl.java

Fixes #3150 .
Locating at eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/SubClientImpl.java
- Line 47: Re-foramt according to code style;
- Line 94: Logging rather than console trace;

[ISSUE #3150] Method prints the stack trace to the console[SubClientImpl]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java

Fixes #3271 
if HTTPHandler execute ReferenceCountUtil.release method, then SimpleChannelInboundHandler execute ReferenceCountUtil.release will throw IllegalReferenceCountException. Because relase is performed twice for one reference. So need to remove ReferenceCountUtil.release from HTTPHandler 
*Fix handle http message throw IllegalReferenceCountException*

[ISSUE #3271]Fix handle http message throw IllegalReferenceCountException

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/EventMeshMessageProducer.java

[ISSUE #3284] Fix HTTP server HttpRequest release bug

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/ConsumerImpl.java

Fixes #3307.
It is possible that the Kafka consumer will be closed twice. It will raise an IllegalStateException when being closed again.
Since we call `consumer.close()` in `ConsumerImpl.java`. The consumer is already closed. In the final shutdown of eventmesh, the `finally` section of code in the `KafkaConsumerRunner` will also be called, resulting in closing the consumer twice.
As a result, I modify the code to call the shutdown method in the `KafkaRunner`, and then shut down the executor to prevent the executor from running forever.
- If a feature is not documented yet …

[ISSUE #3307] Kafka Consumer Shuts Down Properly

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java

Made changes in eventmesh-examples.
Added null pointer exception to method invocation 'getbytes'. Open for help and feel free to add any thing.
Fixes #3260

[ISSUE #3260] Added Null ptr excep to method

---

eventmesh-storage/eventmesh-storage-api/src/main/java/org/apache/eventmesh/api/admin/Admin.java
eventmesh-storage/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/admin/RocketMQAdmin.java
eventmesh-storage/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/admin/RocketMQAdminAdaptor.java
eventmesh-storage/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/admin/StandaloneAdmin.java
eventmesh-storage/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/admin/StandaloneAdminAdaptor.java
eventmesh-storage/eventmesh-storage-standalone/src/test/java/org/apache/eventmesh/storage/standalone/admin/StandaloneAdminTest.java

Fixes https://github.com/apache/incubator-eventmesh/issues/3491
Make some refactoring for class `StandaloneAdmin` and `RocketMQAdmin`.  We can try this, but th will need more refactoring and some discussion before.
- Use properties or
- If not used, then delete it
- Segregate the `Admin` interface by creating an interface `Initialize` that contain the `void init(Properties properties)` method.
Remove the `Propertie` parameter from the constructor.

[ISSUE #3491] Refactor class StandaloneAdmin and RocketMQAdmin

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/GrpcClientHandler.java

Fixes #3007  .
Used try-with-resources to manage resources.

#3007 [Enhancement] Method manually handles closing an auto-closeable resource [GrpcClientHandler]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/EventMeshMessage.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java

Fixes #3523 .
bug fix for redis storage. After this change, the json be serialized successfully and the consumer can consume the data.

[ISSUE #3523] fix json serialization issue when using redis

---

build.gradle
tools/dependency-check/known-dependencies.txt

Bump nacos client version from 2.1.0 to 2.2.1. That's a regular update.

[ISSUE ##3555] Bump nacos client version from 2.1.0 to 2.2.1

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java

Fixes #3410.
The issue was that the getData() method in SendAsyncEventProcessor could return null, which could cause a NullPointerException to be thrown. 
To prevent this, the suggested solution is to use Objects.requireNonNull().
The modification made to the code was to add a call to Objects.requireNonNull() around the getData() method call in SendAsyncEventProcessor. This ensures that if getData() returns null, a NullPointerException will be thrown immediately, making it easier to locate and fix the issue.
- If yes, how is the feature documented? (n/a)
- If a feature is not applicable for documentation, explain why? (n/a) …

Fixed issue with 'Objects.requireNonNull()' where getData() can return null

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfigurationTest.java

Modified the assertEquals method which was earlier in the form of Assert.assertEquals(actual, expected) to be in the 
correct order which is Assert.assertEquals(expected, actual).
No

[ISSUE #3521] Swapped the actual and expected values

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java

Fixes #3395 
Using isEmpty() to check whether the collection is empty or not.
Changed "size()>0" to "isEmpty()"
No
Not Applicable

[ISSUE #3395]Use isEmpty() to check whether the collection is empty or not.[ClientSessionGroupMapping]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshVersion.java

Fixes #3464 
When String::replaceAll is used, the first argument should be a real regular expression. If it’s not the case, String::replace does exactly the same thing as String::replaceAll without the performance drawback of the regex.
Replaced "replaceAll()" with "replace()"
No
Not Applicable

[ISSUE #3464]Replace this call to "replaceAll()" by a call to the "replace()" method.[EventMeshVersion]

---

eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/consumer/PushConsumerImpl.java

Fixes #3483 
When String::replaceAll is used, the first argument should be a real regular expression. If it’s not the case, String::replace does exactly the same thing as String::replaceAll without the performance drawback of the regex.
Replaced "replaceAll()" with "replace()"
No

[ISSUE #3483]Replace this call to "replaceAll()" by a call to the "replace()" method.[PushConsumerImpl]

---

eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/producer/ProducerImpl.java

Fixes #3482 
When String::replaceAll is used, the first argument should be a real regular expression. If it’s not the case, String::replace does exactly the same thing as String::replaceAll without the performance drawback of the regex.
Replaced "replaceAll()" to "replace()"
No

[ISSUES #3482]Replace this call to "replaceAll()" by a call to the "replace()" method.[ProducerImpl]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java

[Fixes #3165] "Actual value of parameter 'defaultValue' is always"
Since the 'defaultValue' variable is going to be empty throughout. Hence, there is no requirement of a third parameter.
Removed the parameter 'defaultValue' at line 256. Replaced 'defaultvalue' with "" at line 258 . I have also removed the third parameter at lines 196 and 197.
No
Not applicable

[ISSUE #3165]Actual value of parameter 'defaultValue' is always"

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TCPClientHandler.java

Fixes #3019
Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms.
Above issue is the reason why this change is introduced.
Issue #3019
Passed Constants.DEFAULT_CHARSET as the parameter to getBytes() method in line 115,116,167,168,178,179 of TCPClientHandler.java class.
- Ans: no
- Ans: Passed a parameter to the existing method in TCPClientHandler.java class.

[ISSUE #3019] Found reliance on default encoding: String.getBytes() [TCPClientHandler]

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByPathHandlerTest.java

Fixes #3159
Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms.
Above issue is the reason why this change is introduced.
Issue #3159
Modified response variable of RedirectClientByPathHandlerTest class present in Line 127
Earlier value of response variable used to be outputStream.toString()
New value of response variable is outputStream.toString(Constants.DEFAULT_CHARSET.name());
- Ans: no
- Ans: Modified a variable in RedirectClientByPathHandlerTest class.

[ISSUE #3159] Found reliance on default encoding [RedirectClientByPathHandlerTest]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/MonitorMetricConstants.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/tcp/EventMeshTcpMonitor.java

Modified two constants in MonitorMetricConstants (EVENTMESH_MONITOR_FORMAT_COMMON, EVENTMESH_TCP_MONITOR_FORMAT_THREADPOOL) to work without using String.format()
Fixes #2975
removed String.format() and modified the format constants to use {} instead of %s.
using {} doesn't require us to use String.format() and is also supported by the logger.
removed use of String.format()
modified format constants EVENTMESH_TCP_MONITOR_FORMAT_THREADPOOL, EVENTMESH_MONITOR_FORMAT_COMMON
- If a feature is not applicable for documentation, explain why? (it is a simple fix for an issue where we wanted to get rid of using String.format() as it is not required by logger)

[ISSUE #2975] removed String.format()

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/retry/RetryContext.java

Fixes #3734.
Aoid `Not annotated parameter overrides @NotNull parameter`.
Add `@Nonnull` for parameter

[ISSUE #3734]Not annotated parameter overrides @NotNull parameter[tcp RetryContext]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java

Fixes #3416
*Because Double Brace Initialization (DBI) creates an anonymous class with a reference to the instance of the owning object, its use can lead to memory leaks if the anonymous inner class is returned and held by other objects. Even when there’s no leak, DBI is so obscure that it’s bound to confuse most maintainers.*
*Fixes the above mentioned issue.*
Issue #3416
*Modified the initialization of localClients instance on line 391,451.*
- Ans: no
- Ans: Only changed the method of initialization of an instance.

[ISSUE #3416] Used another way to initialize localClients instance [HttpClientGroupMapping]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TopicHandler.java

Fixes #3012
*This method allocates and uses an auto closeable resource. However, it manually closes the resource in a finally block. While this is correct management, it doesn't rely on the idiomatic way available to JDK 7 and above, allows for possible subtle problems, and complicates the reading of code by developers expecting the use of try-with-resources.*
*Fixes the above mentioned issue.*
Issue #3012
*Changed conventional try-catch-finally block to try-with-resources.*
- Ans: no
- Ans: Replaced conventional try-catch-finally block to try-with-resources.

[ISSUE #3012] Method modified to handle auto-closeable resource [TopicHandler]

---

eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcMessageProtocolResolver.java

Fixes #3849.
Fixes #3839
org.apache.eventmesh.protocol.cloudevents.resolver.grpc.GrpcMessageProtocolResolver:
Many unused variable in `buildBatchEvents()`.
`getMessageItemValue()` and `getHeaderValue()` have the same body.
Some logic ignore the existing api.
And so on.
Remove unused variables and repetitive method. Use existing api. And other modifications.

[ISSUE #3849]GrpcMessageProtocolResolver has many unused variables and repetitive method def.

---

eventmesh-storage-plugin/eventmesh-storage-standalone/src/test/java/org/apache/eventmesh/storage/standalone/TestUtils.java

Fixes #3870.
When we can estimate the size of Map, specifying the initialization size is better.
Specify the initialization size.

[ISSUE #3870]Specifying the initial capacity of Map can save resources

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ConfigurationHandler.java

Fixes #2997 .
This line is in the form of String str = str.equals("someOtherString");
A NullPointerException may occur if the String variable str is null.
If instead the code was restructured to String str = "someOtherString".equals(str);that is, call equals() on the string literal, passing the variable as an argument, then this exception could never happen as both equals() check for null.

[ISSUE#2997][Enhancement] Method makes literal string comparisons passing the literal as an argument [ConfigurationHandler] 

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpCommand.java

Fixes #3837 
Changed to private and add the transient modifier at lines 60,61

[ISSUE #3837]Change to private and add the transient modifier[HttpCommand]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventMeshRebalanceImpl.java

Fixes #3863 
Method name misspelled.
- Rename EventmeshRebalanceImpl class name and EventmeshRebalanceImpl#caculateRedirectNum method name

[ISSUE #3863]Rename EventmeshRebalanceImpl class name and EventmeshRebalanceImpl#caculateRedirectNum method name

---

eventmesh-runtime/conf/server.env
style/checkStyle.xml
style/checkstyle-header1.txt
style/checkstyle-header2.txt
style/checkstyle-header3.txt

Fixes #3926.
checkStyle.xml can not check the file header.
Enable checkstyle.xml to check the file header.

[ISSUE #3926]checkStyle.xml can not check the file header

---

eventmesh-admin/eventmesh-admin-rocketmq/src/test/java/org/apache/eventmesh/admin/rocketmq/response/TopicResponseTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/JsonUtilsTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/NetUtilsTest.java

Fixes #3946.
Import code coverage of NetUtils, TopicResponse.
Add test methods of `NetUtils#sendSuccessResponseHeaders()`.
Add test class for `TopicResponse`.

[ISSUE #3946]Add unit test method or class for classes: NetUtils, TopicResponse 

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/Operation.java

ISSUE #3900
Removed additional null check as both Objects.requireNonNull and later explicit null check is doing the same thing.
Fixes #3900.
* as the issue suggest, there is an extra null check that is exhibiting the same functionality. as the Objects.requireNonNull throws NPE if the object is null. the later null check is redundant the execution won't reach the later check. 
* Removed the additional redundant null check. 
- If a feature is not applicable for documentation, explain why? simple code refactoring.

[ISSUE #3900] Removed Additional Null Check

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Heartbeat.java

[ISSUE #4029 ] Comparison using reference equality instead of value equality.[Heartbeat]

---

eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/MessageQueue.java

Fixes #3983 
*Optimize MessageQueue and add some comments*

[ISSUE #3983] Optimize MessageQueue

---

eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusGrpcExporter.java
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusHttpExporter.java
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusTcpExporter.java
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/utils/PrometheusExporterUtils.java

Fixes #4079.
Error occurs when building metric observer. Because the metrics of EventMesh is not ready yet, they should not be obtained at that time. Eg `v.apply(summaryMetrics)` get metrics here
```
paramPairs.forEach((k, v) ->
observeOfValue(meter, METRICS_GRPC_PREFIX + k[0], k[1], GRPC, v.apply(summaryMetrics)));
```
Modify the method `PrometheusExporterUtils#observeOfValue()` to make the action of getting metrics deferred execution.
Eg `getMetric` is `Function` here. It can defer the action of getting metrics.
```
paramPairs.forEach((metricInfo, getMetric) ->
observeOfValue(meter, METRICS_GRPC_PREFIX + metricInfo[0], metricInfo[1], GRPC, summaryMetrics, getMetric));
```
- If yes, how is the feature documented? (not …

[ISSUE #4079]The error of building metric observer: java.util.NoSuchElementException

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/retry/HttpRetryer.java

Fixes #4110.
If a thread is interrupted while in a blocked state, in order to prevent subsequent code from making erroneous judgments after handling the interruption, the `InterruptedException` is thrown and at the same time, the `Thread.interrupted()` method is called to clear the thread's interrupt status.
If the dispatcher is interrupted while executing the `take()` method, it will catch the `InterruptedException` exception and continue executing the exception handling block. At this point, the information about the thread being interrupted should not be lost. However, because `InterruptedException` is a `checked exception`, if it is not handled, it will be propagated to the method caller and may be thrown in `EventMeshHTTPServer.java`, resulting in a delayed closure of the thread. …

[ISSUE #4110] Enhance thread handling of InterruptedException

---

eventmesh-registry-plugin/eventmesh-registry-consul/src/main/java/org/apache/eventmesh/registry/consul/config/ConsulTLSConfig.java
eventmesh-registry-plugin/eventmesh-registry-consul/src/main/java/org/apache/eventmesh/registry/consul/service/ConsulRegistryService.java
eventmesh-runtime/conf/eventmesh.properties

Fixes #4069.
The registry plugin Consul does not support `TLSConfig` for now. 
Add TLSConfig to registry plugin Consul.

[ISSUE #4069]Add TLSConfig to registry plugin Consul. 

---

eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/source/connector/OpenFunctionSourceConnector.java
eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java

Fixes #4133 
*Optimize OpenFunctionSourceConnector poll*

[ISSUE #4133]Optimize OpenFunctionSourceConnector poll

---

eventmesh-admin/eventmesh-admin-rocketmq/src/test/java/org/apache/eventmesh/admin/rocketmq/util/UrlMappingPatternTest.java

Fixes #4138 .
The TO-DO mark said that "It is better using Mockito not PowerMockito", so I used Mockito. Although there are private method/field to test in the compile() method of UrlMappingPattern.
Use reflections to access private method and field, then write regular expressions.
The Test case passed.

[ISSUE #4138] Add Unit Test for UrlMappingPattern

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/retry/GrpcRetryer.java

Fixes #4198 
- Variable `retryObj` initializer `null` is redundant at line 65, removed.
- Throwing of the `InterruptedException` at line 80.

[ISSUE#4198]Do some code optimization.[GrpcRetryer]

---

eventmesh-connectors/README.md
eventmesh-runtime/conf/eventmesh.properties
eventmesh-webhook/eventmesh-webhook-admin/src/test/resources/eventmesh.properties
eventmesh-webhook/eventmesh-webhook-receive/src/test/resources/eventmesh.properties

Fixes #4185.
According to the original Chinese comments in the git commit history, the existing English comments are misleading. The English translation does not match the meaning of the original Chinese text, which affects understanding.
Correct eventmesh.properties comment grammar mistake.
```
producer:
storage: standalone
```

[ISSUE #4185] Correct eventmesh.properties comment grammar mistake

---

build.gradle
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpCommand.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpEventWrapper.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/codec/Codec.java
eventmesh-metrics-plugin/eventmesh-metrics-api/src/main/java/org/apache/eventmesh/metrics/api/model/HttpSummaryMetrics.java
eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolConstant.java
eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver/HttpRequestProtocolResolver.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/acl/Acl.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HandleMsgContext.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPClientPool.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/WebhookUtil.java
eventmesh-security-plugin/eventmesh-security-api/src/main/java/org/apache/eventmesh/api/acl/AclProperties.java
eventmesh-security-plugin/eventmesh-security-api/src/main/java/org/apache/eventmesh/api/acl/AclPropertyKeys.java
tools/dependency-check/known-dependencies.txt
tools/third-party-licenses/LICENSE

Fixes #4217，
Fixes #4218，
Fixes #4219，
Fixes #4220
- Add response status code setting for http request 
- support application/protobuf 
- Default parameter optimization and codec optimization 
- Optimize remote subscribe and unsubscribe interface 
- fix NPE, security upgrade 
- log optimization
- Authentication supports version number verification 
- Set http request timeout 
- Fix concurrent modification exception
- Fix the port occupation that caused the startup fail, and the process did not exit

[ISSUE #4217 #4218 #4219 #4220]Some bug fixes and optimization in http protocol

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/retry/EventMeshTcpRetryer.java

Fixes: https://github.com/apache/eventmesh/issues/4105.
Motivation
There are a few warnings related to fields that could have been declared final.
Modifications
1. Made fields final.
2. Removed the commented-out block.
3. At line 106 added a code block for Reinterrupting the thread.
Does this pull request to introduce a new feature? No

[ISSUE #4105] Code Optimization in EventMeshTcpRetryer

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java

Fixes #3904
Bring consistency in the declaration of constant fields
The class **Constants** in the package **org.apache.eventmesh.common** have some fields (CLOUD_EVENTS_PROTOCOL_NAME, EM_MESSAGE_PROTOCOL_NAME, OPEN_MESSAGE_PROTOCOL_NAME) that didn't had **final** modified. In this PR these fields are made final.

[ISSUE #3904] Make fields final that should be final

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/controller/ClientManageController.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/controller/HttpHandlerManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/AbstractHttpHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ConfigurationHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/EventHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/GrpcClientHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/HTTPClientHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/MetricsHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RegistryHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TCPClientHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TopicHandler.java

Fixes #4208.
Please see https://github.com/apache/eventmesh/issues/4208.
Adds JavaDoc and single-line comments for all the classes and methods included in the eventmesh-dashboard APIs.
Another doc PR for other classes of `org.apache.eventmesh.runtime.admin` package which are not included in the eventmesh-dashboard APIs will be submitted later, in order to make reviewing less difficult.

[ISSUE #4208] Add JavaDoc for org.apache.eventmesh.runtime.admin APIs of dashboard

---

eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/controller/AdminController.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/request/TopicCreateRequest.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/response/TopicResponse.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/util/RequestMapping.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/util/UrlMappingPattern.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/controller/ClientManageController.java

Fixes #4182.
Please see https://github.com/apache/eventmesh/issues/4182.
I have written these comments following the examples set by various common Java libraries. I have paid attention to formatting and ensured the correct usage of tags such as `<p>`, `<pre>`, `@see`, `@link`, `@linkplain`, `@code` and others.

[ISSUE #4182] Add JavaDoc and Comments for eventmesh-admin-rocketmq Module

---

eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManager.java

Fixes #4215.
The `transient` keyword won't make any sense in this context as it's a static field. `transient` is used to indicate that a field should not be serialized, but `static` fields are inherently not serialized anyway.

[ISSUE #4215] Correct typos and Remove redundant keyword for AdminWebHookConfigOperationManager

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/HeartbeatProcessor.java

Fixes #4194 .
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/HeartbeatProcessor.java line 95,127
use Objects.requireNonNull() to avoid NPE.
use Objects.requireNonNull() to avoid NPE.

[ISSUE #4194]Dereference of 'heartbeatItems' may produce NPE.

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/EventEmitter.java

Fixes [#4199](https://github.com/apache/eventmesh/issues/4199).
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/EventEmitter.java line 37,45,53
Use `Exception` instead of `Throwable`.
Use `Exception` instead of `Throwable`.

[ISSUE #4199] Catch Exception instead of Throwable

---

eventmesh-registry-plugin/eventmesh-registry-nacos/src/main/java/org/apache/eventmesh/registry/nacos/config/NacosRegistryConfiguration.java
eventmesh-registry-plugin/eventmesh-registry-nacos/src/main/java/org/apache/eventmesh/registry/nacos/service/NacosRegistryService.java
eventmesh-runtime/conf/eventmesh.properties

Fixes #4065.
Currently, the registry plugin Nacos only supports to config server address, userName and password.
Make registry plugin Nacos support more configuration items: `endpoint`,` accessKey`, `secretKey` and so on.

[ISSUE #4065]Make registry plugin Nacos support more configuration items

---

eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPPubClient.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java

Fix #4236 TCP reconnection failed

[ISSUE #4236] TCP reconnection failed

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/Operation.java

Fixes #4023 .
*Changed value equality to reference equality*
*Changed == to equals()*

 [Enhancement] Comparison using reference equality instead of value equality.[Operation] #4023 

---

eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/MeshMessageProtocolAdaptor.java

Fixes #4269
Replaced the if-else conditions with switch cases.
ISSUE #4269 
Replaced the if-else conditions with switch cases.
- Does this pull request introduce a new feature? 
- Ans: no
- Ans: Replaced the if-else conditions with switch cases.

[ISSUE #4269] Used switch to replace the if-else. [MeshMessageProtocolAdaptor]

---

eventmesh-storage-plugin/eventmesh-storage-mongodb/src/main/java/org/apache/eventmesh/storage/mongodb/constant/MongodbConstants.java
eventmesh-storage-plugin/eventmesh-storage-mongodb/src/main/java/org/apache/eventmesh/storage/mongodb/utils/MongodbCloudEventUtil.java

Fixes #4099.
Mentioned file in the issue has some constants that are being used in two different methods. Refactoring was needed to ensure consistency. 
Added the constants in separate file and used as import in the file of interest.
- If yes, how is the feature documented? (not applicable )
- If a feature is not applicable for documentation, explain why? (it's a refactoring)

[ISSUE #4099]Refactor re-used constant's usage from dedicated file

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/QueryWebHookConfigByIdHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/QueryWebHookConfigByManufacturerHandler.java

Fixes #4286.
The response body is not recognised as JSON in Postman, and the Content-Type header missing:
That's because `NetUtils.sendSuccessResponseHeaders(httpExchange);` is in front of `httpExchange.getResponseHeaders().add(CONTENT_TYPE, APPLICATION_JSON);` and headers are sent out before they are set correctly.

[ISSUE #4286] Fix response body is not recognised as JSON in query WebHook config endpoints

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java

Fixes #4204.
- Catch Exception instead of Throwable.
- Repeat the code extraction as a method. 
- If a feature is not applicable for documentation, explain why? **(code refactoring)**

 [ISSUE #4204] Repeat the code extraction as a method.

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/ThreadUtils.java

Fixes #4263 
Restored interrupted states in lines 37 & 54

[ISSUE #4263] InterruptedExceptions should never be ignored[ThreadUtils]

---

eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/sink/connector/OpenFunctionSinkConnector.java
eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/source/connector/OpenFunctionSourceConnector.java
eventmesh-connectors/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/sink/connector/RocketMQSinkConnector.java

Fixes #4266 .
Interrupted exception should never be ignored in the code
Restored interrupted state for interrupted exception in the mentioned files in the issue.

[ISSUE #4266]InterruptedExceptions should never be ignored[connectors]

---

eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/MessageUtils.java

Fixes #4093.
There were some duplicated logic within different methods in MessageUtils. 
Move reusable logics to separate method and make use of those methods where applicable

[ISSUE #4093]Repeat code extraction as method.[MessageUtils]

---

.github/workflows/greetings.yml
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HelloTask.java

Fixes #4260 .
To contribute in open source
Updated: ChannelFutureListener to lambda expression as its a functional Interface

[ISSUE #4260] Anonymous new ChannelFutureListener() can be replaced with lambda[HelloTask]

---

eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/service/ConsumerService.java
eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/service/ProducerService.java

Fixes #4264.
1、Make field non-public and provide accessors if needed.
2、Restore interrupted state

[ISSUE #4264][Enhancement] Some optimizations for ProducerService

---

eventmesh-sdks/eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/common/MessageUtilsTest.java

Fixes #4085 
I switched the order of the argument for the method assertEquals in the MessageUtilsTest.java

[ISSUE #4085] Switching order

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/EventMeshCloudEventUtils.java

Fixes #4262.
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/EventMeshCloudEventUtils.java
1.Extract 
```
try {
return cloudEvent.getAttributesOrThrow(ProtocolKey.ENV).getCeString();
} catch (Exception e) {
return defaultValue;
}
```
as a method private static String getValue(CloudEvent cloudEvent, String defaultValue, String protocolKey) .
2.Replace Optional.ofNullable() with 'Optional.of()' - Passing a non-null argument to 'Optional'.[366,383]
3.Remove Condition 'protoData == null' and 'binaryData == null' is always 'false'.[370,374]
4.Remove unnecessary return as the last statement in a 'void' method[416].

[ISSUE #4262] Enhancement Request EventMeshCloudEventUtils

---

eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/controller/SubController.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/service/SubService.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/service/SubService.java
eventmesh-examples/src/main/java/org/apache/eventmesh/util/Utils.java
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/CloudEventsProtocolAdaptor.java

Fixes #4346 .
fix start error and some code optimization
fix start error and some code optimization

[ISSUE 4346] Fix start error and some code optimization.

---

eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/producer/RocketMQProducerImpl.java

Fixes #4350 .
Fixed eventmesh startup error under MQ plugin.
Fixed eventmesh startup error under MQ plugin.

[ISSUE 4350] Fixed eventmesh startup error under MQ plugin.

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigService.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/HttpConvertsUtils.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/ReflectUtils.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/body/BodyTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/HeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/RandomStringUtilsTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/ReflectUtilsTest.java
eventmesh-trace-plugin/eventmesh-trace-jaeger/src/test/java/org/apache/eventmesh/trace/jaeger/JaegerTraceServiceTest.java
eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/test/java/org/apache/eventmesh/trace/pinpoint/PinpointTraceServiceTest.java
eventmesh-trace-plugin/eventmesh-trace-zipkin/src/test/java/org/apache/eventmesh/trace/zipkin/ZipkinTraceServiceTest.java

Fixes #4349.
```java
Header pushMessageRequestHeaderAsync = Header.buildHeader(String.valueOf(RequestCode.HTTP_PUSH_CLIENT_ASYNC.getRequestCode()), originalMap);
Assert.assertNotNull(pushMessageRequestHeaderAsync);
Assert.assertEquals(pushMessageRequestHeaderAsync.getClass(), PushMessageRequestHeader.class);
```
this test case code will IllegalArgumentException. I also fixed this issue
when headerParam param is Empty value object instance will cause
`java.lang.IllegalArgumentException: Can not set int field org.apache.eventmesh.common.protocol.http.header.message.PushMessageRequestHeader.code to null value`.
```java
private void setFiledValue(Header header, Map<String, Object> headerParam, ProtocolKey protocolKey,
Field[] protocolKeyFields, Field headerField,
String headerFieldName) …
```

[ISSUE #4349][Unit Test] eventmesh-common header unit test.

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/enums/ConnectionType.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/common/RequestURI.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/AsyncHttpProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/CreateTopicProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ShortHttpProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/WebHookProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/HttpResponseUtils.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/WebhookFileListener.java

Fixes #4335.
Most of the services that use `HandlerService` are affected by this bug. When sending webhook payloads using Postman and spoofing the hash value, the CloudEvent is sent successfully. However, Postman remains in a waiting state even after receiving a 200 or 500 status code. 
Webhook Delivery Error:
**In the screenshots of the webhook documentation, the tasks are also failing.** I will submit a corresponding PR to correct it later.
I choose to asynchronously close the connection in the `sendResponse()` method rather than synchronously closing it in `postHandler()` or `run()`. This is to avoid premature closure of the connection while asynchronous tasks are still in progress. As shown, this modification may occasionally cause GitHub to report an "EOF" error.
After promptly …

[ISSUE #4335] Fix Webhook connection not closing after processing

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/QueryOperationsResponse.java

[ISSUE #4025] Comparison using reference equality instead of value equality

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/AsyncSubClient.java

Fixes #4087
Please refer #4087 for details. Code optimisation done.
- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

[ISSUE #4087] Anonymous new can be replaced with lambda.[AsyncSubClient]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/RegistryResponse.java

Fixes #4027 
Changed `==` to `equals()` in lines 265 & 393

[ISSUE #4027] Comparison using reference equality instead of value equality.[RegistryResponse]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/SubscribeProcessor.java

Fixes #4195 
To solve below two issues:
1. transient is used to mark fields in a Serializable class which will not be written out to file (or stream). In a class that does not implement Serializable, this modifier is simply wasted keystrokes, and should be removed.
2. Dereference of 'subscriptionItems' may produce 'NullPointerException'
1. I have added a static keyword.
2. I have added Objects.requireNonNull() for the subscriptionItems list. 
- Does this pull request introduce a new feature?  (no)
- If a feature is not applicable for documentation, explain why? (Fixed small issue)

[ISSUE #4195] Do some code optimization.[SubscribeProcessor]

---

eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/common/SharedLatchHolder.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/WebhookFileListener.java

Fixes #4341.
When creating a new WebHookConfig, the `writeToFile` method is invoked to create a file and write data. The `fileWatchRegister` can monitor file creation, modification, and deletion. It calls the `cacheInit` method during creation and modification events to store the WebHookConfig in `cacheWebHookConfig`.
Under normal circumstances, when copying the `webhook.github.eventmesh.all` configuration file, both ENTRY_CREATE and ENTRY_MODIFY events are generated as expected:
The bug occurs when calling the `insertWebHookConfig` endpoint for the first time to create a WebHookConfig. Only the ENTRY_CREATE event is captured (abnormal; expected behavior is to have both events):
At this point, the file is empty, and the `cacheInit` method writes null to `cacheWebHookConfig`:
However, the …

[ISSUE #4341] WebHookConfig failed to load after being inserted

---

.gitignore
eventmesh-runtime/bin/start.sh
eventmesh-runtime/bin/stop.sh

Fixes #4398.
https://github.com/apache/eventmesh/issues/4299#issuecomment-1691348107
https://github.com/apache/eventmesh/issues/4398

[ISSUE #4398] Use bash to excute shell script and fix mis-output

---

eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshExtensionFactory.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/EventMeshExtensionFactoryTest.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/example/AnotherSingletonExtension.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/example/TestAnotherSingletonExtension.java
eventmesh-spi/src/test/resources/META-INF/eventmesh/org.apache.eventmesh.spi.example.TestAnotherSingletonExtension

Fixes #4129 
- *Enhance the functionality of EventMeshExtensionFactory*

[ISSUE #4129]Enhance the functionality of EventMeshExtensionFactory

---

eventmesh-runtime/build.gradle
eventmesh-runtime/conf/eventmesh.properties
eventmesh-storage-plugin/eventmesh-storage-redis/src/main/java/org/apache/eventmesh/storage/redis/admin/RedisAdmin.java
eventmesh-storage-plugin/eventmesh-storage-redis/src/main/java/org/apache/eventmesh/storage/redis/admin/RedisAdminAdaptor.java
eventmesh-storage-plugin/eventmesh-storage-redis/src/main/java/org/apache/eventmesh/storage/redis/consumer/RedisConsumer.java
eventmesh-storage-plugin/eventmesh-storage-redis/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.admin.Admin

Fixes #4403.
Fix the SPI extension admin-api loading of eventmesh-storage-redis

[ISSUE #4403] Fix redis admin spi

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncSubClient.java

Fixes #4091 .
* replace class [org.apache.eventmesh.runtime.demo.SyncSubClient] with lambda. use the correct log format.
* replace with lambda. 
* use the correct log format.

[ISSUE #4091]Anonymous new can be replaced with lambda.[SyncSubClient]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java

Make field a static final constant or non-public
Fixes #3397.
*Make field a static final constant or non-public*
*Make field a static final constant or non-public.*
- If yes, how is the feature documented? Not applicable 
- If a feature is not applicable for documentation, explain why? Not applicable

[ISSUE #3397] Make field a static final constant or non-public

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/ResetCountDownLatchTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/PropertiesUtilsTest.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/controller/ClientManageControllerTest.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/protocol/processor/WebHookProcessorTest.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/BannerUtilTest.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/EventMeshUtilTest.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/ValueComparatorTest.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/WebhookUtilTest.java
eventmesh-sdks/eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/producer/EventMeshGrpcProducerTest.java
eventmesh-sdks/eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/util/EventMeshCloudEventBuilderTest.java
eventmesh-sdks/eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/util/HttpUtilsTest.java
eventmesh-sdks/eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/common/MessageUtilsTest.java
eventmesh-security-plugin/eventmesh-security-acl/src/test/java/org/apache/eventmesh/acl/impl/AclServiceImplTest.java
eventmesh-security-plugin/eventmesh-security-api/src/test/java/org/apache/eventmesh/api/acl/AclServiceTest.java
eventmesh-security-plugin/eventmesh-security-api/src/test/java/org/apache/eventmesh/api/auth/AuthServiceTest.java
eventmesh-security-plugin/eventmesh-security-api/src/test/java/org/apache/eventmesh/api/exception/AclExceptionTest.java
eventmesh-security-plugin/eventmesh-security-auth-http-basic/src/test/java/org/apache/eventmesh/auth/http/basic/impl/AuthHttpBasicServiceTest.java
eventmesh-spi/src/test/java/org/apache/eventmesh/spi/EventMeshExtensionFactoryTest.java
eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/test/java/org/apache/eventmesh/storage/rocketmq/producer/ProducerImplTest.java
eventmesh-webhook/eventmesh-webhook-admin/src/test/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperationTest.java

Fixes #4483.
Following 750825158253d4004e023cfb8ab515c39bc20a71 (#4475), the upgrade to JUnit Jupiter allows us to standardize the way exceptions are handled in tests and reduce boilerplate code.
- There is no need to catch an exception and explicitly fail the test. The test should be allowed to throw the exception and error-out, which is technically the correct behavior (the test didn't really fail on any logic test).
- In the cases where the only assertion was explicitly failing the test in case an exception was thrown, `Assertions.assertDoesNotThrow` was used instead.
- In order to test cases when an exception must be thrown, `Assertions.assertThrows` can be used. There is no need to catch the exception and assert it's not null.
- It's also worth noting that some instances that used …

[ISSUE #4483] Standardize exception handling in tests

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/ConfigurationContextUtil.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/ConfigurationContextUtilTest.java
eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/client/CloudEventsPublishInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/GrpcAbstractDemo.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/HttpAbstractDemo.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java
eventmesh-meta/eventmesh-meta-consul/src/test/java/org/apache/eventmesh/meta/consul/service/ConsulMetaServiceTest.java
eventmesh-meta/eventmesh-meta-etcd/src/test/java/org/apache/eventmesh/registry/etcd/service/EtcdMetaServiceTest.java
eventmesh-meta/eventmesh-meta-nacos/src/test/java/org/apache/eventmesh/registry/nacos/service/NacosMetaServiceTest.java
eventmesh-meta/eventmesh-meta-zookeeper/src/test/java/org/apache/eventmesh/registry/zookeeper/service/ZookeeperMetaServiceTest.java
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusGrpcExporter.java
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusHttpExporter.java
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusTcpExporter.java
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/utils/PrometheusExporterConstants.java
eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcBootstrap.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHttpBootstrap.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTcpBootstrap.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/ProtocolConstant.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/CloudEventProducer.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/EventMeshCommon.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/MessageUtils.java

There were duplicate final static constants that could have been created in a single common file and could be reused anywhere in the project.
The common file which is suitable for hosting the static constants was found to be inside the package -> package org.apache.eventmesh.common. The file is the Constants.java file. There I added the following String constants ->
{  HTTP = "HTTP",  TCP = "TCP", GRPC = "GRPC"}
Other than this there is one more constant in the eventmesh-common.Constants file called ( CLOUD_EVENTS_PROTOCOL_NAME = "cloudevents" ) which I have added wherever applicable.
and changed the import statements accordingly.
- If a feature is not applicable for documentation, …

[ISSUE #4474] Uniformly manage duplicate static variables

---

build.gradle
eventmesh-connectors/eventmesh-connector-prometheus/build.gradle
eventmesh-connectors/eventmesh-connector-prometheus/gradle.properties
eventmesh-connectors/eventmesh-connector-prometheus/src/main/java/org/apache/eventmesh/connector/prometheus/config/PrometheusServerConfig.java
eventmesh-connectors/eventmesh-connector-prometheus/src/main/java/org/apache/eventmesh/connector/prometheus/model/QueryPrometheusReq.java
eventmesh-connectors/eventmesh-connector-prometheus/src/main/java/org/apache/eventmesh/connector/prometheus/model/QueryPrometheusRsp.java
eventmesh-connectors/eventmesh-connector-prometheus/src/main/java/org/apache/eventmesh/connector/prometheus/model/ResponseData.java
eventmesh-connectors/eventmesh-connector-prometheus/src/main/java/org/apache/eventmesh/connector/prometheus/server/PrometheusConnectServer.java
eventmesh-connectors/eventmesh-connector-prometheus/src/main/java/org/apache/eventmesh/connector/prometheus/source/config/PrometheusSourceConfig.java
eventmesh-connectors/eventmesh-connector-prometheus/src/main/java/org/apache/eventmesh/connector/prometheus/source/config/SourceConnectorConfig.java
eventmesh-connectors/eventmesh-connector-prometheus/src/main/java/org/apache/eventmesh/connector/prometheus/source/connector/PrometheusSourceConnector.java
eventmesh-connectors/eventmesh-connector-prometheus/src/main/resources/server-config.yml
eventmesh-connectors/eventmesh-connector-prometheus/src/main/resources/source-config.yml
settings.gradle
tools/dependency-check/known-dependencies.txt

Fixes #4415.
*Add Promethus source connector.*
*Add new source connector module for prometheus*

[ISSUE #4415] Add Promethus source connector

---

eventmesh-protocol-plugin/eventmesh-protocol-api/src/test/java/org/apache/eventmesh/protocol/api/MockProtocolAdaptorImpl.java
eventmesh-protocol-plugin/eventmesh-protocol-api/src/test/java/org/apache/eventmesh/protocol/api/ProtocolPluginFactoryTest.java
eventmesh-protocol-plugin/eventmesh-protocol-api/src/test/resources/META-INF/eventmesh/org.apache.eventmesh.protocol.api.ProtocolAdaptor

Fixes #4515 
Add test case for ProtocolPluginFactory.

[ISSUE#4515] Add test case for ProtocolPluginFactory.

---

eventmesh-admin/src/main/java/org/apache/eventmesh/admin/config/AdminProperties.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/config/MetaTypeConfig.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/constant/ConfigConst.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/constant/NacosConst.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/dto/Result.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/enums/Errors.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/enums/Status.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/exception/BaseException.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/exception/EventMeshAdminException.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/exception/GlobalExceptionHandler.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/exception/MetaException.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/service/impl/NacosSubscriptionService.java
eventmesh-admin/src/main/java/org/apache/eventmesh/admin/util/ExceptionUtil.java

Fixes #4521.
The `Message` subclass represents the string message for exceptions; however, its concept may potentially conflict with MQ messages. To address this concern, the class name has been changed while retaining the field name.
`Type` refers to a kind or category, where its constituents share similar characteristics. It can pertain to a single exception or multiple exceptions of the same type, which might lead to potential ambiguity. Therefore, its class name has been exacted to the primary classification level `Category`.
The `Errors` enum has been renamed to `Status` to accommodate additional situations, such as the status of a K8s pod being `Deploying`.
The names of exception enum members have been optimized to better align with their usage in the code, adhere more closely to …

[ISSUE #4521] A poor naming.

---

eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/model/TopicMetadata.java

[ISSUE #3825] Do some code optimization.[TopicMetadata]

---

eventmesh-sdks/eventmesh-sdk-rust/Cargo.toml
eventmesh-sdks/eventmesh-sdk-rust/examples/grpc/producer_example.rs
eventmesh-sdks/eventmesh-sdk-rust/rust-toolchain.toml
eventmesh-sdks/eventmesh-sdk-rust/src/common.rs
eventmesh-sdks/eventmesh-sdk-rust/src/common/grpc_eventmesh_message_utils.rs
eventmesh-sdks/eventmesh-sdk-rust/src/common/protocol_key.rs
eventmesh-sdks/eventmesh-sdk-rust/src/grpc/grpc_consumer.rs
eventmesh-sdks/eventmesh-sdk-rust/src/grpc/grpc_producer.rs
eventmesh-sdks/eventmesh-sdk-rust/src/grpc/impl.rs
eventmesh-sdks/eventmesh-sdk-rust/src/grpc/impl/grpc_producer_impl.rs
eventmesh-sdks/eventmesh-sdk-rust/src/lib.rs
eventmesh-sdks/eventmesh-sdk-rust/src/model.rs
eventmesh-sdks/eventmesh-sdk-rust/src/model/event_clouds.rs
eventmesh-sdks/eventmesh-sdk-rust/src/model/message.rs
eventmesh-sdks/eventmesh-sdk-rust/tests/eventmesh_message_utils_test.rs

Fixes #4519 
- Rust sdk support CloudEvents
- Rust sdk grpc producer support CloudEvents
- Optimize some code
- Rename some rust source file name
How to use see producer_example.rs, Run result
```
2023-10-30T09:25:46.464595Z  INFO main ThreadId(01) producer_example: 71: Publish Message to EventMesh........ …
```

[ISSUE #4519]Rust sdk support CloudEvents

---

eventmesh-connectors/eventmesh-connector-rocketmq/build.gradle
eventmesh-connectors/eventmesh-connector-rocketmq/src/test/java/org/apache/eventmesh/connector/rocketmq/sink/connector/RocketMQSinkConnectorTest.java
eventmesh-connectors/eventmesh-connector-rocketmq/src/test/resources/sink-config.yml

Fixes #4536 .
Add unit test for RocketMQSinkConnector.

[ISSUE#4536] Add unit test for RocketMQSinkConnector.

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPMessageHandler.java

Fixes #4549 .
Remove unnecessary transient modifier, was located at file `HTTPMessageHandler.class`, line 49, 54.

[ISSUE#4549] Remove unnecessary transient modifiers. [HTTPMessageHandler]

---

eventmesh-connectors/eventmesh-connector-rocketmq/src/test/java/org/apache/eventmesh/connector/rocketmq/source/connector/RocketMQSourceConnectorTest.java
eventmesh-connectors/eventmesh-connector-rocketmq/src/test/resources/source-config.yml

Fixes #4535 .
Add unit test for RocketMQSourceConnector.

[ISSUE#4535] Add unit test for RocketMQSourceConnector.

---

.github/workflows/ci.yml
eventmesh-transformer/src/test/java/org/apache/eventmesh/transformer/TransformTest.java

[MINOR] Fix ci check error

---

.github/workflows/build.yaml

Fixes #913.
*Currently, the workflow only pushed to eventmesh repo on dockerhub*
*We need the docker image to be pushed under apache repo as well*
*Added the tag for pushing to apache repo on dockerhub*

[ISSUE #913] Push docker image to apache repo

---

eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/util/CloudEventUtil.java

…nnectRecord  to CloudEvent throw NPE
Fixes #4596 
- Fix SourceWorker#convertRecordToEvent method converts ConnectRecord  to CloudEvent throw NPE
- Fix SourceWorker#convertRecordToEvent method converts ConnectRecord  to CloudEvent throw NPE

[ISSUE #4596]Fix SourceWorker#convertRecordToEvent method converts ConnectRecord  to CloudEvent throw NPE

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/ProtocolKey.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/SubscriptionReply.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ConsumerService.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/SubStreamHandler.java

Fixes #4619 
-Fix Grpc request reply can not revice reply message
- Fix Grpc request reply can not revice reply message

[ISSUE #4619]Fix Grpc request reply can not revice reply message

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/BroadCastSubClient.java

Issue Fix: #4088 
Replaced the anonymous inner class with a lambda expression for the handle method

[ISSUE #4088] Anonymous new can be replaced with lambda.[BroadCastSubClient]

---

eventmesh-connectors/README.md
eventmesh-connectors/eventmesh-connector-wechat/src/main/java/org/apache/eventmesh/connector/wechat/sink/connector/TemplateMessageResponse.java
eventmesh-connectors/eventmesh-connector-wechat/src/main/java/org/apache/eventmesh/connector/wechat/sink/connector/WeChatSinkConnector.java
eventmesh-connectors/eventmesh-connector-wechat/src/test/java/org/apache/eventmesh/connector/wechat/sink/connector/WeChatSinkConnectorTest.java

Fixes #4602.
fix bug when wecaht api response fail
rename org.apache.eventmesh.connector.wechat.sink.connector.TemplateMessageResponse#errocode
to org.apache.eventmesh.connector.wechat.sink.connector.TemplateMessageResponse#errcode
add abnormal test case

[ISSUE #4602] when wechat send message api response errcode is not zero, the wechat sink connector does not throw IllegalAccessException

---

eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumer.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/SubStreamHandler.java

Fixes #4643 
- Fix Grpc client can't reconnection when runtime after crashing the runtime and restarting it

[ISSUE #4643]Fix Grpc client can't reconnection when runtime after crashing the runtime and restarting it

---

eventmesh-connectors/eventmesh-connector-dingtalk/README.md
eventmesh-connectors/eventmesh-connector-dingtalk/README_CN.md
eventmesh-connectors/eventmesh-connector-dingtalk/src/main/resources/sink-config.yml

Fix #4658 
Add documentation for dingtalk sink connector.

[ISSUE #4658] Add documentation for dingtalk sink connector.

---

eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/connector/HttpSourceConnector.java

Fixes #4659.
see #4659 
- Check arrtibutes `subject`, `datacontenttype` & `data` before saving a cloudevent. Since they are required in `connectRecord` but optional in cloudevents.
- Use default status message in failure response.
- Does this pull request introduce a new feature?no

[ISSUE #4659] Fix HTTP source connector stop after receiving an invalid request

---

.github/workflows/ci.yml
settings.gradle

Closes #4688.
This PR publishes a build scan for every CI build on GitHub Actions and for every local build from an authenticated Apache committer. The build will not fail if publishing fails.
The build scans of the Apache EventMesh project will be published to the Develocity instance at [ge.apache.org](https://ge.apache.org/), hosted by the Apache Software Foundation and run in partnership between the ASF and Gradle. This Develocity instance has all features and extensions enabled and is freely available for use by the Apache EventMesh project and all other Apache projects. Currently, this is being used by other ASF projects such as [Beam](https://ge.apache.org/scans?search.rootProjectNames=beam&search.timeZoneId=America%2FChicago), …

[ISSUE #4688] Capture build scans on ge.apache.org to benefit from deep build insights

---

build.gradle
eventmesh-common/src/test/java/org/apache/eventmesh/common/file/WatchFileManagerTest.java
gradle.properties

Fixes #1054.
The motivation of this PR is to improve the build time by resolving caching issues.
- build cache was not enabled.
- spotlessApply runs on every build, modifying source code and causing cache misses.
- spotless target included build directory, causing cache misses due to changing inputs.
- WatchFileManagerTest edits a properties file in place causing a cache miss in subsequent tasks.
- Enabled gradle build cache by setting org.gradle.caching = true in the gradle.properties file.
- Removed checkstyleMain dependency on spotlessApply (should run spotlessApply as a separate task or integrate into CI).
- Limited the target of spotlessJava to only the src java files.
- Copied configuration.properties into a TempDir for testing the onChange method.
These changes improved the build …

[ISSUE #1054] Build caching optimizations

---

eventmesh-meta/eventmesh-meta-nacos/src/main/java/org/apache/eventmesh/meta/nacos/service/NacosMetaService.java

[ISSUE #4723] Fix get meta from nacos return 403

---

.github/workflows/ci.yml

Fixes #4721.
This is a follow on effort to the change in https://github.com/apache/eventmesh/pull/4685. This change will both show build scan links on GitHub Actions workflows and replace custom caching logic in the CI workflow.
- Add [gradle-build-action](https://github.com/gradle/gradle-build-action) to the CI GitHub Actions workflow.

[ISSUE #4721] Use gradle-build-action for caching and build scan link promotion

---

.github/workflows/ci.yml
build.gradle
docker/Dockerfile_jdk11
docker/Dockerfile_jdk8

Fixes #4705.
When writing this PR https://github.com/apache/eventmesh-site/pull/170, I noticed this build task.
Gradle build task `jar` is already depended by `dist` and included in `build`, so there is no need to excute it.
Remove task `jar` from compilation commands.

[ISSUE #4705] Remove redundant Gradle build task 'jar'

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/codec/Codec.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/tcp/codec/CodecTest.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractTCPServer.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java

Fixes #4701 
- use tcp protocol client send message, it throw a DecoderException
- Refactored the Codec's code and fixed the current issue

[ISSUE #4701]Fix use tcp protocol client send message, it throw a DecoderException

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/file/WatchFileTask.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/file/WatchFileManagerTest.java

Fixes https://github.com/apache/eventmesh/issues/4711
The `@TempDir` added in the [Build caching optimizations PR](https://github.com/apache/eventmesh/pull/4689) caused tests to fail when run on a Windows machine. The failure was due to the fact that the directory could not be deleted because it was in use by other processes.
The resources holding on to the temporary config file that were preventing the temp directory from being deleted are now properly closed.
- If yes, how is the feature documented?

[ISSUE #4711] Properly close resources used by WatchFileManagerTest

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshConstants.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/HeartbeatProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/ReplyMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/SubscribeStreamProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/CreateTopicProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/DeleteTopicProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/QuerySubscriptionProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/tcp/EventMeshTcpMonitor.java

Fixes #4734 
In Java, it is a best practice to declare a logger static final.
private - so that no other class can hijack your logger
static - so there is only one logger instance per class, also avoiding attempts to serialize loggers
final - no need to change the logger over the lifetime of the class
For all `private final Logger` declarations a `static` modifier has been added and the UPPER_CASE has been applied.
Logger names has been substituted with constants from `org.apache.eventmesh.runtime.constants.EventMeshConstants`, in particular 3 new constants have been added to it.
- If a feature is not applicable for documentation, explain why? (minor refactoring)
- If a feature …

[ISSUE #4734] Use the static final modifier to decorate Logger

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/docker.yaml
settings.gradle

Fixes #4737.
The motivation for this PR is to fix an issue where CodeQL is not able to analyze a PR when the Gradle build cache prevents all Java compilation. CodeQL requires the compiler to execute during the workflow in order to perform its analysis, as documented [here](https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/no-source-code-seen-during-build).
This pull request moves the CodeQL verification to its own workflow, independent of the "Continuous Integration" workflow, where Gradle build caching is disabled. This not only addresses the issue, but should also have some improvements to the workflows:
* By moving CodeQL to its own workflow, it can execute in parallel. This removes CodeQL analysis from the critical path of a full build and lets the …

[ISSUE #4737] Separate codeql workflow

---

README.md
README.zh-CN.md

Fixes #4710.
Rewrite the quick start guide for the home page.
Add the operator's quick start step.
Rewrite the quick start guide for the home page.
Add the operator's quick start step.

[ISSUE #4710] Rewrite the quick start guide for the home page.

---

eventmesh-meta/eventmesh-meta-etcd/src/main/java/org/apache/eventmesh/meta/etcd/service/EtcdCustomService.java

Fixes #4095 .
Code Optimization and Interrupeted Exception handling in EtcdCustomService.class

[ISSUE #4095] Code Optimization and Interrupeted Exception handling.[EtcdCustomService]

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/ThreadWrapperTest.java
eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/PubClientImpl.java

Fixes #4733 .
Substitute e.printStackTrace() with log.error()

[ISSUE #4733] Substitute e.printStackTrace() with log.error()

---

eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/WebhookFileListener.java

Fixes #3822 .
The throwing of the InterruptedException clears the interrupted state of the Thread, so if the exception is not handled properly the information that the thread was interrupted will be lost. Instead, InterruptedExceptions should either be rethrown - immediately or after cleaning up the method’s state - or the thread should be re-interrupted by calling Thread.interrupt().

[ISSUE #3822]Enhance thread handling of InterruptedException

---

eventmesh-sdks/eventmesh-sdk-rust/src/grpc/grpc_consumer.rs

Fixes #4633 .
*Optimized the message body of the Rusk SDK's returned reply message*

[ISSUE #4633] Optimize the message body of the Rust SDK's returned reply message

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/HeartbeatRequestBody.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/consumer/EventMeshHttpConsumer.java

Fixes #3903
I am currently new to open source contributing and would like to gain experience solving issues and navigating git in order to become a better contributor.
-Added appropriate getters and setters for HeartbeatEntity class in HeartbeatRequestBody.java. 
-Updated EventMeshHttpConsumer.java to access aforementioned variables using correct setters. 
-Updated HeartbeatProcessor.java to access aforementioned variables using correct getters.
At eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/HeartbeatRequestBody.java line 70-75
At eventmesh-sdk
java/src/main/java/org/apache/eventmesh/client/http/consumer/EventMeshHttpConsumer.java line 120,121
At eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProce …

[ISSUE #3903] Unwritten public or protected field [HeartbeatRequestBody]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/MetaHandler.java

Fixes #3010.
*This change implements try-with-resources feature for get() method in MetaHandler class.*
*The try-with-resources statement ensures that each resource is closed at the end of the statement.*
*Rewrite get() method to use try-with-resource statement, remove finally block.*

[ISSUE #3010] Method manually handles closing an auto-closeable resource [MetaHandler]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/AbstractHttpRequestProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/AdminMetricsProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/AdminShutdownProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/CreateTopicProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/DeleteTopicProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HttpProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/QuerySubscriptionProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ShortHttpProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/WebHookProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/HttpRequestProcessor.java

[ISSUE #4731] HttpRequestProcessor enhancement

---

eventmesh-meta/eventmesh-meta-zookeeper/src/main/java/org/apache/eventmesh/meta/zookeeper/service/ZookeeperMetaService.java

Fixes #3833 
a. Change to private modifier.
b. Repeat code extraction as method.
make public to pravite
Extract public methods

[ISSUE #3833] optimization ZookeeperMetaService

---

eventmesh-storage-plugin/eventmesh-storage-standalone/src/test/java/org/apache/eventmesh/storage/standalone/TestUtils.java
eventmesh-storage-plugin/eventmesh-storage-standalone/src/test/java/org/apache/eventmesh/storage/standalone/admin/StandaloneAdminTest.java

Fixes #3828
Optimize code in the following classes : StandaloneAdminTest and TestUtils
Remove duplication
Use native Boolean.TRUE and Boolean.FALSE instead of variable with value true and false
Use Collections.singletonList for creating List
- If a feature is not applicable for documentation, explain why? Optimization in tests

[ISSUE #3828] Code optimization for StandaloneAdminTest and TestUtils

---

eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/model/MessageEntity.java

Fixes https://github.com/apache/eventmesh/issues/3824
Motivation
add serialVersionUID and transient message
Modifications
Documentation
Does this pull request introduce a new feature? no

[ISSUE #3824] code optimization for MessageEntity

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/MetricsHandler.java

Fixes #3009 
try-resources for `httpExchange.getResponseBody()` and `PrintWriter` (on catch).
- If a feature is not applicable for documentation, explain why? (bug fix)
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation (not applicable)

[ISSUE #3009] change MetricsHandler#get to try-resources

---

eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/producer/ProducerImpl.java

Fixes https://github.com/apache/eventmesh/issues/3830
Motivation
Add catch InterruptedException and ThreadDeath exceptions in the code.  
Modifications
Documentation

[ISSUE #3830] InterruptedExceptions should not be ignored in the code.

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/Header.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/codec/Codec.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/IPUtils.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/ThreadUtils.java
eventmesh-connectors/eventmesh-connector-dingtalk/src/main/java/org/apache/eventmesh/connector/dingtalk/sink/connector/DingDingSinkConnector.java
eventmesh-connectors/eventmesh-connector-jdbc/src/main/java/org/apache/eventmesh/connector/jdbc/dialect/mysql/MysqlDatabaseDialect.java
eventmesh-connectors/eventmesh-connector-jdbc/src/main/java/org/apache/eventmesh/connector/jdbc/source/SourceJdbcTaskManager.java
eventmesh-connectors/eventmesh-connector-jdbc/src/main/java/org/apache/eventmesh/connector/jdbc/source/dialect/cdc/mysql/MysqlCdcEngine.java
eventmesh-connectors/eventmesh-connector-jdbc/src/main/java/org/apache/eventmesh/connector/jdbc/source/dialect/mysql/MysqlDataTypeConvertor.java
eventmesh-connectors/eventmesh-connector-jdbc/src/main/java/org/apache/eventmesh/connector/jdbc/source/dialect/snapshot/mysql/MysqlSnapshotEngine.java
eventmesh-connectors/eventmesh-connector-jdbc/src/main/java/org/apache/eventmesh/connector/jdbc/table/catalog/mysql/MysqlDefaultValueConvertorImpl.java
eventmesh-connectors/eventmesh-connector-lark/src/main/java/org/apache/eventmesh/connector/lark/sink/ImServiceHandler.java
eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/EventMeshListenerBeanPostProcessor.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/cloudevents/SyncRequest.java
eventmesh-meta/eventmesh-meta-etcd/src/main/java/org/apache/eventmesh/meta/etcd/service/EtcdMetaService.java
eventmesh-meta/eventmesh-meta-nacos/src/main/java/org/apache/eventmesh/meta/nacos/service/NacosMetaService.java
eventmesh-meta/eventmesh-meta-zookeeper/src/main/java/org/apache/eventmesh/meta/zookeeper/service/ZookeeperMetaService.java
eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-nacos/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/nacos/NacosConfigService.java
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcEventMeshCloudEventProtocolResolver.java
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/grpc/GrpcEventMeshCloudEventProtocolResolver.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/HttpTinyClient.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/Codec.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/EventMeshMessageProducer.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/util/EventMeshCloudEventBuilder.java
eventmesh-security-plugin/eventmesh-security-auth-token/src/main/java/org/apache/eventmesh/auth/token/impl/auth/AuthTokenUtils.java
eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/consumer/PushConsumerImpl.java
eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java

Fixes #4808
The usage of `null == object` is a legacy convention from the C language era. In Java, this syntax is not supported by any specifications (see the discussion below). Therefore, it is better to standardize it as `object == null`.
- [java - object==null or null==object? - Stack Overflow](https://stackoverflow.com/questions/2369226/object-null-or-null-object)
- [java - (obj == null) vs (null == obj)? - Stack Overflow](https://stackoverflow.com/questions/6883646/obj-null-vs-null-obj)
- [java - Difference between 'a == null' and 'null == a' - Stack Overflow](https://stackoverflow.com/questions/28594183/difference-between-a-null-and-null-a)
As discussed, in Java, erroneous assignments such as `object = null` do not occur.
If a developer is prone to mistaking `object != null` for …

[ISSUE #4808] Unify all `null == object` usage to standard `object == null`

---

eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/EventMeshMessageProducer.java

Fixes #4805
Please see https://github.com/apache/eventmesh/issues/4805.
Add a new `throws new EventMeshException` statement in the catch block, just like the `org.apache.eventmesh.client.http.AbstractProducerHttpClient#publish` and the `org.apache.eventmesh.client.tcp.impl.eventmeshmessage.EventMeshMessageTCPPubClient#publish` did.
In `eventmesh-sdk-java`, this exception is not handled by the caller of the `publish(EventMeshMessage message)` method. If the exception is rethrown, the user must catch this exception manually.
- If a feature is not documented yet in this PR, please …

[ISSUE #4805] Rethrow exception in gRPC SDK when publish error occurs

---

.github/workflows/stale.yml

Fixes #4810
https://github.com/apache/eventmesh/actions/runs/8548456034
Correct keyword and adjust time to 2:30 UTC+8.

[ISSUE #4810] Fix stale workflow failure and adjust cron with UTC time

---

build.gradle
eventmesh-connectors/eventmesh-connector-prometheus/build.gradle
eventmesh-connectors/eventmesh-connector-prometheus/src/main/java/org/apache/eventmesh/connector/prometheus/source/connector/PrometheusSourceConnector.java
eventmesh-connectors/eventmesh-connector-wechat/build.gradle
eventmesh-connectors/eventmesh-connector-wechat/src/main/java/org/apache/eventmesh/connector/wechat/sink/connector/WeChatSinkConnector.java
eventmesh-runtime/build.gradle
tools/dependency-check/known-dependencies.txt
tools/third-party-licenses/LICENSE

[Enhancement] Migrate from fastjson 1.2.83 to fastjson2 [#4814](https://github.com/apache/eventmesh/issues/4814)
remove the `fastjson:1.2.83` and add the `fastjson2:2.0.48`

[ISSUE #4814] Migrate from fastjson 1.2.83 to fastjson2

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java

Fixes #4551 
[Enhancement] The logical operations in prehandler and posthandler are not reasonable #4551
Create a wrapper method named `postHandlerWithTimeCostRecord` for `postHandler()`, encapsulating the original `preHandler()` logic, and then invoking the `postHandler()` method.

[ISSUE #4551] The logical operations in prehandler and posthandler are not reasonable

---

eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java
eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java

Fixes #4855 
fix tcp client close failed.
The session should be deleted first, then the channel should be closed, and the order should be adjusted.

[ISSUE #4855] Fix close tcp client failed

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/JsonUtils.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/AbstractHttpHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/AdminHandlerManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/v2/ConfigurationHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/response/v2/GetConfigurationResponse.java

Fixes #4834
Since `EventMeshTCPConfiguration`, `EventMeshHTTPConfiguration` and `EventMeshGrpcConfiguration` are subclasses of `CommonConfiguration`, their serialized JsonString would contain superclass fields, which enlarges the response body and brings in difficulty in getting `CommonConfiguration` fields.
- Add a PropertyFilter to remove superclass fields from the JsonString of `EventMeshTCPConfiguration`, `EventMeshHTTPConfiguration` and `EventMeshGrpcConfiguration`, then add `CommonConfiguration` into the response body.
- Add `configs` param which accepts two values, `exclusive` and `all`.
- Add unified exception handling
- The actual version number will be returned after merging https://github.com/apache/eventmesh/pull/4055.
- …

[ISSUE #4834] Add protocol exclusive fields filter for `/v2/configuration` endpoint

---

eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/MessageUtils.java

Fixes #3095
[Enhancement] Method invocation may produce `NullPointerException`[MessageUtils] #3095
Explicitly handle exceptions using `Objects.requireNonNull()`

[ISSUE #3095] Handling possible NullPointerException[MessageUtils]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java

Fixes #3411
[Enhancement] Do some code optimization[ReplyMessageProcessor]

[ISSUE #3411] Do some code optimization[ReplyMessageProcessor]

---

build.gradle
eventmesh-admin-server/bin/start-admin.sh
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/db/entity/EventMeshJobDetail.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/service/position/EventMeshPositionBizService.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/service/position/IFetchPositionHandler.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/service/position/impl/MysqlPositionHandler.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/connector/rdb/canal/CanalSinkConfig.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/connector/rdb/canal/CanalSourceConfig.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/remote/response/FetchJobResponse.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/remote/response/FetchPositionResponse.java
eventmesh-connectors/eventmesh-connector-canal/build.gradle
eventmesh-connectors/eventmesh-connector-canal/src/main/java/org/apache/eventmesh/connector/canal/dialect/MysqlDialect.java
eventmesh-connectors/eventmesh-connector-canal/src/main/java/org/apache/eventmesh/connector/canal/interceptor/SqlBuilderLoadInterceptor.java
eventmesh-connectors/eventmesh-connector-canal/src/main/java/org/apache/eventmesh/connector/canal/source/EntryParser.java
eventmesh-connectors/eventmesh-connector-canal/src/main/java/org/apache/eventmesh/connector/canal/source/connector/CanalSourceConnector.java
eventmesh-connectors/eventmesh-connector-canal/src/main/java/org/apache/eventmesh/connector/canal/template/AbstractSqlTemplate.java
eventmesh-connectors/eventmesh-connector-canal/src/main/java/org/apache/eventmesh/connector/canal/template/MysqlSqlTemplate.java
eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/connector/SourceConnectorContext.java
eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-admin/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/admin/AdminOffsetService.java
eventmesh-registry/eventmesh-registry-nacos/gradle.properties
eventmesh-runtime-v2/bin/start-v2.sh
eventmesh-runtime-v2/bin/stop-v2.sh
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/boot/RuntimeInstance.java
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/connector/ConnectorRuntime.java

[ISSUE #4979] Canal Connector supports bidirectional data synchronization

---

eventmesh-connectors/eventmesh-connector-http/build.gradle
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/handle/CommonHttpSinkHandler.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/handle/WebhookHttpSinkHandler.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/connector/HttpSourceConnector.java
eventmesh-connectors/eventmesh-connector-http/src/test/java/org/apache/eventmesh/connector/http/source/connector/HttpSinkConnectorTest.java
eventmesh-connectors/eventmesh-connector-http/src/test/java/org/apache/eventmesh/connector/http/source/connector/HttpSourceConnectorTest.java

Fixes #5020
Optimize unit tests and code <HTTP Connector>

[ISSUE #5020] Optimize unit tests and code <HTTP Connector>

---

build.gradle
eventmesh-trace-plugin/eventmesh-trace-pinpoint/build.gradle
eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/exporter/PinpointSpanExporter.java
eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/test/java/org/apache/eventmesh/trace/pinpoint/exporter/PinpointSpanExporterTest.java

Fixes #4963
Upgrading version of the Pinpoint libraries to the latest version (some deprecated functionality had been removed in the 3.0.0 release so updates were necessary.
- Updated the libraries to 3.0.0 version of the pinpoint-profiler libraries in support of the associated trace plugin.
- Added case to unit test to validate that parent span information was passed correctly.
- If yes, how is the feature documented? NA
- If a feature is not applicable for documentation, explain why? Library upgrade, no docs required.

[ISSUE #4963] Updating version of pinpoint libraries to 3.0.0

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/HttpRequestUtilTest.java

Fixes #4994 
Added new tests for HttpRequestUtil.java located at [eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util]

[ISSUE #4994] unit tests for HttpRequestUtil.java

---

eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/server/HttpConnectServer.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/HttpSinkConnector.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/HttpSourceConnector.java
eventmesh-connectors/eventmesh-connector-http/src/test/java/org/apache/eventmesh/connector/http/sink/HttpSinkConnectorTest.java
eventmesh-connectors/eventmesh-connector-http/src/test/java/org/apache/eventmesh/connector/http/source/HttpSourceConnectorTest.java

Fixes #5031
Http Connector Adaptation Work
Implement the ConnectorCreateService interface in the HTTP connector to make it compatible with the v2 architecture.

[ISSUE #5031] Http Connector Adaptation Work

---

build.gradle
eventmesh-admin-server/build.gradle
eventmesh-connectors/eventmesh-connector-canal/build.gradle

Fixes #5042
Please see https://github.com/apache/eventmesh/pull/5038#discussion_r1687979992
Add a new `deniedLicense` and change `implementation` namespace to `compileOnly`.

[ISSUE #5042] Exclude `mysql-connector-j` from classpath

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/TraceUtilsTest.java

Fixes https://github.com/apache/eventmesh/issues/4995
Motivation
Modifications
Added new tests for TraceUtils.java located at [eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util]
Documentation
If yes, how is the feature documented? (not applicable)

[ISSUE #4995] unit tests for TraceUtils.java

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/connector/http/SourceConnectorConfig.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/handle/CommonHttpSinkHandler.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/HttpSourceConnector.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/protocol/impl/CommonProtocol.java

[ISSUE #5069] Enhancement for http source/sink connector

---

eventmesh-admin-server/conf/eventmesh.sql
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/HttpServer.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/Response.java

[ISSUE #5073] Fix eventmesh-admin-server createTask response error

---

eventmesh-admin-server/bin/start-admin.sh
eventmesh-admin-server/build.gradle
eventmesh-admin-server/conf/application.yaml
eventmesh-admin-server/conf/eventmesh.sql
eventmesh-admin-server/conf/mapper/EventMeshVerifyMapper.xml
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/HttpServer.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/db/DBThreadPool.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/db/entity/EventMeshVerify.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/handler/impl/FetchJobRequestHandler.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/handler/impl/ReportJobRequestHandler.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/handler/impl/ReportPositionHandler.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/handler/impl/ReportVerifyHandler.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/service/job/JobInfoBizService.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/service/position/impl/HttpPositionHandler.java
eventmesh-admin-server/src/main/java/org/apache/eventmesh/admin/server/web/service/verify/VerifyBizService.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/remote/JobState.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/remote/TransportType.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/remote/request/ReportJobRequest.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/remote/request/ReportVerifyRequest.java
eventmesh-common/src/main/resources/META-INF/services/org.apache.eventmesh.common.remote.payload.IPayload
eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-admin/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/admin/AdminOffsetService.java

[ISSUE #5079] Enhancement update for admin-server

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/ThreadUtilsTest.java

Fixes https://github.com/apache/eventmesh/issues/4540
Motivation
Modifications
Added new tests for ThreadUtils.java located  https://github.com/apache/eventmesh/blob/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/ThreadUtils.java
Documentation
If yes, how is the feature documented? (not applicable)

[ISSUE #4540] Add unit test for ThreadUtils

---

build.gradle
eventmesh-common/src/main/java/org/apache/eventmesh/common/stubs/HeaderStub.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/HttpConvertsUtilsTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/ThreadUtilsTest.java
eventmesh-connectors/eventmesh-connector-rabbitmq/build.gradle
eventmesh-storage-plugin/eventmesh-storage-rabbitmq/build.gradle
settings.gradle

Fixes #4990 
`HttpConvertsUtils.java` at `eventmesh-common/src/test/java/org/apache/eventmesh/common/utils` do not have its unit test, and the test coverage needs to be expanded.
Added `HttpConvertsUtilsTest.java` located at `eventmesh-runtime/src/test/java/org/apache/eventmesh/common/util`
- Does this pull request introduce a new feature?   no
- If yes, how is the feature documented?   not applicable

[ISSUE #4990] Add unit test for HttpConvertsUtils.java

---

eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/data/HttpAttemptEvent.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/data/MultiHttpRequestContext.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/handler/AbstractHttpSinkHandler.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/handler/impl/CommonHttpSinkHandler.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/handler/impl/HttpSinkHandlerRetryWrapper.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/handler/impl/WebhookHttpSinkHandler.java
eventmesh-connectors/eventmesh-connector-http/src/test/java/org/apache/eventmesh/connector/http/sink/HttpSinkConnectorTest.java

Fixes #5105 
Due to the lack of communication between the retry callback and the response callback mechanism, the result after a retry failure is not handled correctly.
Move all data processing originally performed in the retry callback to the response callback handling of Vert.x.

[ISSUE #5105] Fix the retry mechanism of the HttpSinkConnector

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/LogUtilTest.java

Fixes https://github.com/apache/eventmesh/issues/4991
Motivation
Modifications
Added new tests for LogUtil.java located https://github.com/apache/eventmesh/blob/master/eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/LogUtilTest.java
Documentation
If yes, how is the feature documented? (not applicable)

[ISSUE #4991] add unit test for LogUtil

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/connector/PollConfig.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/connector/SourceConfig.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/connector/http/SourceConnectorConfig.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/connector/mq/kafka/SourceConnectorConfig.java
eventmesh-connectors/eventmesh-connector-canal/src/main/java/org/apache/eventmesh/connector/canal/source/connector/CanalSourceCheckConnector.java
eventmesh-connectors/eventmesh-connector-canal/src/main/java/org/apache/eventmesh/connector/canal/source/connector/CanalSourceFullConnector.java
eventmesh-connectors/eventmesh-connector-chatgpt/src/main/java/org/apache/eventmesh/connector/chatgpt/source/connector/ChatGPTSourceConnector.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/common/SynchronizedCircularFifoQueue.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/HttpSourceConnector.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/protocol/Protocol.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/protocol/impl/CloudEventProtocol.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/protocol/impl/CommonProtocol.java
eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/source/protocol/impl/GitHubProtocol.java
eventmesh-connectors/eventmesh-connector-http/src/main/resources/source-config.yml
eventmesh-connectors/eventmesh-connector-http/src/test/resources/source-config.yml
eventmesh-connectors/eventmesh-connector-jdbc/src/main/java/org/apache/eventmesh/connector/jdbc/source/JdbcSourceConnector.java
eventmesh-connectors/eventmesh-connector-jdbc/src/main/java/org/apache/eventmesh/connector/jdbc/source/TaskManagerCoordinator.java
eventmesh-connectors/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/source/connector/KafkaSourceConnector.java
eventmesh-connectors/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/source/connector/MongodbSourceConnector.java
eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/source/connector/OpenFunctionSourceConnector.java
eventmesh-connectors/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/source/connector/PravegaSourceConnector.java
eventmesh-connectors/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/source/connector/RabbitMQSourceConnector.java
eventmesh-connectors/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/source/connector/RedisSourceConnector.java
eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/source/connector/SpringSourceConnector.java

Fixes #5101 
For further details, refer to  #5101 
For further details, refer to  #5101 

[ISSUE #5101] Define and standardize some common configurations for all Sources

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/remote/request/ReportMonitorRequest.java
eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/monitor/AbstractConnectorMonitor.java
eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/monitor/Monitor.java
eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/monitor/MonitorRegistry.java
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/boot/RuntimeInstanceStarter.java
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/connector/ConnectorRuntime.java
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/service/health/HealthService.java
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/service/monitor/MonitorService.java
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/service/monitor/SinkMonitor.java
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/service/monitor/SourceMonitor.java
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/service/status/StatusService.java
eventmesh-runtime-v2/src/main/java/org/apache/eventmesh/runtime/service/verify/VerifyService.java

[ISSUE #5137] update connector runtime v2 module 

---

eventmesh-meta/eventmesh-meta-raft/build.gradle
eventmesh-meta/eventmesh-meta-raft/src/main/java/org/apache/eventmesh/meta/raft/JraftMetaServiceImpl.java
eventmesh-meta/eventmesh-meta-raft/src/main/java/org/apache/eventmesh/meta/raft/MetaStateMachine.java
eventmesh-meta/eventmesh-meta-raft/src/main/java/org/apache/eventmesh/meta/raft/serialize/EventMeshHessianSerializer.java
eventmesh-meta/eventmesh-meta-raft/src/main/java/org/apache/eventmesh/meta/raft/serialize/EventMeshSerializerFactory.java

Hessian Serializer add whitelist

---

.github/workflows/ci.yml
.github/workflows/code-scanning.yml
settings.gradle

Fixes #5164 
ge.apache.org is migrating to develocity.apache.org
This PR migrates the EventMesh project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
Additionally, this PR sets a projectId for use by Develocity.
- If a feature is not applicable for documentation, explain why? build-related

Publish build scans to develocity.apache.org

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/AbstractHttpHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractTCPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshAdminServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcp2Client.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/processor/HelloProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/processor/MessageTransferProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/Utils.java

[ISSUE #5185] Enhancement for http server and tcp server
