defibus-broker/src/main/java/cn/webank/defibus/broker/client/AdjustQueueNumStrategy.java

not synchronized with a String

not synchronized with String

---

defibus-client/src/main/java/cn/webank/defibus/client/impl/producer/HealthyMessageQueueSelector.java

better the producer send message flow more balanced at Topic level

---

defibus-tools/src/main/java/cn/webank/defibus/tools/admin/DeFiBusAdminExt.java

add comments

---

defibus-examples/src/main/java/cn/webank/defibus/examples/rpc/RequestProducer.java
defibus-examples/src/main/java/cn/webank/defibus/examples/rpc/ResponseConsumer.java
defibus-examples/src/main/java/cn/webank/defibus/examples/rpc/ResponseConsumerAutoReply.java
defibus-examples/src/main/java/cn/webank/defibus/examples/simple/PubProducer.java
defibus-tools/src/main/java/cn/webank/defibus/tools/command/topic/UpdateTopicPermSubCommand.java

collapse exception and format return message in example module

collapse exception and format return message in example module

---

script/broker_watchdog.sh
script/namesrv_watchdog.sh
script/runadmin.cmd
script/runadmin.sh
script/runbroker.cmd
script/runbroker.sh
script/runbroker_cloud.sh
script/runnamesrv.cmd
script/runnamesrv.sh
script/stop.cmd
script/stop.sh

It would be better to change the license to the apache2 license as other files([ISSUE](https://github.com/WeBankFinTech/EventMesh/issues/37)).

[ISSUE #37]License fix

---

defibus-namesrv/src/main/java/cn/webank/defibus/namesrv/DeFiBusNamesrvStartup.java

add init rocketmq home path

---

defibus-namesrv/src/main/java/cn/webank/defibus/namesrv/DeFiBusNamesrvStartup.java

Reverts WeBankFinTech/EventMesh#41

Revert "add init rocketmq home path"

---

eventmesh-common/build.gradle
eventmesh-emesher/build.gradle
eventmesh-store/gradle.properties

fix "can not find defibus-client"

---

docs/en/instructions/quickstart.md

add instruction of how to setting up an eventmesh environment

add quick start instruction

---

README.md
docs/en/instructions/eventmesh-emesher-quickstart.md
docs/en/instructions/eventmesh-store-quickstart.md

link readme of quickstart part to instruction of each components

link readme to store and emesher instruction

---

README.md
docs/en/instructions/eventmesh-sdk-java-quickstart.md
eventmesh-sdk-java/src/test/java/cn/webank/eventmesh/client/http/demo/AsyncPublishInstance.java
eventmesh-sdk-java/src/test/java/cn/webank/eventmesh/client/http/demo/AsyncSyncRequestInstance.java
eventmesh-sdk-java/src/test/java/cn/webank/eventmesh/client/http/demo/SyncRequestInstance.java
eventmesh-sdk-java/src/test/java/cn/webank/eventmesh/client/tcp/common/AccessTestCaseTopicSet.java

add eventmesh-sdk-java quickstart user guide

add: add eventmesh-sdk-java-quickstart user guide

---

eventmesh-emesher/src/main/java/cn/webank/emesher/admin/controller/ClientManageController.java
eventmesh-emesher/src/main/java/cn/webank/emesher/boot/ProxyStartup.java
eventmesh-emesher/src/main/java/cn/webank/emesher/configuration/AccessConfiguration.java
eventmesh-emesher/src/main/java/cn/webank/emesher/configuration/CommonConfiguration.java
eventmesh-emesher/src/main/java/cn/webank/emesher/constants/ProxyConstants.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/consumergroup/ConsumerGroupTopicConf.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/http/consumer/ConsumerManager.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/http/processor/ReplyMessageProcessor.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/http/processor/SendAsyncMessageProcessor.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/http/producer/SendMessageContext.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/tcp/client/ProxyTcp2Client.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/tcp/client/group/ClientGroupWrapper.java
eventmesh-emesher/src/test/java/client/ProxyClient.java
eventmesh-emesher/src/test/java/client/PubClient.java
eventmesh-emesher/src/test/java/client/SubClient.java
eventmesh-emesher/src/test/java/client/common/ClientConstants.java
eventmesh-emesher/src/test/java/client/common/ClientGlobal.java
eventmesh-emesher/src/test/java/client/common/MessageUtils.java
eventmesh-emesher/src/test/java/client/common/UserAgentUtils.java

remove unnecessary code and support comment in emesher

[#90]remove unnecessary code and support comment in emesher

---

eventmesh-common/src/main/java/cn/webank/eventmesh/common/IPUtil.java
eventmesh-common/src/main/java/cn/webank/eventmesh/common/protocol/tcp/AccessMessage.java
eventmesh-common/src/main/java/cn/webank/eventmesh/common/protocol/tcp/HeartBeatInfo.java
eventmesh-common/src/main/java/cn/webank/eventmesh/common/protocol/tcp/Package.java
eventmesh-common/src/main/java/cn/webank/eventmesh/common/protocol/tcp/UnRegisterInfo.java

1. modify the toString() method in the eventmesh-common component, make it more easy to read in human read type
`
HeartBeatInfo{serviceId=serviceIdinstanceId=110topicList=[topic1, topic2]}
`
to
`
HeartBeatInfo{serviceId='serviceId', instanceId='110', topicList=[topic1, topic2]}
`
2. modify some comment

modify the toString() method in the eventmesh-common component, make it more easy to read in human read type

---

eventmesh-common/src/main/java/cn/webank/eventmesh/common/IPUtil.java

validate return ip in the eventmesh-common component

validate return ip in the eventmesh-common component

---

eventmesh-common/src/main/java/cn/webank/eventmesh/common/ThreadUtil.java

@ #97 
get current process id only once，improve get current process id speed.

get current process id only once

---

eventmesh-common/src/main/java/cn/webank/eventmesh/common/protocol/http/body/client/RegRequestBody.java
eventmesh-common/src/main/java/cn/webank/eventmesh/common/protocol/http/body/message/PushMessageResponseBody.java
eventmesh-emesher/conf/proxy.properties

ascii encode inconvenient to read.
old ascii : \u6D88\u606F\u4E0B\u53D1\u5931\u8D25 \u6807\u8BB0\u5BA2\u6237\u7AEF\u9694\u79BB\u65F6\u95F4
change to : client isolation time if the message send failure
fix #101 
fix #100

modify the proxy.properties with ascii encoding, and fix some toString() method error

---

README.md

Add release link and license link in Readme

Add release link and license link in Readme

---

eventmesh-emesher/src/main/java/cn/webank/emesher/configuration/CommonConfiguration.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/tcp/client/group/ClientGroupWrapper.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/tcp/client/session/send/SessionSender.java
eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/tcp/client/task/MessageTransferTask.java

improve cost time of the method ProxyUtil.getLocalAddr() in message transformation

fix: performance improvement,reduce cost time in message transformation #116 

---

eventmesh-emesher/src/main/java/cn/webank/emesher/core/protocol/tcp/client/session/push/SessionPusher.java

push the msg into unAckMap before execute the push action, and remove the msg from unAckMap at the callback when push to client failed #120

fix ack problem 

---

build.gradle

remove logback spelling

---

eventmesh-sdk-java/src/main/java/com/webank/eventmesh/client/http/conf/LiteClientConfig.java

fix security

---

eventmesh-sdk-java/src/main/java/com/webank/eventmesh/client/http/AbstractLiteClient.java
eventmesh-sdk-java/src/main/java/com/webank/eventmesh/client/http/RemotingServer.java
eventmesh-sdk-java/src/main/java/com/webank/eventmesh/client/http/conf/LiteClientConfig.java
eventmesh-sdk-java/src/main/java/com/webank/eventmesh/client/http/consumer/context/LiteConsumeContext.java
eventmesh-sdk-java/src/main/java/com/webank/eventmesh/client/http/producer/LiteProducer.java
eventmesh-sdk-java/src/test/java/com/webank/eventmesh/client/http/demo/AsyncPublishInstance.java
eventmesh-sdk-java/src/test/java/com/webank/eventmesh/client/http/demo/AsyncSyncRequestInstance.java
eventmesh-sdk-java/src/test/java/com/webank/eventmesh/client/http/demo/SyncRequestInstance.java

#153You are right. Actually, the configCenter is used to dynamically discover the eventmesh addr.As to your question, maybe you can do as follows:
- create topic
- start defibus consumer, subscribe the topic
- run demo in eventmesh-sdk-java with your topic

remove code relatived to configcenter#153

---

docs/cn/features/https.md
eventmesh-emesher/conf/proxy.properties

fix config and doc

---

eventmesh-common/gradle.properties
eventmesh-emesher/gradle.properties
eventmesh-sdk-java/gradle.properties

release v1.1.1

---

README.md
README.zh-CN.md

modify roadMap

---

eventmesh-common/src/main/java/com/webank/eventmesh/common/config/CommonConfiguration.java
eventmesh-common/src/main/java/com/webank/eventmesh/common/config/ConfigurationWraper.java
eventmesh-connector-api/build.gradle
eventmesh-connector-api/src/main/java/com/webank/eventmesh/api/consumer/MeshMQPushConsumer.java
eventmesh-connector-defibus/src/main/java/com/webank/eventmesh/connector/defibus/consumer/DeFiBusConsumerImpl.java
eventmesh-connector-rocketmq/src/main/java/com/webank/eventmesh/connector/rocketmq/consumer/PushConsumerImpl.java
eventmesh-connector-rocketmq/src/main/java/com/webank/eventmesh/connector/rocketmq/consumer/RocketMQConsumerImpl.java
eventmesh-connector-rocketmq/src/test/java/rocketmq/consumer/PushConsumerImplTest.java
eventmesh-runtime/src/main/java/com/webank/eventmesh/runtime/configuration/AccessConfiguration.java
eventmesh-runtime/src/main/java/com/webank/eventmesh/runtime/configuration/ProxyConfiguration.java
eventmesh-runtime/src/main/java/com/webank/eventmesh/runtime/core/plugin/MQConsumerWrapper.java
eventmesh-runtime/src/main/java/com/webank/eventmesh/runtime/core/protocol/http/consumer/ProxyConsumer.java
eventmesh-runtime/src/main/java/com/webank/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
eventmesh-runtime/src/main/java/com/webank/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java

fix send rr msg bug #188 
- fix rr reply bug
- rollback delete config file in eventmesh-common
- remove setInstanceName method in eventmesh-connector-api

fix send rr msg bug

---

eventmesh-connector-defibus/src/main/java/com/webank/eventmesh/connector/defibus/utils/OMSUtil.java
eventmesh-connector-rocketmq/src/main/java/com/webank/eventmesh/connector/rocketmq/utils/OMSUtil.java

fix consumer pull request missing bizNo

---

eventmesh-runtime/src/main/java/com/webank/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java

fix missing instanceName for broadcastConsumer refering to NullPointer Exception

[ISSUE #211]Rocketmq-connector throw nullpointer exception

---

eventmesh-runtime/src/main/java/com/webank/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java

fix：this problem because of heartBeat processor client info managing error

[ISSUE #212]For multiple listening instances, only the last started instance can receive messages

---

eventmesh-runtime/src/main/java/com/webank/eventmesh/runtime/core/protocol/tcp/client/session/push/retry/ProxyTcpRetryer.java

Fix NumberFormatException In ProxyTcpRetryer Class.

[ISSUE #216]EventMesh ProxyTcpRetryer throws NumberFormatException

---

docker/centos7-jdk8/Dockerfile
docker/eventmesh-defibus/Dockerfile
docker/eventmesh-rocketmq/Dockerfile
eventmesh-runtime/bin/start.sh

support running eventmesh in docker

[ISSUE #201]Could we support running eventmesh in docker

---

eventmesh-starter/gradle.properties
eventmesh-starter/src/main/java/com/webank/eventmesh/starter/StartUp.java
eventmesh-starter/src/main/java/org/apache/eventmesh/starter/StartUp.java

[ISSUE #282]Refactor 'eventmesh-starter' package name to org.apache

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/ssl/MyX509TrustManager.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/AsyncPublishInstance.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/AsyncSyncRequestInstance.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/SyncRequestInstance.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/common/EventMeshTestCaseTopicSet.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/common/EventMeshTestUtils.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/AsyncPublish.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/AsyncPublishBroadcast.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/AsyncSubscribe.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/AsyncSubscribeBroadcast.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/SyncRequest.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/SyncResponse.java
eventmesh-sdk-java/src/test/resources/application.properties

[ISSUE #296]add licenses in file under eventmesh-sdk-java

---

eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/AbstractContext.java
eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/RRCallback.java
eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/consumer/MeshMQPushConsumer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshConstants.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/retry/EventMeshTcpRetryer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java

[ISSUE #293]Lack of licenses in each source file under the eventmesh-connector-api module

---

eventmesh-test/bin/http_pub.sh
eventmesh-test/bin/http_sub.sh
eventmesh-test/bin/tcp_pub.sh
eventmesh-test/bin/tcp_pub_broadcast.sh
eventmesh-test/bin/tcp_sub.sh
eventmesh-test/bin/tcp_sub_broadcast.sh
eventmesh-test/build.gradle
eventmesh-test/conf/application.properties
eventmesh-test/conf/server.env
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/AsyncPublishInstance.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/AsyncSyncRequestInstance.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/SyncRequestInstance.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/sub/SpringBootDemoApplication.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestCaseTopicSet.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/demo/AsyncPublish.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/demo/AsyncPublishBroadcast.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/demo/AsyncSubscribe.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/demo/AsyncSubscribeBroadcast.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/demo/SyncRequest.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/demo/SyncResponse.java
eventmesh-test/src/main/java/org/apache/eventmesh/util/Utils.java
gradle/wrapper/gradle-wrapper.properties

[ISSUE #298]Lack of licenses in each source file under the eventmesh-test module

---

eventmesh-starter/build.gradle

[ISSUE #297]Lack of licenses in each source file under the eventmesh-starter module

---

build.gradle

bugfix build.gradle tar task

---

.github/workflows/greetings.yml

ISSUE #348
By setuping the GitHub Greetings workflow, we can:
1. Accurately identify new users and contributors
2. Encourage new users and contributors
3. Attract new users and contributors to the WeChat Group and our mailing lists

[ISSUE #348] Setup automated workflows for greetings

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/loadbalance/LoadBalanceSelector.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/loadbalance/LoadBalanceType.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/loadbalance/RandomLoadBalanceSelector.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/loadbalance/Weight.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/loadbalance/WeightRoundRobinLoadBalanceSelector.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/loadbalance/RandomLoadBalanceSelectorTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/loadbalance/WeightRoundRobinLoadBalanceSelectorTest.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/AbstractLiteClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/conf/LiteClientConfig.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/consumer/LiteConsumer.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/LiteProducer.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/util/HttpLoadBalanceUtils.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/util/HttpLoadBalanceUtilsTest.java

close #333 
Disscuss Thread: https://lists.apache.org/thread.html/r5190488286772ca4077519850a05201e0e48f35f4b5f363611e66ff4%40%3Cdev.eventmesh.apache.org%3E

[Issue #333] Support multiple load balance strategy in sdk

---

docs/en/features/eventmesh-cloudevents-sdk-binding.md

This commit only includes a brief introduction and requirements. Design details can be followed up in a later commit.
This is a very WIP draft of the eventual design. This PR is opened to get some early feedback on the narrative and specified requirements.
#274

[Issue #274] add: requirements for lightweight EventMesh SDK with CloudEvents

---

.github/workflows/check-license.yml
.licenserc.yaml

[ISSUE #310] add github action for check license

---

docs/cn/instructions/eventmesh-sdk-java-quickstart.zh-CN.md
docs/en/instructions/eventmesh-sdk-java-quickstart.md
eventmesh-runtime/src/test/java/client/common/ClientConstants.java
eventmesh-runtime/src/test/java/client/common/MessageUtils.java
eventmesh-runtime/src/test/java/demo/CCSubClient.java
eventmesh-runtime/src/test/java/demo/CClientDemo.java
eventmesh-runtime/src/test/java/demo/SyncPubClient.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/AsyncPublishInstance.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/AsyncSyncRequestInstance.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/common/EventMeshTestCaseTopicSet.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/AsyncSubscribe.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/AsyncSubscribeBroadcast.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/demo/SyncResponse.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/AsyncPublishInstance.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/AsyncSyncRequestInstance.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/sub/service/SubService.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestCaseTopicSet.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/demo/AsyncSubscribe.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/demo/AsyncSubscribeBroadcast.java
eventmesh-test/src/main/java/org/apache/eventmesh/tcp/demo/SyncResponse.java

use clear name to replace obscure topic in test file

[ISSUE #393]:perf topic name in test file

---

.github/workflows/greetings.yml

[ISSUE #406] Github Actions: Resource not accessible by integration

---

eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ClientConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java

[ISSUE #405]fix typo

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/config/CommonConfigurationTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/config/ConfigurationWrapperTest.java
eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ClientConfiguration.java
eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ConfigurationWrapper.java
eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/RocketMQConsumerImpl.java
eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/RocketMQProducerImpl.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshStartup.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/plugin/MQProducerWrapper.java

I found an error in the spelling of `configurationWraper`, fix it in this PR

[ISSUE #436] fix ConfigurationWrapper typo

---

build.gradle
eventmesh-common/src/test/java/org/apache/eventmesh/common/IPUtilTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/ThreadUtilTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/tcp/codec/CodecTest.java

[ISSUE #374]add test case.

---

.github/workflows/ci.yml
CONTRIBUTING.md
CONTRIBUTING.zh-CN.md
build.gradle
gradle.properties
tool/license/allowed-licenses.txt

[ISSUE #456] Automatic License report and check

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java

[ISSUE #451] Fix SSLContext Initialize error

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java
eventmesh-runtime/conf/eventmesh.properties
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/retry/EventMeshTcpRetryer.java

[ISSUE #460]Support custom retry times configuration when SubcriptionType is SYNC

---

build.gradle
eventmesh-common/build.gradle
eventmesh-common/gradle.properties
eventmesh-connector-plugin/eventmesh-connector-api/build.gradle
eventmesh-connector-plugin/eventmesh-connector-api/gradle.properties
eventmesh-connector-plugin/eventmesh-connector-rocketmq/build.gradle
eventmesh-connector-plugin/eventmesh-connector-rocketmq/gradle.properties
eventmesh-connector-plugin/gradle.properties
eventmesh-runtime/build.gradle
eventmesh-runtime/gradle.properties
eventmesh-sdk-java/gradle.properties
eventmesh-spi/build.gradle
eventmesh-spi/gradle.properties
eventmesh-starter/gradle.properties
eventmesh-test/build.gradle
eventmesh-test/gradle.properties
gradle.properties
tool/license/allowed-licenses.txt

[ISSUE #465]All third part dependencies should be controlled at root build.gradle

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/ThreadUtilTest.java

[ISSUE #468] ThreadUtilTest failed

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/message/PushMessageRequestHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/message/PushMessageResponseHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/message/ReplyMessageRequestHeaderTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/protocol/http/header/message/ReplyMessageResponseHeaderTest.java

For #374 .
- add unit test for PushMessageRequestHeader class.
- add unit test for PushMessageResponseHeader class.
- add unit test for ReplyMessageRequestHeader class.
- add unit test for ReplyMessageResponseHeader class.

[ISSUE #374] add unit test for header class.

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/async/AsyncContext.java

in this class, complete only change false to true and never will be false again. And when you want to use get() in atomicBoolean, is just return a volatile boolean. If we use volatile here instead atomicBoolean, we will reduce each meaningless CAS check and there's no difference with before.

[ISSUE #405]maybe there is no need to use atomicboolean here

---

docs/cn/features/spi.zh-CN.md
docs/en/features/spi.en-US.md

[ISSUE #367] Add SPI design docs

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java

fix the configuration check error

[ISSUE #473]fix configuration property get error

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/EventMeshUtilTest.java

[ISSUE #405]use RandomStringGenerator instead deprecated class RandomStringUtils

---

build.gradle
docs/en/features/eventmesh-metrics-export-design.md
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
eventmesh-runtime/build.gradle
eventmesh-runtime/conf/eventmesh.properties
eventmesh-runtime/conf/prometheus.yml
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/http/HTTPMetricsServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/openTelemetry/OpenTelemetryExporterConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/openTelemetry/OpenTelemetryHTTPMetricsExporter.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/openTelemetry/OpenTelemetryTCPMetricsExporter.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/tcp/EventMeshTcpMonitor.java
tool/license/allowed-licenses.txt

[ISSUE #340]merge otel metric branch 2 develop

---

docs/cn/instructions/eventmesh-runtime-quickstart.zh-CN.md
docs/en/instructions/eventmesh-runtime-quickstart.md

[ISSUE #340]polish quickstart

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/producer/MeshMQProducer.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/ProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/RocketMQProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/utils/OMSUtil.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/plugin/MQProducerWrapper.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/producer/EventMeshProducer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java

close #490.
*Support service invocation for tcp mode*

[ISSUE #490] Support service invocation

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/RandomStringUtil.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/AsyncPublishInstance.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/AsyncSyncRequestInstance.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/SyncRequestInstance.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/AsyncPublishInstance.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/AsyncSyncRequestInstance.java
eventmesh-test/src/main/java/org/apache/eventmesh/http/demo/SyncRequestInstance.java

[ISSUE #505]remove all RandomStringUtils.

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java

add http trace http point.

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/loadbalance/LoadBalanceType.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/loadbalance/WeightRandomLoadBalanceSelector.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/loadbalance/WeightRandomLoadBalanceSelectorTest.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/conf/LiteClientConfig.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/util/HttpLoadBalanceUtils.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/util/HttpLoadBalanceUtilsTest.java

Hi,  this pull request support a new type of selector with weighted random load balance strategy to make user config their routing rule more flexible.
- add a weighted random load balance selector
- add some unit test

add weighted random load balacne selector

---

README.md

Fixes ISSUE#588.
There's a typo in README.md, I want correct it.
I changed `quickstar` to `quickstart`.
nothing needed.

[ISSUE #588] Fix typo in README.md

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java

[Bug #590] Consumer subscription topic is invalid (#590)

---

README.zh-CN.md

just fixed a wrong url in cn-doc.

fixed a wrong url in cn-doc

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java

[Bug #590] resolve_exception->Consumer subscription topic is invalid (#590)

---

README.zh-CN.md

[ISSUE #677] Translate readme files from English to Chinese

---

eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/pub/cloudevents/AsyncPublishInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/util/Utils.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/util/HttpUtils.java

[Minor] update cloudevents examples

---

gradle/wrapper/gradle-wrapper.properties

Bump gradle version to 7.3.3 Support Java17 build
Bump gradle version from 7.1 to 7.3.3

Bump gradle version to 7.3.3 to Support Java17 build

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/pub/cloudevents/AsyncPublishInstance.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/EventMeshHttpProducer.java
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat

[ISSUE #690]Remove extra code style check job in CI

---

docs/cn/instructions/eventmesh-runtime-quickstart-with-docker.md
docs/en/instructions/eventmesh-runtime-quickstart-with-docker.md

Fixes ISSUE #673 .
update docker quickstart
- update English version
- add zh-cn version
- Does this pull request introduces a new feature? no

[ISSUE #673] update eventmesh-runtime-quickstart-with-docker.md en & cn

---

docs/en/features/eventmesh-workflow-design.md

Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
Added small updates to text and update to workflow definition

Small updates to workflow design doc

---

eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/utils/OMSUtil.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/UpStreamMsgContext.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/PubClientImpl.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/SubClientImpl.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CClientDemo.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncPubClient.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncSubClient.java

Remove the unnecessary call `toString`

[MINOR] Remove unnecessary call toString

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPPubClient.java

Fix #727
Add the exception cause to help trouble shoot

[ISSUE #727] Missed exception cause

---

build.gradle

[ISSUE #732] Binary package failed to execute 

---

eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ClientConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventmeshRebalanceImpl.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/ValueComparator.java

[MINOR] Remove the unnecessary boxing

---

build.gradle

The `extension` has been deprecated, and it's better to use `archiveExtension`.
- If a feature is not applicable for documentation, explain why? no

[MINOR] Optimize gradle zip  and tar task

---

.github/ISSUE_TEMPLATE/bug_report.yml

* Help user easy to report bug.
no
- Does this pull request introduce a new feature? yes

[MINOR] Add environment and version selector in bug_report.yml

---

build.gradle
eventmesh-common/build.gradle
eventmesh-connector-plugin/eventmesh-connector-standalone/build.gradle
eventmesh-protocol-plugin/eventmesh-protocol-api/build.gradle
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/build.gradle
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/build.gradle
eventmesh-protocol-plugin/eventmesh-protocol-openmessage/build.gradle
tools/third-party-dependencies/known-dependencies.txt
tools/third-party-licenses/LICENSE

Fixes ISSUE #750.
Affects the pom file that is associated with eventmesh-common.
Changed build.gradle.
- If yes, how is the feature documented? not documented
- If a feature is not applicable for documentation, explain why? build issue

[Issue #750] junit should only be used in tests

---

build.gradle
tools/third-party-dependencies/known-dependencies.txt
tools/third-party-licenses/LICENSE

Fixes ISSUE #752.
httpclient has a CVE
build change to get new dependency version
- If yes, how is the feature documented? not documented
- If a feature is not applicable for documentation, explain why? build change

[Issue #752] upgrade httpclient

---

build.gradle
tools/third-party-dependencies/known-dependencies.txt
tools/third-party-licenses/LICENSE

Fixes ISSUE #754.
guava has a CVE
pom.xml
- If yes, how is the feature documented? not documented
- If a feature is not applicable for documentation, explain why? build change

[Issue-754] upgrade guava

---

eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/util/NetUtils.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/pub/eventmeshmessage/AsyncPublishInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/cloudevents/AsyncPublish.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/eventmeshmessage/AsyncPublish.java
eventmesh-examples/src/main/java/org/apache/eventmesh/util/Utils.java

Remove unused field in example module.
Remove unused field

[MINOR] Remove unused field in example

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestCaseTopicSet.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java

Fix the hardcode ip address
- change the ip address to `localhost`
- do a clean up

[MINOR] Fix the hardcode ip address

---

eventmesh-admin/README.md
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/Constants.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/HttpMethod.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/controller/AdminController.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/util/NetUtils.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/util/RequestMapping.java

Fixes ISSUE #784 
Modifications
1. fix "appication" misspell
2. add Contansts in admin package
3. optimize admin http method constants

[ISSUE #784] Fix words misspell, optimize admin http method code

---

eventmesh-admin/README.md
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/Constants.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/HttpMethod.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/util/NetUtils.java
eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/util/RequestMapping.java

Fixes ISSUE  #784 
Modifications
1. fix "appication" misspell
2. add Contansts in admin package
3. optimize admin http method constants

[ISSUE #784] Fix words misspell, optimize admin http method code 

---

build.gradle

fix Cannot resolve external dependency junit

---

.github/workflows/ci.yml

close #804 
More details, please see #804

[ISSUE #804] Run CI on all branch

---

build.gradle
eventmesh-trace-plugin/eventmesh-trace-zipkin/gradle.properties

[ISSUE #809] add zipkin plugin properties

---

README.md
README.zh-CN.md

Fixes ISSUE #830 .
*Updated README.*
*The slack invite link was no longer working, so I updated it to latest one.*
*Updated Slack Invite link*
- Does this pull request introduces a new feature? (no)
- If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

Updated slack invite link in README

---

docs/cn/instructions/eventmesh-runtime-quickstart-with-docker.md
docs/en/instructions/eventmesh-runtime-quickstart-with-docker.md

Fixes ISSUE #819 .
Documentation Related `eventmesh-runtime-quickstart-with-docker.md` docker run command contains">"
Optimized documentation docker script code blocks
none.

Optimized documentation docker script code blocks

---

.github/workflows/ci.yml

[MINOR] update ci.yml enable codecov

---

.github/ISSUE_TEMPLATE/unit_test.yml
docs/cn/instructions/eventmesh-unit-test-rule.md
docs/en/instructions/eventmesh-unit-test-rule.md

Add guidelines documents and `issue` templates for unit test code.
Added the unit test guidelines document and `issue` template.
- Does this pull request introduce a new feature?   no

Add the unit guidelines document and issue template

---

eventmesh-webhook/eventmesh-webhook-admin/build.gradle
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/ManufacturerObject.java
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookConfig.java
eventmesh-webhook/eventmesh-webhook-receive/build.gradle
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookController.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookRequest.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/protocol/ProtocolManage.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/WebHookConfigOperationManage.java

[ISSUE #865 ](https://github.com/apache/incubator-eventmesh/issues/865)
Two WebHookConfigOperation interface (NacosWebHookConfigOperation FileWebHookConfigOperation) are implemented.
实现了Nacos、File写入Webhook配置的接口。

[ISSUE #865] Implemented NacosWebHookConfigOperation FileWebHookConfigOperation

---

docs/zh/sdk-java/01-introduction.md
docs/zh/sdk-java/02-http.md
docs/zh/sdk-java/03-tcp.md
docs/zh/sdk-java/04-grpc.md
docs/zh/sdk-java/_category_.json

Fixes ISSUE #579, **Work In Progress**
Add a more explicit Java client guide for EventMesh.
- Translate the en-version guide of sdk-java, which is introduced by #836

[WIP][ISSUE #579] Guide of EventMesh Java SDK

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/file/FileChangeContext.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/file/FileChangeListener.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/file/WatchDirectoryTask.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/file/WatchFileManager.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/file/WatchFileTask.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/config/CommonConfigurationTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/config/ConfigurationWrapperTest.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/file/WatchFileManagerTest.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshStartup.java

Fixes ISSUE #890.
ConfigurationWrapper internally reads files at regular intervals, regardless of whether the files change or not, and the timer introduces a delay that causes configuration information to not be updated immediately after the change. I think the configuration information can be updated in real time by using WatchService to listen for changes in the configuration file.
add WatchFileManager
add FileChangeListener

Add file listener manager

---

README.md
README.zh-CN.md

Fixes ISSUE #891.
*The Chinese version of Readme was not up-to-date before.  I updated the Chinese version of readme so that those who had trouble reading the English version can also learn about this project*
*Update the Readme file by updating the file `README.zh-CN.md`*
- remove the deprecated Chinese documentation, and write the new one based on the English version.

[ISSUE #891] Sync Update Chinese Version of Readme

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/HTTPTrace.java

Fixes ISSUE #865 .
add a java class named HTTPTrace.java for EM-WebHook.

[ISSUE #865] EM-Webhook: add HTTPTrace support

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HttpProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/WebHookProcessor.java

Add HttpProcessor & WebHookProcessor.

[ISSUE #865] Add HttpProcessor & WebHookProcessor

---

eventmesh-runtime/conf/eventmesh.properties

fix : #930 
Fixes ISSUE #<XXXX>.

[ISSUE #930] registry plugin is disabled by default

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshStartup.java

fix : #932
Fixes ISSUE #<XXXX>.

[ISSUE #932] EventMeshHTTPConfiguration variable Camel-Case named

---

eventmesh-examples/bin/http_pub_eventmeshmessage.sh
eventmesh-examples/bin/http_sub.sh
eventmesh-examples/bin/tcp_eventmeshmessage_sub.sh
eventmesh-examples/bin/tcp_pub_eventmeshmessage.sh
eventmesh-examples/bin/tcp_pub_eventmeshmessage_broadcast.sh
eventmesh-examples/bin/tcp_sub_eventmeshmessage_broadcast.sh
eventmesh-runtime/bin/start.sh
eventmesh-runtime/bin/stop.sh

[ISSUE #939]Darwin operating system detection bug fix

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java

[ISSUE #938] Code optimization

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java

[ISSUE #940] LocalSubscribeEventProcessor json deserialize error

---

.github/ISSUE_TEMPLATE/documentation_related.yml
.github/ISSUE_TEMPLATE/unit_test.yml

The issue Template cannot be automatically labeled
The link is not working
Modify to the corresponding label.
Update link

[MINOR] update issue template

---

.github/workflows/ci.yml
README.md
README.zh-CN.md
docs/en/installation/01-runtime.md
docs/zh/instructions/eventmesh-runtime-quickstart.md

* Using apache release link in doc

[MINOR] Use Apache release rather than Github release in README

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshStartup.java

Fixes ISSUE #992.
Cannot exit the process if exception occurs in EventMeshStartup.main. 
Add System.exit(-1) in try -catch block.

[ISSUE #992] Add System.exit(-1) in catch block EventMeshStartup.main()

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java

Fixes ISSUE #993.
Cannot find the value of protocolType (EventMeshMessage) from MessageTransferTask.java (eventmeshmessage) in ProtocolAdaptor due to typo
Modify the value of protocolType ("EventMeshMessage" -> "eventmeshmessage")

[ISSUE #993] Modify the value of protocolType

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java

Fixes ISSUE #1022.
Two NPE problems fixes for Tcp Protocol Resolver.
*Two NPE problems fixes for Tcp Protocol Resolver.*

[ISSUE #1022] Two NPE problems fixes for Tcp Protocol Resolver

---

eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/EventMeshExtensionConstant.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/JarExtensionClassLoader.java
eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/MetaInfExtensionClassLoader.java

Fixes ISSUE #950.
SPI plugin path config can move to constant config that can manage them.
SPI plugin path config can move to constant config.

[ISSUE #950] SPI plugin path config can move to constant config

---

README.md
README.zh-CN.md

Fixes ISSUE #1033.
Lack of files
Update documents of quick-start

[ISSUE #1033]Update quick-start

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/ProducerGroupConf.java

replace == with equals() at line 50 ProducerGroupConf.java
Fixes ISSUE #997 .

[ISSUE #997] [Bug] ProducerGroupConf equals method doesn't work

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/IPUtils.java

Fixes ISSUE #1038 
Fix valid target url bug in http protocol.

[ISSUE #1038] fix valid url bug

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/HTTPTrace.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/common/EventMeshTrace.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/WebHookProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java

[ISSUE #865] update http processors supported trace annotation

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/MessageUtils.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/openmessage/OpenMessageTCPClient.java

Fixes ISSUE #1050 .
Before sending the message, add the necessary message validation

[ISSUE #1050]add msg check before send in sdk

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/registry/Registry.java

[ISSUE #1043] Fix the problem of shared registry singleton.

---

eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/test/java/org/apache/eventmesh/metrics/prometheus/config/PrometheusConfigurationTest.java

[ISSUE #1074]Fix PrometheusConfigurationTest running test fail

---

eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolConstant.java
eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver/HttpRequestProtocolResolver.java

Fixes ISSUE #1087 
Extract the constants from the image into the class HttpProtocolConstant.

[ISSUE #1087] Extract constants of protocol-http module

---

docs/zh/desing-document/06-cloudevents.md

Fixes #1068.
Translate desing-document/cloudevents to zh

[ISSUE #1068] translate desing-document/cloudevents to zh

---

eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver/HttpRequestProtocolResolver.java
eventmesh-registry-plugin/eventmesh-registry-consul/src/test/java/ConsulRegistryServiceTest.java

fix gradle build fail exception

[MINOR] fix gradle build fail exception

---

docs/en/instruction/01-store-with-docker.md
docs/zh/instruction/01-store-with-docker.md

fix: Remove unnecessary whitespace #1117
Fixes ISSUE #<XXXX>.

fix: Remove unnecessary whitespace #1117

---

eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/ZipkinTraceService.java
eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/common/ZipkinConstants.java
eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/config/ZipkinConfiguration.java

[ISSUE #1079] Extract constants of Zipkin trace module

---

docs/zh/desing-document/01-workflow.md

Fixes ISSUE #1062 .
translate document (workflow.md)

[ISSUE #1062]translate document (workflow.md)

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #1102.
Use the auto link feature (like above) helps maintaining the status of issues.

[ISSUE #1102] PR auto link to issue

---

eventmesh-trace-plugin/eventmesh-trace-api/src/main/java/org/apache/eventmesh/trace/api/common/EventMeshTraceConstants.java
eventmesh-trace-plugin/eventmesh-trace-api/src/main/java/org/apache/eventmesh/trace/api/config/ExporterConfiguration.java

Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>
Fixes #1078 .

[ISSUE #1078] Extract constants of ExporterConfiguration

---

eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java

Fixes ISSUE #1076 .
Extracted the constant "webhook" and defined it as CONSTANTS_WEBHOOK

[Issue #1076] Extraction of constants nacoswebhook

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HandleMsgContext.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java

[ISSUE #1017] Remove invalid code and open log

---

eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolAdaptor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java

Fixes #1170 
Remove unused local variables which aim to keep code clean.

[Enhancement] Remove some unused local variables

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcServer.java

[ISSUE #986] Remove unused replyMsgThreadPoolQueue

---

eventmesh-connector-plugin/eventmesh-connector-knative/build.gradle
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/config/ClientConfiguration.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/DefaultConsumer.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/KnativeConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/PullConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/domain/NonStandardKeys.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/patch/EventMeshConsumeConcurrentlyContext.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/patch/EventMeshConsumeConcurrentlyStatus.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/patch/EventMeshMessageListenerConcurrently.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.consumer.Consumer
eventmesh-connector-plugin/eventmesh-connector-knative/src/test/java/org/apache/eventmesh/connector/knative/connector/KnativeConnectorTest.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/test/java/org/apache/eventmesh/connector/knative/consumer/KnativeConsumerImplTest.java

Fixing ISSUE #1187.
*Implemented and tested Consumer module to subscribe an event from Knative (ISSUE #1187).*
*This PR for ISSUE #1187 will be merged into knative-connector branch.*
- KnativeConsumer base on **Pull** communication model
- subscribe method
- unsubscribe method
- Unit test for KnativeConsumer
- Integration test for KnativeProducer and KnativeConsumer
**Thanks @qqeasonchen and @xwm1992 for their super helpful suggestions in the design and implementation.**
*Assume the cloudevents-player Knative service has already been set up on your local machine; otherwise, please follow the steps in https://knative.dev/docs/getting-started/first-source/#sending-an-event to set up a Knative service (cloudevents-player) as source and sink.* 
```bash
$ cd …
```

[ISSUE #1187] Knative Connector: Initial Implementation of Consumer.

---

docs/zh/desing-document/03-stream.md

- Translate the design document (stream.md) 
Cloese #1063.
Translate the design document (stream.md)
Translate the design document (stream.md)

ISSUE #1063: [Doc] Translate the design document (stream.md)

---

docs/en/design-document/03-stream.md
docs/zh/desing-document/03-stream.md

Fixes #1174.
[Doc] Image link not working [03-stream.md]
[Doc] Image link not working [03-stream.md]

[ISSUE #1174] image link not work

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/trace/TraceUtils.java
eventmesh-security-plugin/eventmesh-security-api/src/main/java/org/apache/eventmesh/api/auth/AuthService.java
eventmesh-security-plugin/eventmesh-security-auth-http-basic/src/main/java/org/apache/eventmesh/auth/http/basic/impl/AuthHttpBasicService.java

Fixes #1202 
Remove warning code
Remove warning code

 [ISSUE #1202] Remove warning code

---

eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/QueryWebHookConfigByIdHandler.java

[ISSUE #1211] Fix code style check for CI

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/WebHookProcessor.java

Fix webhook request type convert error
#1195 
None
None

[ISSUE #1195] Fix webhook request type convert error

---

eventmesh-connector-plugin/eventmesh-connector-kafka/build.gradle
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/ConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerRunner.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/KafkaProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/resources/kafka-client.properties
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java

Fixes #1205.
*Complete the support for Kafka Connector*
*Fix bugs in Kafka Producer*
*Implemented a Minimum Viable Kafka Consumer*
- Yes
- It will be documented after its completion and rollout in a separate PR

[ISSUE #1205] Fix bugs in Kafka Producer and Minimum Viable Kafka Consumer

---

docs/zh/desing-document/webhook.md

#1224 
Some of the document's image URL needs to be updated.
Fix URL path.
None

[Document] Fix document invalid image urls

---

eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcMessageProtocolResolver.java
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/grpc/GrpcMessageProtocolResolver.java

Fixes the style check failure caused by PR #1233 associated with issue #1081.

[ISSUE #1081] Fix style check

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/plugin/MQWrapper.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/consumergroup/ConsumerGroupTopicConfig.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/HeartbeatProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java

See https://github.com/apache/incubator-eventmesh/issues/1161

[ISSUE #1161] Remove invalid code [ runtime module core and util directory ]

---

eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/protocol/GithubProtocol.java

[ISSUE #1276] update github protocol under the webhook module

---

eventmesh-server-go/plugin/connector/rocketmq/constants/message_constants.go
eventmesh-server-go/plugin/connector/rocketmq/convert/rocketmq_message_reader.go
eventmesh-server-go/plugin/connector/rocketmq/convert/rocketmq_message_reader_test.go
eventmesh-server-go/plugin/connector/rocketmq/convert/rocketmq_message_writer.go
eventmesh-server-go/plugin/connector/rocketmq/convert/rocketmq_message_writer_test.go

#1266  
- add RocketMQ message to event writer/reader
None

[ISSUE #1266] [Go-Server] add RocketMQ message to event writer/reader

---

eventmesh-connector-plugin/eventmesh-connector-pulsar/gradle.properties

[ISSUE #1279] gradle.properties incorrect under the connector-pulsar

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/UtilsConstants.java

Extraction of constants [example module tcp directory] #1083

[ISSUE #1083] Extraction of constants under example module for tcp

---

eventmesh-server-go/plugin/connector/connector.go
eventmesh-server-go/plugin/connector/rocketmq/client/rocketmq_consumer.go
eventmesh-server-go/plugin/connector/rocketmq/client/rocketmq_producer.go
eventmesh-server-go/plugin/connector/rocketmq/config/client_config.go
eventmesh-server-go/plugin/connector/rocketmq/constants/rocketmq_message_properties.go
eventmesh-server-go/plugin/connector/rocketmq/consumer.go
eventmesh-server-go/plugin/connector/rocketmq/convert/message_ext_convert.go
eventmesh-server-go/plugin/connector/rocketmq/factory.go
eventmesh-server-go/plugin/connector/rocketmq/producer.go
eventmesh-server-go/plugin/connector/rocketmq/resource.go
eventmesh-server-go/plugin/connector/rocketmq/utils/oms_util.go
eventmesh-server-go/plugin/connector/standalone/consumer.go
eventmesh-server-go/plugin/connector/standalone/producer.go
eventmesh-server-go/plugin/connector/standalone/standalone_connector_test.go

#1288 
add go server RocketMQ consumer
add go server RocketMQ consumer
None

[ISSUE #1288] add go server RocketMQ consumer

---

eventmesh-server-go/config/plugin.go
eventmesh-server-go/runtime/consts/env.go
eventmesh-server-go/runtime/consts/state.go
eventmesh-server-go/runtime/core/grpc/Readme.md
eventmesh-server-go/runtime/core/http/Readme.md
eventmesh-server-go/runtime/core/wrapper/base.go
eventmesh-server-go/runtime/core/wrapper/consumer.go
eventmesh-server-go/runtime/core/wrapper/consumer_test.go

#1297 
Add consumer wrapper for runtime

Add consumer wrapper for runtime

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/QueryRecommendEventMeshHandler.java

Fixes #1280.
Making code clear 
try-with-finally changed to try-with-resource.
- If yes, how is the feature documented? -
- If a feature is not applicable for documentation, explain why? -
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation -

[ISSUE #1280] Change to try-with-resource

---

eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookMQProducer.java

[ISSUE #1321] update WebHookMQProducer constructor

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookController.java

[ISSUE #1330] Update WebHookController for using WebHookMQProducer

---

.gitignore
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/TopicInfo.java

[ISSUE #1329] Add TopicInfo class to store the topic info for storage-connector

---

eventmesh-server-go/config/grpc.go
eventmesh-server-go/go.mod
eventmesh-server-go/go.sum
eventmesh-server-go/pkg/util/id.go
eventmesh-server-go/pkg/util/id_test.go
eventmesh-server-go/pkg/util/pid.go
eventmesh-server-go/pkg/util/pid_test.go
eventmesh-server-go/pkg/version/version.go
eventmesh-server-go/runtime/core/protocol/grpc/config/consumer_group.go
eventmesh-server-go/runtime/core/protocol/grpc/config/producer_group.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer/consumer.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer/group_client.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer/group_option.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer/manager.go
eventmesh-server-go/runtime/core/protocol/grpc/push/context.go
eventmesh-server-go/runtime/core/protocol/grpc/push/handler.go
eventmesh-server-go/runtime/core/protocol/grpc/retry/context.go
eventmesh-server-go/runtime/core/wrapper/producer.go
eventmesh-server-go/runtime/core/wrapper/producer_test.go

add consumer implement

---

eventmesh-server-go/plugin/protocol/protocol.go

add protocol plugin api

---

eventmesh-server-go/plugin/types.go
eventmesh-server-go/runtime/core/protocol/grpc/producer/context.go
eventmesh-server-go/runtime/core/protocol/grpc/producer/manager.go
eventmesh-server-go/runtime/core/protocol/grpc/producer/producer.go
eventmesh-server-go/runtime/core/protocol/grpc/push/request.go

add runtime producer

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/ConsumerGroupInfo.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/StorageListenerInfo.java

[ISSUE #1328] Add StorageListenerInfo to store the eventlistener and topic

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/ConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerRunner.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java
eventmesh-runtime/build.gradle
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java

Fixes #1262.
*Kafka Support for manual acknowledgement: the previous version of Kakfa Connector auto commits on consuming the messages*
*Disabled the auto-commit, and implemented the manual commit with updateOffset() API*
*Pick the largest offset from the list of cloudevent given, then commit to that specific offset*
- Yes
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) 
- Not yet documented
- If a feature is not applicable for documentation, explain why? 
- Will be documented after completion of development

[ISSUE #1262] Kafka Support for manual acknowledgement

---

build.gradle
eventmesh-connector-plugin/eventmesh-connector-knative/build.gradle
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/KnativeMessageFactory.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/impl/KnativeMessageWriter.java

Fixed #1314.
*Add a parser to convert HTTP response to CloudEvent.*
*This PR for ISSUE #1314 will be merged into knative-connector branch first.*
- Implemented a parser to first convert HTTP response String to JSONObject to get header and data fields, and then use these fields to construct CloudEvent message.
- Does this pull request introduce a new feature? No.
- If yes, how is the feature documented? N/A.
- If a feature is not applicable for documentation, explain why? There is no need for this PR to add documentation.
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation. N/A.

[ISSUE #1314] Knative Connector: Parse HTTP Response to CloudEvent.

---

eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.connector.ConnectorResourceService
eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.consumer.Consumer
eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.producer.Producer

Fixes ISSUE #1316 
Motivation
Fix the pulsar connector failed to start
Modifications
Fix the spi wrong settings in resource

[ISSUE #1316] Pulsar Connector:  Repair started error with ClassNotFoundException(PulsarProducerImpl)

---

eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/utils/StringUtils.java

[ISSUE #1333] Add utils for webhook get the file config

---

eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/HookConfigOperationManage.java

[ISSUE #1344] update HookConfigOperationManage for webhook

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/ClusterInfo.java

[ISSUE #1322] Add Add the ClusterInfo to identify the storage service info

---

eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/PravegaClient.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/PravegaEvent.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/SubscribeTask.java

[ISSUE #1347] Close pravega writer when unsubscribing

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/CloudEventInfo.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/CloudEventStateEnums.java

[ISSUE #1323] Add cloudevents classes for connector-storage module

---

eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/WebhookFileListener.java

[ISSUE #1356] update WebhookFileListener for operating the webhook config

---

eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java

[ISSUE #1358] Update FileWebHookConfigOperation for webhook config

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/StorageProducer.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/CloudEventInfo.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/CloudEventStateEnums.java

[ISSUE #1320] Add the StorageProducer under the connector-storage

---

eventmesh-protocol-plugin/eventmesh-protocol-webhook/src/main/java/org/apache/eventmesh/protocol/webhook/WebHookProtocolAdaptor.java

[ISSUE #1361] Update WebHookProtocolAdaptor for pub/sub

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java
eventmesh-webhook/build.gradle
eventmesh-webhook/eventmesh-webhook-admin/build.gradle
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManage.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookOperationConstant.java

[ISSUE #1364] Fix WebHook module code checkstyle

---

docs/en/connector-knative/_category_.json
docs/en/design-document/10-knative-connector.md
docs/zh/connector-knative/_category_.json
docs/zh/desing-document/10-knative-connector.md

Fixed #1368.
*The documentation of Knative Connector should be placed under the design-document directory.*
Moved documentation of Knative Connector to the design-document directory.
- Does this pull request introduce a new feature? No.
- If yes, how is the feature documented? N/A.
- If a feature is not applicable for documentation, explain why? This is a documentation PR.
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation. N/A.

[ISSUE #1368] Knative Connector: Move Documentation to Deisgn Directory. 

---

eventmesh-protocol-plugin/eventmesh-protocol-webhook/src/main/java/org/apache/eventmesh/protocol/webhook/WebHookProtocolAdaptor.java

[ISSUE #1367] fixed webHook protocol adaptor

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/StorageConnector.java

[ISSUE 1318]  Add sub module connector-storage

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/MetaData.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/PullRequest.java

[ISSUE 1327] Add PullRequest class for storage connector consume the data

---

eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/PravegaConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/PravegaProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/PravegaClient.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/SubscribeTask.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/test/java/org/apache/eventmesh/connector/pravega/client/PravegaClientTest.java
eventmesh-filter-plugin/build.gradle
eventmesh-filter-plugin/eventmesh-filter-api/build.gradle
eventmesh-filter-plugin/eventmesh-filter-api/gradle.properties
settings.gradle

[ISSUE #1378] Add eventmesh filter plugin module

---

eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/EventMeshFilter.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/FilterRegistry.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/FilterRunner.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/factory/FilterFactory.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/loader/FilterLoader.java

[ISSUE #1382] Add EventMesh Filter interfaces

---

eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/FilterConfig.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/FilterType.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/SinkFilter.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/SourceFilter.java

[ISSUE #1384] Add filters to implement the interface

---

eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/EventMeshFilterChainHandler.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/FilterChainInitializer.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/FilterChainRunner.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/factory/StaticFilterPluginFactory.java

[ISSUE #1386] Add FilterChainHandler to run the filters

---

eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcMessageProtocolResolver.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exception/AmqpProtocolClassException.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exception/AmqpProtocolHeaderException.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exception/AmqpProtocolVersionException.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/AMQData.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/protocol/ErrorCodes.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/protocol/ProtocolFrame.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/protocol/ProtocolVersion.java

[ISSUE #1404] Implement amqp protocol version and protocol frame

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/codec/AbstractBatchDecoder.java

Fixes #1406 .
abstract decode class

[ISSUE #1406] realization amqp decoder

---

eventmesh-runtime/build.gradle
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exception/MalformedFrameException.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/AMQPFrame.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/codec/AmqpCodeDecoder.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/codec/AmqpCodeEncoder.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/protocol/ProtocolFrame.java
tools/dependency-check/known-dependencies.txt

[ISSUE #1409] realization amqp encoder 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/ChannelMethodProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/ConnectionMethodProcessor.java

[ISSUE #1423] realization channel and connection interface

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exception/AmqpFrameDecodingException.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpHandler.java

[ISSUE #1425] realization amqp command processor

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpChannel.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpConnection.java

[ISSUE #1426] connection and channel impl

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/constants/ProtocolKey.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/protocol/ProtocolVersion.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/AmqpUtils.java

Fixes #1429.
add utils for supporting AmqpConnection and AmqpChannel
None

[ISSUE #1429] Implementaion of common utils of AmqpConnection and AmqpChannel

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/MetaMessageService.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/QueueContainer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/QueueService.java

Fixes #1440.
define interface of queue service and container
define interface of meta model management
None

[ISSUE #1440] Design of management of queue and meta model

---

eventmesh-metrics-plugin/eventmesh-metrics-api/src/main/java/org/apache/eventmesh/metrics/api/model/GrpcSummaryMetrics.java

Fixes #1431 
#1431 
add metrics model of GRPC protocol
None

[ISSUE #1431] add metrics model of GRPC protocol

---

.licenserc.yaml

Fixes #1444 
#1444 
add ignore rule
None

[ISSUE #1444] Add paths-ignore rule to adapt skywalking-eye's update

---

eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/PrometheusMetricsRegistry.java
eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusGrpcExporter.java

Fixes #1432 
#1432 
add metrics exporter of GRPC protocol
None

[ISSUE #1432] add metrics exporter of GRPC protocol

---

eventmesh-metrics-plugin/eventmesh-metrics-api/src/test/java/org/apache/eventmesh/metrics/api/GrpcSummaryMetricsTest.java

Fixes #1434 
#1434 
add unit test of GRPC protocol metrics
None

[ISSUE #1434] add unit test of GRPC protocol metrics

---

eventmesh-metrics-plugin/eventmesh-metrics-api/src/test/java/org/apache/eventmesh/metrics/api/GrpcSummaryMetricsTest.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/BatchPublishMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/ReplyMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/RequestMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/SendAsyncMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ConsumerService.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ProducerService.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/grpc/EventMeshGrpcMonitor.java

Fixes #1433 .
#1433
add metrics monitor of GRPC protocol
None

[ISSUE #1433] add metrics monitor of GRPC protocol

---

docs/en/design-document/webhook.md

[ISSUE #1271]  webhook translation

---

eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/MeshMessageProtocolAdaptor.java
eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/MeshMessageProtocolConstant.java

Fixes #839.
1. extract constant into MeshMessageProtocolConstant
2. replace Strings with constants in MeshMessageProtocolConstant

[ISSUE #839] Extraction of constants [eventmesh-protocol-meshmessage]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java

Fixes https://github.com/apache/incubator-eventmesh/issues/1355 .
Motivation
Modify AsyncHTTPPushRequest.java
Modifications
log  when get ProtocolTransportObject exception
Documentation
None

[ISSUE #1355] Fix No logs when an exception occurs

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshConstants.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java

Fixes #1150 
*Replace strings with constants in ServiceUtils.java*

[ISSUE #1150] Replace strings with constants in ServiceUtils.java

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/StatusCode.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/HeartbeatProcessor.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumer.java

Fixes #1453
Solve the problem that events cannot be consumed after the server is updated and restarted.

[ISSUE #1453] GRPC client resubscribe

---

docs/en/instruction/01-store.md
docs/zh/instruction/01-store.md

Fixes #1166 .
Fixed the links in following files:
docs/en/instruction/01-store.md
docs/zh/instruction/01-store.md

[ISSUE #1166] [Doc] Document link not working [01-store.md]

---

eventmesh-catalog-go/internal/dal/catalog.go
eventmesh-catalog-go/internal/dal/model/event_catalog.go

Fixes #1467 . 
modify eventmesh-catalog internal module
modify eventmesh-catalog internal module, support QueryOperations api 

[ISSUE #1467] Modify eventMesh-catalog internal module

---

eventmesh-workflow-go/config/config.go
eventmesh-workflow-go/configs/workflow.yaml

Fixes #1472 . 
modify eventmesh-workflow config module
add eventmesh-server, eventmesh-protocol and selector config

[ISSUE #1472] Modify eventmesh-workflow config module

---

eventmesh-workflow-go/flow/engine.go
eventmesh-workflow-go/flow/model.go

Fixes #1474 . 
modify eventmesh-workflow flow module
support latest eventmesh-workflow api

[ISSUE #1474] Modify eventmesh-workflow flow module

---

eventmesh-workflow-go/internal/constants/constants.go
eventmesh-workflow-go/internal/dal/model/workflow_task.go
eventmesh-workflow-go/internal/dal/workflow.go

Fixes #1476 . 
modify eventmesh-workflow dal module
1. add new constants
2. modify query task instance logic

[ISSUE #1476] Modify eventmesh-workflow dal module

---

eventmesh-workflow-go/internal/queue/in_memory_queue.go

Fixes #1477 . 
modify eventmesh-workflow queue module
add update task instance status

[ISSUE #1477] Modify eventmesh-workflow queue module

---

eventmesh-workflow-go/internal/protocol/meshmessage.go
eventmesh-workflow-go/internal/protocol/message.go

Fixes #1478 . 
add eventmesh-workflow protocol module
support publish meshmessage

[ISSUE #1478] Add eventmesh-workflow protocol module

---

eventmesh-workflow-go/internal/schedule/inline_scheduler.go
eventmesh-workflow-go/internal/schedule/scheduler.go
eventmesh-workflow-go/server.go

Fixes #1479 . 
modify eventmesh-workflow scheduler module
Re-abstract scheduling module and add in-line scheduler

[ISSUE #1479] Modify eventmesh-workflow scheduler module

---

eventmesh-workflow-go/internal/task/event_task.go
eventmesh-workflow-go/internal/task/operation_task.go
eventmesh-workflow-go/internal/task/switch_task.go
eventmesh-workflow-go/internal/task/task.go

Fixes #1480 . 
modify eventmesh-workflow task module
modify event/operation/switch task execute logic

[ISSUE #1480] Modify eventmesh-workflow task module

---

eventmesh-workflow-go/third_party/jqer/jqer.go

Fixes #1486 . 
modify eventmesh-workflow third-party-jqer 
modify jqer default constructor logic

[ISSUE #1486] Modify eventmesh-workflow third-party-jqer 

---

README.md

update slack link in readme

---

eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/loader/FilterLoader.java
eventmesh-filter-plugin/eventmesh-filter-api/src/main/java/org/apache/eventmesh/filter/api/loader/StaticFilterLoader.java

[ISSUE #1502] Add StaticFilterLoader for filter module

---

eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshExtensionType.java

[ISSUE #1505] Update EventMeshExtensionType Enum

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java

Fixes #1009 .
The null check is redundant and hence I removed it and raised a PR
I removed a redundant null check from the code.

[ISSUE #1009]Removed redundant null check as per issue #1009

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java

#1149 [ Soundar ] Replaced Magic Strings with EventMeshConstants

---

eventmesh-workflow-go/internal/protocol/meshmessage.go
eventmesh-workflow-go/internal/protocol/message.go

Fixes #1541 . 
add license header
refer to two files
1. meshmessage.go
2. message.go

[ISSUE #1541] add license header

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java

Fixes #1548 
#1548 
Fix check style error of EventMeshConsumer
None

[ISSUE #1548] Fix check style error of EventMeshConsumer

---

docs/en/contribute/03-new-contributor-guidelines.md
docs/en/design-document/02-runtime-protocol.md
docs/zh/contribute/03-new-contributor-guidelines.md
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventmeshRebalanceImpl.java
eventmesh-sdk-go/grpc/client.go

Fixes [#<1520>.](https://github.com/apache/incubator-eventmesh/issues/1520).
- Update the _eventmesh_ keywords.
- Update the _eventmesh_ keywords.
- Does this pull request introduce a new feature? (**no**)
- If yes, how is the feature documented? (**not applicable**)

[Doc] Update the eventmesh keywords.

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/SimpleMessage.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Subscription.java

Made changes for fetching value using the key from the map as per suggestion in #1526 
Fixes #1526 
- Does this pull request introduces a new feature? no
- If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

[ISSUE #1526] update all map fetch value

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/SimpleMessage.java

[ISSUE #1560]Project build fail

---

docs/en/instruction/02-runtime.md

Fixes <https://github.com/apache/incubator-eventmesh/issues/1270>.
*Fix the issue of 1270.*
*Fix the issue of 1270.*

[Doc] Fix the issue of 1270.

---

eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/config/ClientConfiguration.java
eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/consumer/PulsarConsumerImpl.java
eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/producer/ProducerImpl.java
eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/producer/PulsarProducerImpl.java

Motivation
When enable authentication in pulsar cluster, Client needs authentication parameters.
Modifications
Add auth parameters in ClientConfiguration and configured in producer & consumer

[ISSUE #1494]  Setting authentication parameters for pulsar client in connector

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/PropertiesUtils.java

Fixes #1544 
#1544 
Add common properties file loading method 
None

[ISSUE #1544] Add common properties file loading method 

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/KafkaProducerImpl.java

Fixes #1554 
Remove invalid imports

[ISSUE #1554]Remove unused import

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerImpl.java

Fixes #1562 .
There are unused variables
Unused variables removed

[ISSUE #1562] Remove unused variables

---

eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java

Fixes #1508.
print exception message
This method uses a try-catch block that catches the Exception object, but the Exception is not printed out in the try block.
so added a logger to print exception message

ISSUE#1508 print exception message

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java

Fixes #1564.
Delete unused logger
Delete unused logger
- Does this pull request introduce a new feature? (yes / no)  no

[ISSUE #1564] Delete unused logger 

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/HeartbeatResponseBody.java

Fixes #1513 
*Removing throws exception since method does not throws any.*
- If a feature is not applicable for documentation, explain why? its an minor issue where as fall under code cleanup

[Issue #1513] - Removing throws exception

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java

Fixes #1555
Motivation
Removed unused code in ProducerImpl.java
Removing unused commented code in ProducerImpl.java
Modifications
Removed commented code in ProducerImpl.java.
Documentation
Does this pull request introduce a new feature? No
If yes, how is the feature documented? Not applicable
If a feature is not applicable for documentation, explain why? No feature is introduced

[Issue #1555] Removed unused code in ProducerImpl.java

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java

Removed invalid code
Fixes #1555.
*Remove invalid code.*
*Commented code has been removed.*
*Removed the commented code*
- If a feature is not applicable for documentation, explain why? No new feature is introduced

[ISSUE #1555]Update ProducerImpl.java

---

docs/zh/instruction/01-store-with-docker.md
docs/zh/instruction/01-store.md

[ISSUE #1176]Update 01-store-with-docker.md and 01-store.md by adding link

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/KafkaProducerImpl.java

Removed unused field
Fixes #1556.
Removing unused field
Removed a field that is never used in the code base
Removed a field.
- If a feature is not applicable for documentation, explain why? No new feature is introduced

[ISSUE #1556] Update KafkaProducerImpl.java

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/ExchangeDefaults.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/ExchangeType.java

[ISSUE #1528]define exchange constants and exchange type

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/AmqpRouter.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/RouteComponent.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/RoutingResult.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/metadata/model/BindingInfo.java

[ISSUE #1584]define message router interface

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/metadata/model/ExchangeInfo.java

[ISSUE #1586]Define exchange info model

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exception/AmqpNotFoundException.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/metadata/manager/QueueManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/metadata/manager/QueueManagerMemoryImpl.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/metadata/model/QueueInfo.java

Fixes #1587 .
1. queue create ,delete ,get
2. queue binding

[ISSUE #1587]realization amqp queue manager

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/metadata/manager/ExchangeManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/metadata/manager/ExchangeManagerMemoryImpl.java

Fixes #1590 .
1. exchange curd
2. exchange binding

[ISSUE #1590]realization amqp exchange manager

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/metadata/MetaStore.java

[ISSUE #1592]realization metadata store

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exception/AmqpException.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/service/ExchangeService.java

[ISSUE #1594] realization exchange service interface

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/util/ExchangeUtil.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/util/NameUtils.java

exchange utils and name check util

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/metadata/model/ExchangeInfo.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/service/ExchangeServiceImpl.java

realization exchange service impl

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/service/QueueService.java

define queue service interface

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/service/QueueServiceImpl.java

realization queue service impl

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshAmqpServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/AMQPFrame.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/codec/AmqpCodeDecoder.java

Modify the implementation of maxFrame size

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/CommandFactory.java

realization command factory

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpConnection.java

[ISSUE #1614]modify amqp connection command process

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/KafkaProducerImpl.java

[ISSUE #1619] optimize checkstyle for KafkaProducerImpl

---

eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java

[issue #1621] optimize checkstyle for TopicsHandler

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/UnSubscribeResponseBody.java

Fixes #1517
There is no need to declare exceptions
The method is static so removing the throws exception
"throws exception" has been removed from the code
- If a feature is not applicable for documentation, explain why? No new feature is introduced

[ISSUE #1517]Update UnSubscribeResponseBody.java

---

.asf.yaml

[ISSUE #1624]Update .asf.yaml add hacktoberfest

---

eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/PropertiesUtils.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/PropertiesUtilsTest.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/KafkaProducerImpl.java
eventmesh-trace-plugin/eventmesh-trace-api/src/main/java/org/apache/eventmesh/trace/api/config/ExporterConfiguration.java
eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/config/ZipkinConfiguration.java

Sub PR of #1580 
One of the plugins of:  Fixes #1545 
1. add charset param to common loading method.
2. add unit test of common loading method.
3. replace [trace] plugin config loading method with common utils.
4. fix some style check error.
None

[ISSUE #1545] Replace [trace] plugin config loading method with common utils

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/AbstractHttpClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/conf/EventMeshHttpClientConfig.java

[ISSUE #1625] "ssl.client.protocol" should config by user

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/SSLContextFactory.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java

[ISSUE #1628] Config of SSLContextFactory configure in EventMeshHTTPConfiguration

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/HTTPTrace.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/Utils.java

[ISSUE #1629] Extract HTTPTrace and AbstractHTTPServer duplicate code to Utils

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/file/WatchFileManager.java

Fixes #1511 .
Concatenation of string in log level may reduce performance .Used placeholder tag for dynamic string 
By using this in loggers, an evaluation will only happen if the logging level permits the message to be displayed.
Used placeholder tag for dynamic string
- Does this pull request introduces a new feature? (yes / no) no
- If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

[ISSUE #1511]Use placeholder tag to inject dynamic content[WatchFileManager]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/file/WatchFileTask.java

Fixes #1512 .
Concatenation of string in log level may reduce performance .Used placeholder tag for dynamic string
By using this in loggers, an evaluation will only happen if the logging level permits the message to be displayed.
Used placeholder tag for dynamic string
- Does this pull request introduce a new feature? (yes / no) no 

[ISSUE #1512] Use the {} tag to inject dynamic content into the string [WatchFileTask]

---

eventmesh-webhook/eventmesh-webhook-api/build.gradle
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookOperationConstant.java

[ISSUE #1072] Extraction of constants [WebHookOperationConstant]

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/BaseSQL.java
eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/BaseSQLOperation.java

[ISSUE #1392] connector-storage-jdbc sql Basic capabilities

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/StorageSQL.java
eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/StorageSQLService.java

[ISSUE #1646] connector-storage-jdbc StorageSQL interface

---

eventmesh-catalog-go/configs/catalog.yaml
eventmesh-workflow-go/config/config.go
eventmesh-workflow-go/configs/workflow.yaml
eventmesh-workflow-go/internal/protocol/message.go
eventmesh-workflow-go/internal/schedule/inline_scheduler.go
eventmesh-workflow-go/internal/schedule/scheduler.go
eventmesh-workflow-go/server.go

Fixes #1648 .
modify workflow yaml config 
modify workflow scheduler config and yaml config file

[ISSUE #1648] modify workflow yaml config

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/AbstractStorageSQL.java

[ISSUE #1393] connector-storage-jdbc MySQL base sql

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/CloudEventSQL.java
eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/CloudEventSQLOperation.java

[ISSUE #1398] connector-storage-jdbc CloudEventSQL operation

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/ConsumerGroupSQL.java
eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/ConsumerGroupSQLOperation.java

[ISSUE #1402] connector-storage-jdbc ConsumerGroupSQL operation

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/SQL/MySQLStorageSQL.java

[ISSUE #1394] connector-storage-jdbc MySQL Obtain consumption coordinates

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java

Fixes #1656 .
The searchkeys and rmbuniqid extension field don't exist.
Change nonexistent fields to others.
- no

[ISSUE #1656] fix NullPointerException of clusterEventListener

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/ResultSetTransform.java

[ISSUE #1396] add connector-storage-jdbc ResultSetTransform

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/UnRegResponseBody.java

Fixes https://github.com/apache/incubator-eventmesh/issues/1516
Modifications
Removing throws exception since method does not throws any.
Documentation
Does this pull request introduce a new feature? (yes / no) no
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable
If a feature is not applicable for documentation, explain why? its an minor issue where as fall under code cleanup

[ISSUE #1516] Removing throws exception

---

eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolAdaptor.java

Fixes #1154 .
Substituting with constants.
Code duplication makes maintenance more difficult, so it can be better to replace the multiple occurrences with a constant.
Substituting with constants

[ISSUE #1154] Substitution of constants [HttpProtocolAdaptor]

---

eventmesh-server-go/plugin/connector/standalone/consumer.go
eventmesh-server-go/plugin/connector/standalone/standalone_connector_test.go

Fixes #1651 
#1651 
#1651 
None

[ISSUE #1651] go server standalone connector optimization

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/CloudEventInfo.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/TopicInfo.java
eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/ResultSetTransformUtils.java

[ISSUE #1397] add connector-storage-jdbc ResultSetTransform realization

---

eventmesh-catalog-go/distribution/mysql-schema.sql
eventmesh-workflow-go/distribution/mysql-schema.sql

Fixes #1670 1670.
Add workflow mysql schema files
add two files:
1. workflow mysql-schema.sql
2. catalog mysql-schema.sql

[ISSUE #1670] add workflow init mysql schema sql files

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/StorageConnector.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/PullRequest.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/pull/PullCallback.java
eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/AbstractJDBCStorageConnector.java

[ISSUE #1399] add connector-storage-jdbc AbstractJDBCStorageConnector

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/StorageConnectorMetedata.java
eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/AbstractJDBCStorageConnectorMetadata.java

[ISSUE #1400] add connector-storage-jdbc AbstractJDBCStorageConnectorMetadata

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/SubscribeResponseBody.java

Fixes #1515 .
Removed exception from throws clause since the method does not throw any.
Does this pull request introduce a new feature? (yes / no) no
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable
If a feature is not applicable for documentation, explain why? It is minor issue which comes under code cleanup

[ISSUE #1515]-Removing the throws exception

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/RegResponseBody.java

Fixes #1514 
Removed exception from throws clause since the method does not throws any.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) Not Applicable
- If a feature is not applicable for documentation, explain why? It is a minor issue which comes under code cleanup.

[ISSUE #1514] Remove Exception from throws clause

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/config/ConfigurationWrapper.java
eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolAdaptor.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/AbstractHttpClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/conf/EventMeshHttpClientConfig.java

Fixes #1682 
#1682 
add pool manager when initializing the client.
None

[ISSUE #1682] Add java SDK http connection pool

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/main/java/org/apache/eventmesh/connector/storage/jdbc/JDBCStorageConnector.java

[ISSUE #1401] add connector-storage-jdbc JDBCStorageConnector

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/CloudEventStateEnums.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/Metadata.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/data/ServiceInfo.java

[ISSUE #1736] update Storage-Api storage data module

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/pull/PullCallbackImpl.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/pull/StorageAbstractContext.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/pull/StorageAsyncConsumeContext.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/pull/StoragePullService.java

[ISSUE #1739] add pullCallBackImpl realization under storage api module

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcpConnectionHandler.java

Fixes #1689 
added final modifier field in EventMeshTcpConnectionHandler.java
- If a feature is not applicable for documentation, explain why?(minor bug fix)
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation(-)

[ISSUE #1689] Make Field final in EventMeshTcpConnectionHandler.java

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/retry/EventMeshTcpRetryer.java

Fixes #1690 .
Add final keyword to avoid vulnerability

[ISSUE #1690] Field isn't final but should be [ClientGroupWrapper]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/retry/EventMeshTcpRetryer.java

Fixes #1691 .
Add final modifier
- Does this pull request introduce a new feature? (yes / no). no

[ISSUE #1691]  Field isn't final but should be [EventMeshTcpRetryer]

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/cloudevent/RabbitmqCloudEvent.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/cloudevent/RabbitmqCloudEventWriter.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/exception/RabbitmqaConnectorException.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/utils/ByteArrayUtils.java

[ISSUE #1664] add rabbitmq cloudevent and cloudevent writer

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/SubscribeResponseBody.java

ISSUE #1741
[Bug Fix]
Modifications
Fix patch in
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/SubscribeResponseBody.java
by organising the imports.
Documentation
Does this pull request introduce a new feature? (yes / no) No
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) Not Applicable
If a feature is not applicable for documentation, explain why? It is a minor issue which comes under code cleanup.

Fix. Remove throws exception.Fixed patch

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/BatchPublishMessageProcessor.java

Adding NPE Check 
Fixes #1698
Fixes #1698 .
Added a null check
- Does this pull request introduce a new feature? no 
- If a feature is not applicable for documentation, explain why? Not applicable.
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation.

[ISSUE #1698]  Adding NPE Check

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/SubscribeResponseBody.java

Fixes #1755 
#1755 
#1755 
None

[ISSUE #1755] fix check style to solve CI errors

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java

Fixes #1695.
- Does this pull request introduce a new feature? (yes / no) No 
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) NA
- If a feature is not applicable for documentation, explain why? NA

[ISSUE #1695] - Invocation of toString on an array

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/GoodbyeTask.java

Fixes #1696 .
- Does this pull request introduce a new feature? (yes / no) No 
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) NA
- If a feature is not applicable for documentation, explain why? NA

[ISSUE #1696]Update GoodbyeTask.java

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/config/ConfigKey.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/config/ConfigurationHolder.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/config/ConfigurationWrapper.java

[ISSUE #1665] add rabbitmq config

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByIpPortHandler.java

Fixes #<1720>.
good first  issue for this commiunty! 
use stringBuiler replace "+=" operator

[ISSUE #1720]RedirectClientByIpPortHandler:stringBuilder-replace-operator

---

eventmesh-sdk-go/http/conf/eventmesh_http_client_config.go
eventmesh-sdk-go/http/selector/selector.go

Fixes #1744 
#1744 
#1744 
None

[ISSUE #1744] Support Go SDK HTTP Client Load Balance: Selector Interface

---

eventmesh-sdk-go/http/conf/eventmesh_http_client_config.go
eventmesh-sdk-go/http/selector/random_selector.go
eventmesh-sdk-go/http/selector/selector.go

Fixes #1745 
NOTE: should merge after interface.
#1745 
#1745 
None

[ISSUE #1745] Support Go SDK HTTP Client Load Balance: Random Selector

---

eventmesh-sdk-go/http/conf/eventmesh_http_client_config.go
eventmesh-sdk-go/http/selector/selector.go
eventmesh-sdk-go/http/selector/weight_random_selector.go

Fixes #1746 
NOTE: should merge after interface.
#1746 
#1746 
None

[ISSUE #1746] Support Go SDK HTTP Client Load Balance: Weight Random Selector

---

eventmesh-sdk-go/http/conf/eventmesh_http_client_config.go
eventmesh-sdk-go/http/selector/selector.go
eventmesh-sdk-go/http/selector/weight_round_robin_selector.go

Fixes #1747 
NOTE: should merge after interface.
#1747 
#1747 
None

[ISSUE #1747] Support Go SDK HTTP Client Load Balance: Weight Round Robin Selector

---

eventmesh-sdk-go/http/abstract_http_client.go
eventmesh-sdk-go/http/selector/random_selector_test.go
eventmesh-sdk-go/http/selector/selector_test.go
eventmesh-sdk-go/http/selector/weight_random_selector_test.go
eventmesh-sdk-go/http/selector/weight_round_robin_selector_test.go

Fixes #1762 
#1762 
#1762 
None

[ISSUE #1762] Support Go SDK HTTP Client Load Balance: Unit Test and Client Update

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/ClientAckContext.java

Fixes #1710.
- Does this pull request introduce a new feature? (yes / no) NO 
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) NA
- If a feature is not applicable for documentation, explain why? NA

[ISSUE #1710] Fix NPE

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/consumer/RabbitmqConsumer.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/consumer/RabbitmqConsumerHandler.java

[ISSUE #1666] add rabbitmq consumer

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/producer/RabbitmqProducer.java

[ISSUE #1667] add rabbitmq producer

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowListenClientByTopicHandler.java

[ISSUE #1723] Use StringBuilder to build response

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java

Fixes #<1711>
Add null pointer exceptions
- If a feature is not applicable for documentation, explain why? It is just a null pointer check
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation not applicable

[ISSUE #1711] Possible null pointer dereference due to return value of called method 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java

Fixes #1712.
Fixes null pointer exception and removes code smells
Fixes null pointer exception and removes code smells
- If a feature is not applicable for documentation, explain why? It just fixes null pointer exceptions

[ISSUE #1712] Possible null pointer dereference due to return value of called method [SessionPusher]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/UpStreamMsgContext.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/Utils.java

[ISSUE 1714] [Enhancement] Possible null pointer dereference due to return value of called method [UpStreamMsgContext]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java

[ISSUE #1704] [Enhancement] Possible null pointer dereference due to return value of called method [SendAsyncEventProcessor] #1704

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.connector.ConnectorResourceService
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.consumer.Consumer
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.producer.Producer
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/resources/rabbitmq-client.properties

[ISSUE #1668] add rabbitmq resources info

---

docs/zh/instruction/03-demo.md

Fixes #1162 .
Fix documentation link
Fix documentation link

[ISSUE #1162] Reference links are not available in 03-demo.md

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/StorageConfig.java

[ISSUE #1776] add StorageConfig under storage api module

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/CloudEventUtils.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/Constant.java

[ISSUE #1777] add CloudEventUtils under storage api module

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/metadata/RouteHandler.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/metadata/RouteSelect.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/metadata/StorageMetaServcie.java

[ISSUE #1779] add metadata module under storage api module

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/reply/ReplyOperation.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/reply/ReplyOperationService.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/reply/ReplyRequest.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/reply/RequestReplyInfo.java

[ISSUE #1782] add reply module under storage api module

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/Utils.java

[ISSUE #1718] [Enhancement] Possible null pointer dereference due to return value of called method [Utils]

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/RabbitmqMockConnectionFactory.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/RabbitmqServer.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/consumer/RabbitmqConsumerTest.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/producer/RabbitmqProducerTest.java
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/resources/rabbitmq-client.properties

[ISSUE #1669] add rabbitmq connector unit test

---

eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/StorageConnectorInfo.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/StorageConnectorProxy.java
eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/storage/StorageConnectorService.java

[ISSUE #1784] add reply module under storage api module

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpConnection.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/util/AmqpInOutputConverter.java

Fixes #1790.
define interface of converter for conversion between AmqpMessage and AMQData in input stream and output stream.

[ISSUE #1790] Define interface of converter in amqp

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshAmqpConfiguration.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpChannel.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpHandler.java

Fixes #1788 .
1. add config in EventMeshAmqpConfiguration.java
2. fix bug in AmqpChannel

[ISSUE #1788] Add config in EventMeshAmqpConfiguration

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/SSLContextFactory.java

Fixes #1692.
The method creates an IO stream object, does not assign it to any fields, pass it to other methods that might close it, or return it, and does not appear to close the stream on all paths out of the method. This may result in a file descriptor leak.
Use finally to close resources.

[ISSUE #1692] Method may fail to close stream

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/util/AmqpGlobalMapping.java

Fixes #1794.
add mapping to manage relationship between models used in amqp

[ISSUE #1794] Implementation of mapping relationship used in Amqp

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/consumer/AmqpConsumer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/consumer/AmqpConsumerImpl.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/consumer/PushMessageContext.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpChannel.java

Fixes #1792 .
1. add amqpConsumer class that can handle message pushing
2. add PushMessageContext that wrap some context attributes which can be used during pushing message to client

[ISSUE #1792] Implementation of AmqpConsumer

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java

[ISSUE #1717] Adding NPE check

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/trace/Trace.java

[ISSUE #1716] Adding NPE Check

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/downstreamstrategy/DownstreamDispatchStrategy.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/downstreamstrategy/RandomDispatchStrategy.java

Fixes #1796.
1. define interface of downstreamDispatchStrategy
2. define a random dispatch strategy

[ISSUE #1796] Implementation of downstream strategy in amqp

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/consumer/ClientConsumerWrapper.java

Fixes #1800 .
define a class that can init and register event to event mq listener

[ISSUE #1800] Implementation of wrapper class manage amqp consumer

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/test/java/org/apache/eventmesh/connector/storage/jdbc/SQL/AbstractStorageSQLTest.java

[ISSUE #1805] add AbstractStorageSQLTest for Storage-Connector module

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/test/java/org/apache/eventmesh/connector/storage/jdbc/JDBCStorageConnectorTest.java

[ISSUE #1807] add JDBCStorageConnectorTest for Storage-Connector module

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/test/java/org/apache/eventmesh/connector/storage/jdbc/SQL/StorageSQLTest.java

[ISSUE #1808] add StorageSQLTest for Storage-Connector module

---

eventmesh-connector-plugin/eventmesh-connector-storage-jdbc/src/test/java/org/apache/eventmesh/connector/storage/jdbc/SQL/StorageSQLServiceTest.java

[ISSUE #1809] add StorageSQLServiceTest for Storage-Connector module

---

eventmesh-server-go/plugin/protocol/cloudevents/Readme.md
eventmesh-server-go/plugin/protocol/cloudevents/cloudevents.go
eventmesh-server-go/plugin/protocol/protocol.go

add prototol plugin

---

eventmesh-server-go/runtime/core/protocol/grpc/heartbeat_service.go

add heartbeat grpc logic
#1814

add hearbeat service

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java

Fixes #1685 .
Motivation
Logger should be made final to avoid vulnerability.
Modifications
Add final modifier to Logger.
Documentation
- Does this pull request introduce a new feature? (yes / no)No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)Not applicable
- If a feature is not applicable for documentation, explain why?It is a minor issue which comes under code cleanup

[ISSUE #1685] Added final modifier to Logger

---

eventmesh-server-go/go.mod
eventmesh-server-go/go.sum
eventmesh-server-go/pkg/common/protocol/grpc/keys.go
eventmesh-server-go/pkg/common/protocol/grpc/message.go
eventmesh-server-go/pkg/common/protocol/grpc/status_code.go
eventmesh-server-go/pkg/common/protocol/tcp/pck.go
eventmesh-server-go/runtime/consts/constant.go
eventmesh-server-go/runtime/consts/env.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer_group.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer_group_client.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer_group_option.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer_manager.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer_mesh.go
eventmesh-server-go/runtime/core/protocol/grpc/consumer_service.go
eventmesh-server-go/runtime/core/protocol/grpc/context.go
eventmesh-server-go/runtime/core/protocol/grpc/emitter.go
eventmesh-server-go/runtime/core/protocol/grpc/message_handler.go
eventmesh-server-go/runtime/core/protocol/grpc/processor.go
eventmesh-server-go/runtime/core/protocol/grpc/producer_group.go
eventmesh-server-go/runtime/core/protocol/grpc/producer_manager.go
eventmesh-server-go/runtime/core/protocol/grpc/producer_mesh.go
eventmesh-server-go/runtime/core/protocol/grpc/producer_service.go
eventmesh-server-go/runtime/core/protocol/grpc/request.go
eventmesh-server-go/runtime/core/protocol/grpc/retry.go
eventmesh-server-go/runtime/core/protocol/grpc/validator.go
eventmesh-server-go/runtime/core/wrapper/consumer.go
eventmesh-server-go/runtime/core/wrapper/consumer_test.go
eventmesh-server-go/runtime/core/wrapper/producer.go
eventmesh-server-go/runtime/core/wrapper/producer_test.go
eventmesh-server-go/runtime/emserver/grpc.go

- add grpc producer service
- add grpc consumer service
- add grpc heartbeat service
- add multiple processor
#1816 
#1300 
#1302
#1303 
#1305

Eventmesh server go

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowClientHandler.java

Fixes #1722 
In each iteration, the String is converted to a StringBuffer/StringBuilder, appended to, and converted back to a String. This can lead to a cost quadratic in the number of iterations, as the growing string is recopied in each iteration.
Converted string to string builder
- Does this pull request introduce a new feature? (yes / no) no 

[ISSUE #1722] Method concatenates strings using + in a loop [ShowClientHandler]

---

docs/en/roadmap.md

[ISSUE #1836]Update roadmap.md

---

eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/CloudEventsSubscribeReply.java

org/apache/eventmesh/grpc/sub/CloudEventsSubscribeReply.java 41
Add final modifier.
Fixes #1842 

[ISSUE #1842] CloudEventsSubscribeReply add final modifier 

---

eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/service/SubService.java

Fixes #1832 <XXXX>.
Make `logger` field modifier as `final`, to prevent the potential of modification.
Put java keyword `final` behind `static`
No

[ISSUE #1832] Make field modifier as `final`

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HeartBeatTask.java

[ISSUE #1694] Possible Null Pointer Dereference

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java

[ISSUE #1715] Possible Null Pointer Dereference

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java

Fixes #1706 .
If we met null ptr, we will return empty string instead of calling `String.toString()`. In the case mentioned by the issue, some variable will be used to check whether is a blank string. So we can't just throw those exception directly.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) Not applicable
- If a feature is not applicable for documentation, explain why? This is a minor issue that comes under code cleanup

[ISSUE #1706] add NPE exception check

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/producer/AbstractProducer.java

Fixes #1839 .
Make logger field modifier as private.
Use the private modifier.

[ISSUE #1839] Use the private modifier.

---

eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/client/PulsarClientWrapper.java
eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/producer/ProducerImpl.java

Motivation
Improve the performance of publish event in connector-pulsar
Modifications
Hold the producer instance in map, create when used for the first time

[ISSUE #1636] Improve the performance of publish event in connector-pulsar

---

eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/config/PravegaConnectorConfig.java

[ISSUE #1838] fix field isnt final but should be

---

docs/en/contribute/03-new-contributor-guidelines.md
docs/zh/contribute/03-new-contributor-guidelines.md

…difying branches.
Fixes #1159.
The documentation needs to be translated into Chinese as well as the git command expired.
Translate the new-contributor-guidelines document into Chinese
And modifying git commands.

[ISSUE #1159] Translate the new-contributor-guidelines document into Chinese

---

eventmesh-sdk-go/common/protocol/http/common/client_type.go
eventmesh-sdk-go/http/consumer/eventmesh_http_consumer.go
eventmesh-sdk-go/http/producer/cloudevent_producer.go

[ISSUE #1864] Fix GO SDK request missing fields

---

eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/connector/RabbitmqConnectorResourceService.java
eventmesh-runtime/build.gradle

[ISSUE #1858] Add rabbitmq ConnectorResourceService

---

eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcMessageProtocolResolver.java

Fixes #1854  
add general method for repetitive methods
add nle check for avoiding null pointer exception
add a general utils method for setting parameters 
Using Object.requireNonNull for checking if the string value is null.
- If yes, how is the feature documented? not documented
- If a feature is not applicable for documentation, explain why? just for improving the structure of code, not a new feature, and code is readable

[ISSUE #1854] Possible null pointer dereference due to return value of called method

---

eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/producer/AbstractProducer.java

Remove the unused 'logger' field in AbstractProducer. 
Fixes #1867 .

[ISSUE #1867] The unused log field [AbstractProducer]

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/cloudevents/AsyncSubscribe.java

Adding final modifier to field "handler"
Fixes #1874 
Handler field should be final but it isn't. So, added final modifier to that field.
Added final modifier to handler field
- If yes, how is the feature documented? Not applicable 
- If a feature is not applicable for documentation, explain why? Not adding any new feature

[ISSUE #1874]: add final modifier in AsyncSubscribe.java

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java

Fixes #1693 
There is a branch of statement that, if executed, guarantees that a null value will be dereferenced, which would generate a NullPointerException when the code is executed.
Add NPE check

[ISSUE #1693] Possible null pointer dereference [EventMeshServer]

---

eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/PushConsumerImpl.java

Add NPE to check for exceptions.
Fixes #1860 

[ISSUE #1860]Add NPE to check for exceptions.

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/eventmeshmessage/AsyncPublishBroadcast.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/cloudevents/AsyncSubscribe.java

add final modifier to a static variable
Fixes #1880.
In this condition, the variable is declared as private static. As it would not vary, it can be add the 'final' modifier.
Add a 'final' modifier to the declaration of the variable.
This pull request won't introduce a new feature.

[ISSUE #1880]add final modifier to a static variable

---

eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/service/SubService.java

[ISSUE #1887] Fix issue of grpc Subservice logger field miss keyword 'final'

---

eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/EventmeshSubscribeReply.java

located at:
org.apache.eventmesh.grpc.sub.EventmeshSubscribeReply line 40
Add a field  final.
Fixes #1896

[ISSUE #1896] Field isn't final but should be [EventmeshSubscribeReply]

---

eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/config/PrometheusConfiguration.java

[ISSUE #1901]Use the methods that have been extracted [prometheus ConfigurationWrapper] 

---

eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/controller/SubController.java

[ISSUE #1890]Dead store local variable

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/impl/KnativeMessageWriter.java

[ISSUE #1879] Possible null pointer dereference due to return value of called method [KnativeMessageWriter]

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/AsyncSubscribeBroadcast.java

[ISSUE #1907]Field isn't final but should be [eventmeshmessage AsyncSubscribeBroadcast]

---

eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/tcp/TcpMessageProtocolResolver.java

[TcpMessageProtocolResolver]
fix #1893
Fixes #<XXXX>.

[ISSUE #1893] Add NPE to check for exceptions in TcpMessageProtocolResolver

---

eventmesh-workflow-go/internal/constants/constants.go
eventmesh-workflow-go/internal/protocol/meshmessage.go
eventmesh-workflow-go/internal/task/operation_task.go
eventmesh-workflow-go/internal/task/switch_task.go
eventmesh-workflow-go/internal/task/task.go

Fixes #1932 .
optimize workflow-task logic 
fix task publish em message error

[ISSUE #1932]fix task publish em message error

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/impl/KnativeMessageWriter.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/producer/AbstractProducer.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/AsyncSubscribe.java
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcMessageProtocolResolver.java

[ISSUE #1943] Fix project build fail

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/cloudevents/SyncRequest.java

[ISSUE #1948][Enhancement] Possible null pointer dereference due to return value of called method [cloudevents SyncRequest]

---

eventmesh-workflow-go/go.mod
eventmesh-workflow-go/go.sum

Fixes #1934 .
upgrade workflow go.mod
upgrage catalog-proto version

[ISSUE #1934] upgrage catalog-proto version

---

eventmesh-workflow-go/internal/dal/config.go
eventmesh-workflow-go/internal/dal/workflow.go

Fixes #1933 .
optimize workflow-dal logic 
1. remove gorm log
2. add UpdateInstance interface method

[ISSUE #1933]optimize workflow-dal logic

---

eventmesh-workflow-go/third_party/jqer/jqer.go

Fixes #1931 .
optimize workflow-jq logic
modify jqer default wrap left character

[ISSUE #1931]modify jqer default wrap left character

---

eventmesh-sdk-go/grpc/client.go

Fixes #1930 .
rollback golang-sdk logic
rollback close grpc conn logic

[ISSUE #1930] rollback close grpc conn logic

---

eventmesh-catalog-go/api/catalog.go

Fixes #1929 .
optimize workflow-catalog logic
save event-catalog info-title data

[ISSUE #1929]save event-catalog info-title data

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/workflow/protos/EventmeshWorkflowGrpc.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/workflow/protos/ExecuteRequest.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/workflow/protos/ExecuteRequestOrBuilder.java
eventmesh-workflow-go/api/proto/workflow.proto

Fixes #1928 .
upgrade workflow proto
upgrage workflow proto for grpc-java

[ISSUE #1928] upgrage workflow proto for grpc-java

---

eventmesh-protocol-plugin/eventmesh-protocol-webhook/src/main/java/org/apache/eventmesh/protocol/webhook/WebHookProtocolAdaptor.java

[ISSUE #1905]Possible null pointer dereference due to return value of called method [WebHookProtocolAdaptor]

---

eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/pub/eventmeshmessage/SyncRequestInstance.java

[ISSUE #1897] Field isn't final but should be [SyncRequestInstance]

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/cloudevents/AsyncPublish.java

[ISSUE #1885]Add final to AsyncPublish

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/eventmeshmessage/AsyncPublish.java

[ISSUE #1856]add final modifier

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/KnativeMessageFactory.java

Fixes #1951 .
line 34  add a NullPointerException check to print a log to increase code robustness

[ISSUE #1951]  Possible null pointer dereference due to return value of called method [KnativeMessageFactory.java] line 34

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/cloudevents/SyncResponse.java

Fixes #1925 [Enhancement] Field isn't final but should be [cloudevents SyncResponse]

[ISSUE #1925] Field isn't final but should be [cloudevents SyncResponse]

---

README.md

[ISSUE #1947]Update README.md

---

eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ConfigurationWrapper.java

Fixes #1889  .
repeat method
located at:
org/apache/eventmesh/connector/rocketmq/config/ConfigurationWrapper.java line 65
Replace the code in the image using the method that has been extracted.
this method is located at:
org/apache/eventmesh/common/utils/PropertiesUtils.java loadPropertiesWhenFileExist

[ISSUE #1889] Use the methods that have been extracted [rocketmq ConfigurationWrapper]

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/PullConsumerImpl.java

Fixes #1891.
Method prints the stack trace to the console [PullConsumerImpl]
located at：
org/apache/eventmesh/connector/knative/consumer/PullConsumerImpl.java line 79 ，84，93
Use logger to print exception messages.

[ISSUE #1891]Method prints the stack trace to the console [PullConsumerImpl]

---

eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/PravegaClient.java

[ISSUE #1895]Added logger to record the catched exception

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CClientDemo.java

Fixes #1959 .
located at  java/org/apache/eventmesh/runtime/demo/CClientDemo.java line 38
the field logger should be final
add final modifier

[ISSUE #1959] Fix Field isn't final [CClientDemo]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java

Fixes #1967
Redundant local variables. located at:
org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java line 64 77
Fixes #1967

[ISSUE #1967] Redundant local variables 

---

eventmesh-connector-plugin/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/config/ConfigurationWrapper.java

[ISSUE #1973]Added logger to record the catched exception

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java

Fixes #1708 .
- Most of refactoring adapt "fail fast" style.
- Exception check on line 252 is quite different, null cgw won't cause NPE, and it still throw the exception for making `flag` var be false.
* Does this pull request introduce a new feature? (yes / no) no
* If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable
* If a feature is not applicable for documentation, explain why? This is a minor issue that comes under code cleanup

[ISSUE #1708] add NPE exception check

---

eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolAdaptor.java

[ISSUE #1914] fix  NPE bug [HttpProtocolAdaptor]

---

eventmesh-sdk-go/http/constant/protocol_type.go
eventmesh-sdk-go/http/producer/cloudevent_producer.go

Fixes #1983
#1983 
#1983 
None

[ISSUE #1983] Extract GO SDK protocol constant

---

eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookController.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/protocol/GithubProtocol.java
eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/HookConfigOperationManage.java

[ISSUE #1077] Extraction of constants [GithubProtocol HookConfigOperationManage WebHookController]

---

eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/WebhookFileListener.java

[ISSUE #1993] Replacing default encoding with UTF-8 in WebhookFileListener

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java

[ISSUE #1977] [Enhancement] There is no need to use return for a void method

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java

Fixes #1995.
Exception is never thrown in the method getConsumer.
Remove exception from getConsumer throws list.
- If a feature is not applicable for documentation, explain why? This is a minor change that comes under code cleanup

[ISSUE #1995] Remove exception from getConsumer throws list

---

docs/zh/contribute/02-write-unit-test.md

Fixes #1158 .
* translate the unit test doc
* translate the unit test doc to Chinese.

[ISSUE #1158] translate unit test doc 

---

eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/CloudEventsProtocolAdaptor.java

[ISSUE #1998] Possible null pointer dereference due to return value of called method [CloudEventsProtocolAdaptor]

---

eventmesh-catalog-go/cmd/build.sh
eventmesh-catalog-go/cmd/main.go
eventmesh-catalog-go/configs/testorder.yaml
eventmesh-catalog-go/go.mod
eventmesh-catalog-go/go.sum
eventmesh-catalog-go/internal/dal/config.go
eventmesh-catalog-go/server.go
eventmesh-examples/src/main/java/org/apache/eventmesh/selector/NacosSelector.java
eventmesh-workflow-go/api/workflow.go
eventmesh-workflow-go/cmd/build.sh
eventmesh-workflow-go/cmd/main.go
eventmesh-workflow-go/configs/testcreateworkflow.yaml
eventmesh-workflow-go/go.mod
eventmesh-workflow-go/go.sum
eventmesh-workflow-go/internal/constants/constants.go
eventmesh-workflow-go/internal/dal/workflow.go
eventmesh-workflow-go/server.go

Fixes #2004 
add workflow/catalog create command logic
add workflow/catalog create command logic

[ISSUE#2004] add workflow/catalog create command logic

---

eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java

[ISSUE# 2016]add NPE check

---

eventmesh-sdk-go/examples/http/async_pub_cloudevents.go
eventmesh-sdk-go/http/eventmesh_ret_obj.go
eventmesh-sdk-go/http/producer/cloudevent_producer.go
eventmesh-sdk-go/http/producer/cloudevent_producer_test.go
eventmesh-sdk-go/http/producer/eventmesh_http_producer.go
eventmesh-sdk-go/http/producer/eventmesh_protocol_producer.go

Fixes #2017 
#2017 
#2017 
None

[ISSUE #2017] Support Go SDK http protocol RR command

---

eventmesh-sdk-go/examples/http/sub_cloudevents.go
eventmesh-sdk-go/http/consumer/eventmesh_http_consumer.go
eventmesh-sdk-go/http/consumer/eventmesh_http_consumer_test.go

Fixes #2008 
#2008 
#2008 
None

[ISSUE #2008] Support Go SDK Http protocol un-subscription

---

eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/config/ConfigurationWrapper.java

Fixes [[ISSUE #2014](https://github.com/apache/incubator-eventmesh/issues/2014)] 
Motivation [[ISSUE #2014](https://github.com/apache/incubator-eventmesh/issues/2014)] 
Modifications [[ISSUE #2014](https://github.com/apache/incubator-eventmesh/issues/2014)] 
Documentation
None

[ISSUE #2014]  Method throws alternative exception from catch block without history [pulsar ConfigurationWrapper]

---

docs/en/instruction/03-demo.md

I found a problem with document jumping, so i optimize document reference.
optimize document reference.

optimize document reference

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/WebhookProtocolTransportObject.java

Fixes #1534.
* recalculate serialVersionUID

[ISSUE #1534] Recalculate serialVersionUID

---

eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/SyncRequestInstance.java

[ISSUE #2033]Field isn t final but should be [SyncRequestInstance]

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/ClientGlobal.java

[ISSUE #2030]Field isn't final but should be [ClientGlobal]

---

eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcMessageProtocolResolver.java

Fixes #2036.
*Lambda can be replaced with method reference*
*cloudevents GrpcMessageProtocolResolver类中第214行lamdba替换为方法引用*

[ISSUE #2036] Lambda can be replaced with method reference

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/config/ConfigurationWrapperTest.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshConstants.java

Fixes #2035.
Optimize ConfigurationWrapper constructer, avoid the problem of NPE exception.

[ISSUE #2035]Optimize ConfigurationWrapper constructer, avoid the problem of NPE exception.

---

eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/CloudEventsAsyncSubscribe.java

[ISSUE #1987]Field isn't final but should be [CloudEventsAsyncSubscribe]

---

eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/consumer/PulsarConsumerImpl.java

Update PulsarConsumerImpl.java for log print update
#2042

[ISSUE #2042]Update PulsarConsumerImpl.java for log print update

---

docs/zh/instruction/01-store-with-docker.md
docs/zh/instruction/01-store.md

Fixes #1176
*原下一步动作指示没有可直接点击的链接*
*修改了01-store-with-docker.md 01-store.md里的超链接地址，可直接跳转*

[ISSUE#1176] Update 01-store-with-docker.md 01-store.md

---

eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/eventmeshmessage/AsyncPublishBroadcast.java

[ISSUE #2047] Method call passes for non-null parameter

---

docs/zh/instruction/01-store-with-docker.md

Update 01-store-with-docker.md link description

[ISSUE#1176] Update 01-store-with-docker.md link description

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java

[ISSUE #1726] [Enhancement] Inefficient use of keyset iterator instead of entrySet iterator [SubscribeProcessor]

---

eventmesh-catalog-go/configs/catalog.yaml
eventmesh-catalog-go/configs/testexpress.yaml
eventmesh-catalog-go/configs/testorder.yaml
eventmesh-catalog-go/configs/testpayment.yaml
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/pub/eventmeshmessage/WorkflowAsyncPublishInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowExpressAsyncSubscribe.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowOrderAsyncSubscribe.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowPaymentAsyncSubscribe.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/catalog/EventMeshCatalogClient.java
eventmesh-workflow-go/configs/testcreateworkflow.yaml
eventmesh-workflow-go/configs/workflow.yaml
eventmesh-workflow-go/internal/task/switch_task.go

Fixes #2054 
Submit missing files to improve workflow demo
Submit missing files to improve workflow demo

[ISSUE#2054] modify workflow demo

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/CloudEventProducer.java

org/apache/eventmesh/client/http/producer/CloudEventProducer.java line 121 122
Add NPE exception check.
Fixes #2059

[ISSUE #2059]Possible null pointer dereference [CloudEventProducer]

---

docs/zh/sdk-java/02-http.md

Fixes #2066.
Optimize zh http-demo document.

[ISSUE #2066]Optimize zh http-demo document.

---

eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/broker/task/SubScribeTask.java

Fixes #2062 
located at:
org/apache/eventmesh/connector/standalone/broker/task/SubScribeTask.java line 61
Add NPE to check for exceptions.
Add type check before convert
- If yes, how is the feature documented?  not documented

[ISSUE #2062]Add type check before convert

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/HttpResponseUtils.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/WebhookUtil.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/HttpResponseUtilsTest.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/ServerGlobalTest.java

[ISSUE #2061] enhance test cases

---

.github/workflows/ci.yml

Fixes #2048 
To update node dependencies is necessary update action versions
* Update actions/checkout from v2 to v3
* Update github/codeql-action/init from v1 to v2
* Update actions/setup-java from v1 to v3
* Fix issue template typo
- no
- not applicable 
- Is a update to ci

[ISSUE #2048] Update actions to update your dependencies

---

eventmesh-server-go/go.mod
eventmesh-server-go/go.sum

Fixes #2095 .
remove unused go library
remove unused go library

[ISSUE #2095] remove unused go library

---

eventmesh-catalog-go/configs/testexpress.yaml
eventmesh-catalog-go/configs/testpayment.yaml
eventmesh-catalog-go/distribution/mysql-schema.sql

Fixes #2098 .
modify workflow demo related files
modify workflow demo related files

[ISSUE #2098] modify workflow demo related files

---

eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/config/ConfigurationWrapper.java
eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/ConsumerImpl.java

Fixes #2078  
#2072 
#2078 
#2072 
#2078 
None

[ISSUE #2078] fix CI error: kafka connector

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/KnativeMessageFactory.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/PullConsumerImpl.java

Fixes #2079  
#2072 
#2079  
None
None

[ISSUE #2079] fix CI error: knative connector

---

eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/PravegaClient.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/config/PravegaConnectorConfigWrapper.java

Fixes #2080 
#2072 
#2080  
None
None

[ISSUE #2080] fix CI error: pravega connector

---

eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/config/ConfigurationWrapper.java

Fixes #2081  
#2072 
#2081   
None
None

[ISSUE #2081] fix CI error: pulsar connector

---

eventmesh-connector-plugin/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/config/ConfigurationWrapper.java

Fixes #2082 
#2072 
#2082   
None
None

[ISSUE #2082] fix CI error: redis connector

---

eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/PushConsumerImpl.java

Fixes #2083 
#2072 
#2083 
None
None

[ISSUE #2083] fix CI error: rocketmq connector

---

eventmesh-examples/src/main/java/org/apache/eventmesh/common/ExampleConstants.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/pub/eventmeshmessage/WorkflowAsyncPublishInstance.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/CloudEventsSubscribeReply.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/controller/SubController.java
eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/service/SubService.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java
eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/service/SubService.java

Fixes #2084 
#2072 
#2084 
None

[ISSUE #2084] fix CI error: example

---

eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolAdaptor.java

Fixes #2085 
#2072 
#2085  
None
None

[ISSUE #2085] fix CI error: protocol http

---

eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/MeshMessageProtocolAdaptor.java

Fixes #2086 
#2072 
#2086 
None
None

[ISSUE #2086] fix CI error: protocol mesh message

---

eventmesh-common/src/test/java/org/apache/eventmesh/common/config/ConfigurationWrapperTest.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/SSLContextFactory.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshConstants.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/BatchPublishMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/ClientAckContext.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/UpStreamMsgContext.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/GoodbyeTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HeartBeatTask.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/HttpResponseUtils.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/HttpResponseUtilsTest.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/ServerGlobalTest.java

Fixes #2087 
#2072 
#2087  
None
None

[ISSUE #2087] fix CI error: runtime

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/util/EventMeshClientUtil.java
eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/demo/SyncRequestInstance.java

Fixes #2088  
#2072 
#2088
None
None

[ISSUE #2088] fix CI error: java sdk

---

eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/config/PinpointConfiguration.java
eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/exporter/PinpointSpanExporter.java

Fixes #2089 
#2072 
#2089 
None
None

[ISSUE #2089] fix CI error: trace

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java

Fixes #2073 
#2072 
#2073 
None
None

[ISSUE #2073] fix CI error: common

---

eventmesh-connector-plugin/eventmesh-connector-pravega/README.md
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/client/PravegaClient.java
eventmesh-connector-plugin/eventmesh-connector-pravega/src/main/java/org/apache/eventmesh/connector/pravega/config/PravegaConnectorConfigWrapper.java

[ISSUE #2074] Update Pravega connector doc

---

eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/EventmeshSubscribeBroadcast.java

[ISSUE #2117]EventmeshSubscribeBroadcast add final

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/AmqpMessageRouteComponent.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/RouteComponent.java

[ISSUE #2119]realization amqp route component

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/topic/TopicMatcherDFAState.java

[ISSUE #2121]realization TopicMatcherDFAState

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/topic/TopicParser.java

[ISSUE #2123]realization TopicParser

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/KnativeConsumerImpl.java

Fixes #2097 .
Use logger to print exception messages
Use logger to print exception messages

[ISSUE #2097] Use logger to print exception messages

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowClientHandler.java

[ISSUE #2144] Use try-with-resources to manage resources [ShowClientHandler]

---

eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/cloudevents/SyncRequest.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/eventmeshmessage/AsyncPublishBroadcast.java
eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/AsyncSubscribeBroadcast.java

Fixes #2138.
remove the try-with-resources
remove the try-with-resources

[ISSUE #2138] Remove the try-with-resources

---

tools/third-party-licenses/LICENSE
tools/third-party-licenses/licenses/java/LICENSE-amqp-client.txt
tools/third-party-licenses/licenses/java/LICENSE-curator-client.txt
tools/third-party-licenses/licenses/java/LICENSE-curator-framework.txt
tools/third-party-licenses/licenses/java/LICENSE-curator-recipes.txt
tools/third-party-licenses/licenses/java/LICENSE-jline.txt

[ISSUE #2145] Update the LICENSE file

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowListenClientByTopicHandler.java

Fixes #2140 
Motivation
Explain the content here.
Explain why you want to make the changes and what problem you're trying to solve.
Modifications
Describe the modifications you've done.
Documentation
Does this pull request introduce a new feature? (yes / no)
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

[ISSUE #2140]Change to try-with-resources to manage resources

---

eventmesh-catalog-go/Makefile
eventmesh-catalog-go/bin/start-catalog.sh
eventmesh-catalog-go/bin/stop-catalog.sh
eventmesh-catalog-go/internal/util/file_utils.go
eventmesh-catalog-go/server.go
eventmesh-workflow-go/Makefile
eventmesh-workflow-go/bin/start-workflow.sh
eventmesh-workflow-go/bin/stop-workflow.sh
eventmesh-workflow-go/internal/util/file_utils.go
eventmesh-workflow-go/server.go

Fixes #2147 .
add workflow run scripts
add workflow run scripts
include:
start-workflow.sh/start-catalog.sh
stop-workflow.sh/stop-catalog.sh

[ISSUE #2147] add workflow run scripts

---

eventmesh-protocol-plugin/eventmesh-protocol-webhook/src/main/java/org/apache/eventmesh/protocol/webhook/WebHookProtocolAdaptor.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowListenClientByTopicHandler.java

Fixes #2148.
fix webhook NPE
fix webhook NPE

[ISSUE #2148] Fix webhook test NPE

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByIpPortHandler.java

[ISSUE #2151] Use try-with-resources to manage resources [RedirectClientByIpPortHandler]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByPathHandler.java

fix #2165 Use try-with-resources to manage resources

[ISSUE #2165] Use try-with-resources to manage resources [RedirectClientByPathHandler]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/recommend/EventMeshRecommendImpl.java

[ISSUE #2166] return the value assigned by the local variable directly

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/consumergroup/WebhookTopicConfig.java

[ISSUE #2169] Optmise list empty check 

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/Utils.java

Fixes #2197
Method stores return result in local before immediately returning it [EventMeshRecommendImpl]

[ISSUE #2197] Method stores return result in local before immediately returning it [EventMeshRecommendImpl]

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java

replace isSize == 0 with isEmpty()
Fixes #2199

[ISSUE #2199]Update EventMeshConsumer.java replace isSize == 0 with isEmpty()

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/topic/TopicMatcherDFAState.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/topic/TopicMatcherResult.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/topic/TopicNormalizer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/topic/TopicParser.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/topic/TopicWord.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exchange/topic/TopicWordDictionary.java

Fixes #2205.
added helper classes.

[ISSUE #2205] Add helper classes of parsing topic to queue

---

eventmesh-runtime/build.gradle
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/producer/AmqpProducer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/producer/AmqpProducerManager.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/producer/PutMessageContext.java

Fixes #2207.
Implementation of amqp producer

[ISSUE #2207] Implementation of amqp producer

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/exception/UnexpectedFrameError.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/AmqpCommand.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/remoting/Command.java

Fixes #2209.
Add command and AmqpCommand

[ISSUE #2209] Implementation of Command in AMQP

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/naming/ExchangeName.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/naming/QueueName.java

Fixes #2211.
Implementation of naming service of queue and exchange

[ISSUE #2211] Implementation of naming service

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/amqp/AmqpMessage.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/consumer/AmqpConsumerImpl.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/consumer/AmqpMessageSender.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/consumer/UnacknowledgedMessageMap.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpConnection.java

[ISSUE #2213] Implementation of message sender in amqp

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/amqp/AmqpMessage.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshAmqpServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/processor/AmqpChannel.java

[ISSUE #2215] Optimization about AmqpChannel when processing BasicPublish

---

eventmesh-workflow-go/config/config.go
eventmesh-workflow-go/internal/constants/constants.go
eventmesh-workflow-go/internal/queue/eventmesh_queue.go

Fixes #2192 
#2192 
#2192 
#2192

[ISSUE #2192] Workflow Feature Implementation: Integrate EM, implement queue based on MQ

---

gradle.properties

update gradle.properties, prepare for  1.7.0 release

Prepare for  1.7.0 release

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/amqp/AmqpMessage.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/amqp/common/ProtocolKey.java
eventmesh-protocol-plugin/eventmesh-protocol-amqp/src/main/java/org/apache/eventmesh/protocol/amqp/resolver/AmqpProtocolResolver.java

[ISSUE #2218]fixed bug in AmqpMessage

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/MessageHandler.java

Fixes #2220.
the function name `createHttpPushRequest` here is wrong，update the name

[ISSUE #2220] rename push request function name

---

release-node.md

Create 1.7.0 release note

---

eventmesh-catalog-go/distribution/mysql-schema.sql
eventmesh-workflow-go/distribution/mysql-schema.sql

[ISSUE #2231] Workflow database init script add db selection command

---

maturity.md

[ISSUE #2260] update maturity docs

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/PubClientImpl.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2255

[ISSUE #2255] simplify the code

---

eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java

fix issue #2245: change to collection "StringBuilder"

[ISSUE #2245] Change to collection "StringBuilder".

---

docs/en/instruction/01-store.md

Space between "RocketMQ", and the comma wasn't required.
Fixes #<XXXX>.

Fixed grammar.

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/model/RequestParam.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2244

[ISSUE #2244] Update constants

---

eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/utils/StringUtils.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2264

[ISSUE #2264] remove static method final

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByPathHandlerTest.java

[ISSUE #2250]Reliance on default encoding [RedirectClientByPathHandlerTest]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/exception/EventMeshException.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2269

[ISSUE #2269] update EventMeshException

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/protocol/processor/WebHookProcessorTest.java

[ISSUE #2252]Reliance on default encoding [WebHookProcessorTest]

---

eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManage.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2246

add exception

---

eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/exporter/PinpointSpanExporter.java

[ISSUE #2240] (Optimize) change Boolean.True to true.

[ISSUE #2240] (Optimize) change Boolean.True to true.

---

docs/zh/desing-document/05-metrics-export.md

Fixes #1066 
Added documentation for metrics-export [Chinese version]
NA

[ISSUE #1066] Create 05-metrics-export.md

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CCSubClient.java

[ISSUE #2254] Method concatenates the result of a toString() call [CCSubClient]

---

eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/AsyncPubClient.java

[ISSUE #2253] Optimize the error log. [AsyncPubClient]

---

eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/Assert.java
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/AssertUtils.java
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/AssertTest.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/catalog/EventMeshCatalogClient.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2284

[ISSUE #2284]Simplify the code

---

eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/AbstractProducerHttpClient.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/CloudEventProducer.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/EventMeshMessageProducer.java
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/OpenMessageProducer.java
eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManage.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2287

[ISSUE #2287] Simplify the code

---

eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java

[ISSUE #2243] Change Boolean to boolean in NacosWebHookConfigOperation

---

eventmesh-connector-plugin/eventmesh-connector-knative/src/test/java/org/apache/eventmesh/connector/knative/consumer/KnativeConsumerImplTest.java
eventmesh-connector-plugin/eventmesh-connector-knative/src/test/java/org/apache/eventmesh/connector/knative/producer/KnativeProducerImplTest.java

Fixes #2291 .
Knative test code add assertion
test code add assertion

[ISSUE #2291] Knative test code add assertion

---

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByPathHandler.java

Fixes https://github.com/apache/incubator-eventmesh/issues/2304

[ISSUE #2304] String memory optimization
