apache/eventmesh

- eventmesh-runtime/build.gradle
Fixes https://github.com/apache/incubator-eventmesh/issues/2312
> [ISSUE #2312] Unified eventmesh-runtime module dependency management

- eventmesh-connector-plugin/eventmesh-connector-api/build.gradle
Fixes https://github.com/apache/incubator-eventmesh/issues/2319
> [ISSUE #2319] Unified eventmesh-connector-api dependency versioning

- eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshExtensionFactory.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2327
> remove deprecated methods

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/codec/Codec.java
Fixes #2329.
removed in.array()
> [ISSUE #2329] usage "in.array()" in Codec.java will cause exception

- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/utils/CloudEventUtils.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2322
> [ISSUE #2322] Simplify CloudEventUtils code

- eventmesh-metrics-plugin/eventmesh-metrics-api/src/main/java/org/apache/eventmesh/metrics/api/model/TcpSummaryMetrics.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/tcp/EventMeshTcpMonitor.java
Fixes #2331.
1. changed type of tps metrics from int to double
2. add reset method to each metric
> [ISSUE #2331] metrics in TCP will not be reset to zero

- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/config/PinpointConfiguration.java
Fixes #2238 .
Enhancement Reliance on default encoding
refactor PinpointConfiguration.java line 127
> [ISSUE #2238] Reliance on default encoding

- eventmesh-sdk-go/examples/grpc/consumer/asyncsub/main.go
- eventmesh-sdk-go/grpc/fake_webhookserver.go
- eventmesh-sdk-go/grpc/producer.go
> [ISSUE #2321] Resolve security issues of Go SDK

- eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/pub/eventmeshmessage/AsyncSyncRequestInstance.java
> [ISSUE #2388] update log output of AsyncSyncRequestInstance.java

- eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/service/SubService.java
> [ISSUE #2390] use logger to print exception in SubSerivce.java

- eventmesh-examples/src/main/java/org/apache/eventmesh/selector/NacosSelector.java
> format NacosSelector.java

- eventmesh-connector-plugin/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/cloudevent/CloudEventCodec.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2340
> [ISSUE #2340] Method needlessly boxes a boolean constant [CloudEventCodec]

- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/service/SubService.java
> [ISSUE #2393] use logger to print exception in gprc/SubSerivce.java

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/producer/ProducerManager.java
- eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumerTest.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2377
> [ISSUE #2377] Method calls equals on an enum instance [ProducerManager]

- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowOrderAsyncSubscribe.java
> [ISSUE #2397] add NPE check in WorkflowOrderAsyncSubscribe.java

- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowOrderAsyncSubscribe.java
> [ISSUE #2399] add final modifier in WorkflowOrderAsyncSubscribe.java

- .asf.yaml
> Update .asf.yaml temporary

- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowExpressAsyncSubscribe.java
> [ISSUE #2401] add NPE check in WorkflowExpressAsyncSubscribe.java

- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowExpressAsyncSubscribe.java
> [ISSUE #2395] add final modifier in WorkflowExpressAsyncSubscribe.java

- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowPaymentAsyncSubscribe.java
> [ISSUE #2405] add NPE check in WorkflowPaymentAsyncSubscribe.java

- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowPaymentAsyncSubscribe.java
> [ISSUE #2403] add final modifier in WorkflowPaymentAsyncSubscribe.java

- docs/zh/contribute/03-new-contributor-guidelines.md
> [ISSUE #2408] update 03-new-contributor-guidelines.md, improve readability

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/CloudEventProducer.java
> [ISSUE #2415] fix bug of getLogger() parameter in CloudEventProducer.java

- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/KnativeMessageFactory.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/impl/KnativeBinaryMessageReader.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/cloudevent/impl/KnativeMessageWriter.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/config/ClientConfiguration.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/config/ConfigurationWrapper.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/DefaultConsumer.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/KnativeConsumerImpl.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/consumer/PullConsumerImpl.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/domain/NonStandardKeys.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/producer/AbstractProducer.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/producer/KnativeProducerImpl.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/main/java/org/apache/eventmesh/connector/knative/producer/ProducerImpl.java
- eventmesh-connector-plugin/eventmesh-connector-knative/src/test/java/org/apache/eventmesh/connector/knative/producer/KnativeProducerImplTest.java
Fixes #2293 .
fix knative pmd test error 
refactor knative module code
> [ISSUE #2293] fix knative pmd test error 

- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/utils/BeanUtils.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2337
> [Enhancement] Inefficient use of keySet iterator instead of entrySet iterator [BeanUtils]

- eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/cloudevent/RabbitmqCloudEvent.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2343
> [Enhancement] Method convertToCloudEvent() encodes String bytes without specifying the character encoding

- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/config/ZipkinConfiguration.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2242
> [Enhancement] Method throws alternative exception from catch block without history [ZipkinConfiguration]

- eventmesh-trace-plugin/eventmesh-trace-api/build.gradle
- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/test/java/org/apache/eventmesh/trace/zipkin/TracePluginFactoryTest.java
Fixes #2413 .
solve module dependency cycles.
move TracePluginFactoryTest to zipkin module
delete traceapi moudle dependency zipkin module
> [ISSUE #2413] module dependency cycles

- eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java
Fixes #2427 .
SubController compile receive unchecked warning 
add @SuppressWarnings("") fix warning.
> [ISSUE #2427] SubController compile receive unchecked warning 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java
Fixes #2381 .
Method gets and sets a value of a ConcurrentHashMap in a racy manner
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java line 104
replace put method by putIfAbsent method.
> [ISSUE #2381] Method gets and sets a value of a ConcurrentHashMap in a racy manner

- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2336
> [ISSUE #2336] Method concatenates the result of a toString() call [ConsumeMessageConcurrentlyService] 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/producer/EventMeshProducer.java
> [ISSUE #2378]use == to compare two enum values

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/consumergroup/WebhookTopicConfig.java
> [ISSUE #2380]use != to compare two enum values

- eventmesh-metrics-plugin/eventmesh-metrics-api/src/main/java/org/apache/eventmesh/metrics/api/model/HttpSummaryMetrics.java
fix #2385 ,remove local variable before return.
> [ISSUE #2385] return direct result rather than local variable

- eventmesh-connector-plugin/eventmesh-connector-redis/src/test/java/org/apache/eventmesh/connector/redis/producer/RedisProducerTest.java
> [ISSUE #2342] specify the charset

- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/ProducerImpl.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2339
> [Enhancement] Method stores return result in local before immediately returning it [ProducerImpl]

- eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/consumer/StandaloneConsumer.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2335
> [Enhancement] Unboxing of 'cloudEvent.getExtension("offset")' may produce 'NullPointerException'

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java
Fixes #2373 .
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java line 75 93 97.
> [ISSUE #2373] Method calls equals on an enum instance

- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/config/ZipkinConfiguration.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2241
> [Enhancement] Method may fail to close stream and reliance on default encoding [ZipkinConfiguration]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/PropertiesUtils.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2333
> [Enhancement] Method may fail to close stream [PropertiesUtils]

- eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2247
> [Enhancement] Reliance on default encoding [FileWebHookConfigOperation]

- eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/protocol/GithubProtocol.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2248
> [Enhancement] Method throws alternative exception from catch block without history [GithubProtocol]

- eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/broker/MessageQueue.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2334
> [Enhancement] Method calls Condition.signal() rather than Condition.signalAll()

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
Fixes #2371 .
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java line 103,replace equals method with '=='.
> [ISSUE #2371] Method calls equals on an enum instance 

- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/config/PrometheusConfiguration.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
Fixes #2368 .
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java line 615 623, replace equals method with '=='.
> [ISSUE #2368] Method calls equals on an enum instance

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java
Fixes #2367 .
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java line 303,Change to use "==".
> [ISSUE #2367] Method calls equals on an enum instance

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2364
> [Enhancement] Method calls equals on an enum instance [SessionPusher]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
Fixes #2366 .
Method calls equals on an enum instance 
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java line 212,change to use "==".
> [ISSUE #2366] Method calls equals on an enum instance

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/Utils.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2359
> [Enhancement] Method calls equals on an enum instance [Utils]

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/workflow/EventMeshWorkflowClient.java
> [ISSUE #2486] use bracket instead of '+' when print log in EventMeshWorkflowClient.java

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java
> [ISSUE #2360]use == instead of equals in enum compares in MessageTransferTask

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java
> [ISSUE #2365]use == instead of equals in enum compares in DownStreamMsgContext

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/UpStreamMsgContext.java
> [ISSUE #2362]use == instead of equals in enum compares in UpStreamMsgContext

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumer.java
> [ISSUE #2474] use == instead of equals in enum compares in EventMeshGrpcConsumer

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPSubClient.java
> [ISSUE #2471] use log instead of print when exception occurred in EventMeshMessageTCPSubClient

- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/utils/CloudEventUtils.java
> [ISSUE #2338] use logger instead of prints the stack trace

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/controller/ClientManageControllerTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/handler/QueryRecommendEventMeshHandlerTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByIpPortHandlerTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByPathHandlerTest.java
Fixes #2461 .
fix runtime module admin subpackage pmd warning
refactor runtime module admin org/apache/eventmesh/runtime/admin/*.java file.
> [ISSUE #2461] runtime module admin subpackage pmd warning

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPSubClient.java
> [ISSUE #2469]add synchronized bracket in EventMeshMessageTCPSubClient

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java
> [ISSUE #2483] use log instead of print when exception occurred in CloudEventTCPSubClient.java

- eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/config/ConfigurationWrapper.java
> [ISSUE #2344]use encapsulated method

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcServer.java
Fixes #1111.
Use of random function with MIN and MAX limit for client pool
> [ISSUE #1111] Variable for Client Pool 

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/protocol/processor/WebHookProcessorTest.java
Fixes #2467 .
fix runtime module protocol subpackage pmd warning
refactor runtime module admin org/apache/eventmesh/runtime/protocol/*.java file.
> [ISSUE #2467] runtime module protocol subpackage pmd warning

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/AsyncPubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/AsyncSubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/BroadCastPubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/BroadCastSubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CCPubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CCSubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CClientDemo.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncPubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncSubClient.java
Fixes #2489 .
fix runtime module demo subpackage pmd warning
refactor runtime module admin org/apache/eventmesh/runtime/demo/*.java file.
> [ISSUE #2489]runtime module demo subpackage pmd warning 

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/ClientConstants.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/MessageUtils.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/RequestContext.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/Server.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/TCPClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/PubClientImpl.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/SubClientImpl.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPPubClient.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPPubClient.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPSubClient.java
Fixes #2491 .
fix runtime module client subpackage pmd warning
refactor runtime module admin org/apache/eventmesh/runtime/client/*.java file.
> [ISSUE #2491] runtime module client subpackage pmd warning

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/dispatch/DownstreamDispatchStrategy.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/Utils.java
Fixes #2459 .
fix :eventmesh-runtime:javadoc task warning
refinement runtime moudle javadoc
> [ISSUE #2459] :eventmesh-runtime:javadoc task warning

- eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookOperationConstant.java
Fixes #2540
'static' method declared 'final'
Removed 'final' 
located at:
eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookOperationConstant.java line 46
> [ISSUE #2540] 'static' method declared 'final'

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpCommand.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2539
> [Enhancement] Method invocation 'getBytes' may produce 'NullPointerException' [HttpCommand]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/IPUtils.java
<!--
- Name the pull request in the form "[ISSUE #XXXX] Title of the pull request", 
where *XXXX* should be replaced by the actual issue number.
Skip *[ISSUE #XXXX]* if there is no associated github issue for this pull request.
- Fill out the template below to describe the changes contributed by the pull request. 
That will give reviewers the context they need to do the review.
- Each pull request should address only one issue. 
Please do not mix up code from multiple issues.
- Each commit in the pull request should have a meaningful commit message.
- Once all items of the checklist are addressed, remove the above text and this checklist, 
leaving only the filled out template below.
Fixes https://github.com/apache/incubator-eventmesh/issues/2521
*Explain why …
> [Enhancement] Manual array to collection copy

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/workflow/protos/ExecuteRequest.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2535
> [ISSUE #2535] Method stores return result in local before immediately returning it [ExecuteRequest]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowClientBySystemHandler.java
Fixes #2545 .
refactor String concatenation '+=' in loop
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowClientBySystemHandler.java 
,convert variable "result" from String to StringBuilder.
> [ISSUE #2545] refactor String concatenation '+=' in loop

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/AssertUtils.java
- eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/config/ConfigurationHolder.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2514
> [ISSUE #2514] The repetitive code of the ConfigurationHolder we can simplify

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/RRCallbackResponseHandlerAdapter.java
Fixes #2543 .
Method invocation may produce 'NullPointerException'
refactor eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/RRCallbackResponseHandlerAdapter.java 
> [ISSUE #2543] Method invocation may produce 'NullPointerException'

- eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/config/ConfigurationWrapper.java
> [ISSUE #2345]print the log of exception

- eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/SyncResponse.java
org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/SyncResponse.java 40 Add final modifier.
Fixes #2568 .
> [ISSUE #2568] Add final modifier in  [eventmeshmessage SyncResponse]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/QueryOperationsRequest.java
Fixes #2524  .
remove redundant local variable.
remove redundant local variable in `QueryOperationsRequest`.
> [ISSUE #2542] remove redundant immediate local var

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java
- eventmesh-common/src/test/java/org/apache/eventmesh/common/config/ConfigurationWrapperTest.java
Fixes #2541 .
Method may fail to close stream
refactor eventmesh-security-plugin/eventmesh-security-api/src/main/java/org/apache/eventmesh/api/common/ConfigurationWrapper.java
> [ISSUE #2541]  Method may fail to close stream

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2570
> [ISSUE #2570]EventMeshServer nulling code can be simplified

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2566
> [ISSUE #2566] CommonConfiguration can use lombok to simplify the code

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2564
> [ISSUE #2564] AbstractHTTPServer Some code can be simplified

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/QueryOperationsResponse.java
> [ISSUE #2525]return result directly without local variable

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/AbstractPushRequest.java
<!--
- Name the pull request in the form "[ISSUE #XXXX] Title of the pull request", 
where *XXXX* should be replaced by the actual issue number.
Skip *[ISSUE #XXXX]* if there is no associated github issue for this pull request.
- Fill out the template below to describe the changes contributed by the pull request. 
That will give reviewers the context they need to do the review.
- Each pull request should address only one issue. 
Please do not mix up code from multiple issues.
Fixes https://github.com/apache/incubator-eventmesh/issues/2596
- If yes, how is the feature …
> [ISSUE #2596] Method specifies an unrelated class when allocating a Logger [AbstractPushRequest]

- eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcMessageProtocolResolver.java
<!--
Fixes https://github.com/apache/incubator-eventmesh/issues/2518
> [ISSUE #2518] Method invocation 'toString' may produce 'NullPointerException' [GrpcMessageProtocolResolver]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowClientBySystemHandler.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2602
> [ISSUE #2602] Method creates local variable-based synchronized collection

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/QueryWebHookConfigByManufacturerHandler.java
Fixes #2591 .
Method converts String to boxed primitive using excessive boxing
refactor 
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/QueryWebHookConfigByManufacturerHandler.java 
> [ISSUE #2591] Method converts String to boxed primitive using excessive boxing

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/RequestHeader.java
Fixes #2530 .
Method stores return result in local before immediately returning it [RequestHeader] 
refactor
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/RequestHeader.java
> [ISSUE #2530] Method stores return result in local before immediately returning it [RequestHeader] 

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java
Fixes #2528 .
Method stores return result in local before immediately returning it [BatchMessage]
refactor
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java
> [ISSUE #2528] Method stores return result in local before immediately returning it [BatchMessage]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/http/HTTPMetricsServer.java
Fixes #2604 .
Field isn't final but should be [HTTPMetricsServer]
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/http/HTTPMetricsServer.java
> [ISSUE #2604] Field isn't final but should be [HTTPMetricsServer]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java
Fixes #2599.
Call to toString with null check warns about NPE.
Wrapping the extracting the `getExtension` call with default value into a separate method.
I have also modified the code to suppress other warnings. Please let me know if these belong to a different ticket so I revert them.
- If a feature is not applicable for documentation, explain why? refactoring
> [ISSUE #2599] Prevent NPE on toString call

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/IPUtils.java
> [ISSUE #2519]Merge the  exception catched statement

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RejectClientBySubSystemHandler.java
Fixes #2603 .
Argument type 'String' does not match the type of the format specifier '%d' 
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RejectClientBySubSystemHandler.java 
> [ISSUE #2603] Argument type 'String' does not match the type of the format specifier '%d' 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java
Fixes #2600 .
Method calls equals on an enum instance [SessionSender]
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java 
> [ISSUE #2600] Method calls equals on an enum instance [SessionSender]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Heartbeat.java
Fixes #2529 .
Method stores return result in local before immediately returning it [Heartbeat]
refactor
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Heartbeat.java
> [ISSUE #2529] Method stores return result in local before immediately returning it [Heartbeat]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
Fixes #2597 .
Method checks for an item in a set with contains, before using add()
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
> [ISSUE #2597] Method checks for an item in a set with contains, before using add()

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java
Fixes #981.
There's many `NullPointerException`s as described in the ticket.
Using Java 8 Optional API to provide sensible defaults.
- If a feature is not applicable for documentation, explain why? refactoring
> [ISSUE #981] Fix NPE exceptions in runtime HTTP processor

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcBootstrap.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHttpBootstrap.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshStartup.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTcpBootstrap.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshGrpcConfiguration.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfiguration.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/boot/EventMeshServerTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/Server.java
- eventmesh-runtime/src/test/resources/newConfiguration-runtime.properties
- eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManage.java
Fixes #2576.
Enhancement the config manage for project
1. [1] Improved the EventMeshServer configuration class initialization process
2. [2] Complete the initial configuration process and UT of EventMeshHTTPConfiguration.class
3. [3] Complete the initial configuration process and UT of EventMeshTCPConfiguration.class
4. [4] Complete the initial configuration process and UT of EventMeshGrpcConfiguration.class
> EventMeshServer config improve

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/util/HttpUtils.java
Fixes #2633 .
1.AvoidReassigningParameters
2.Unusedimports
3.compareObjectsWithEquas.
refactor code
1.new local variable.
2.delte unused imports
3.repalce == with equals method.
> [ISSUE #2633] HttpUtils PMD check warning

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigurationWrapper.java
- Name the pull request in the form "[ISSUE #XXXX] Title of the pull request", 
where *XXXX* should be replaced by the actual issue number.
Skip *[ISSUE #XXXX]* if there is no associated github issue for this pull request.
- Fill out the template below to describe the changes contributed by the pull request. 
That will give reviewers the context they need to do the review.
- Each pull request should address only one issue. 
Please do not mix up code from multiple issues.
Fixes #2635
- If a feature is not applicable for …
> [ISSUE #2635] CommonConfiguration Some code can be simplified

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/ssl/MyX509TrustManager.java
Fixes #2651 .
new MyX509TrustManager() may fail to close stream 
use a finally block or a try-with-recourse to make sure the stream is closed.
> [ISSUE #2651] new MyX509TrustManager() may fail to close stream

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/catalog/EventMeshCatalogClient.java
Fixes #2653.
Method init() makes literal string comparisons passing the literal as an argument
refactor eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/catalog/EventMeshCatalogClient.java
> [ISSUE #2653] Method init() makes literal string comparisons passing the literal as an argument

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPMessageHandler.java
Fixes #2662.
Can be replaced with 'Map.forEach()
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPMessageHandler.java line
,relace Map.keySet.forEach with Map.forEach 
> [ISSUE #2662] Can be replaced with 'Map.forEach()

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/AsyncHttpProcessor.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2691
> [ISSUE #2691] Interface methods are public by default, so you can remove the public

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java
> [ISSUE #2592] 'while' loop replaceable with enhanced 'for'

- eventmesh-metrics-plugin/eventmesh-metrics-api/src/main/java/org/apache/eventmesh/metrics/api/model/HttpSummaryMetrics.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/http/HTTPMetricsServer.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2593
> [ISSUE #2593] Method passes a simple String.format result to an SLF4J's or Log4j2's format string [HTTPMetricsServer]

- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/consumer/MongodbConsumer.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/consumer/MongodbReplicaSetConsumer.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/consumer/MongodbStandaloneConsumer.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/exception/MongodbConnectorException.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/utils/MongodbCloudEventUtil.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/utils/MongodbSequenceUtil.java
> [ISSUE #2494] Add mongodb connector consumer

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2699
> [ISSUE #2699] AbstractEventProcessor

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
Fixes #2678 .
* This pr will fix the ISSUE #2678 
IPUtils.getLocalAddress() were being called multiple time in same method
i have  assign the response to the local variable and used it .
> [ISSUE #2678] [Enhancement] Method appears to call the same method on the same object [redundantly[AsyncHTTPPushRequest] 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2741
> [ISSUE #2741] The EventMeshHTTPServer registerProcessor method simplifies the use of

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/WebhookUtil.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2730
> [ISSUE #2730] Method check a map with containsKey(), before using get() [WebhookUtil]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ConsumerService.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2723
> [ISSUE #2723]  Method passes a concatenated string to SLF4J's or Log4j2's format string [ConsumerService]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2733
> [ISSUE #2733] Method passes an incorrect number of parameters to an SLF4J or Log4j2 logging statement

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/consumergroup/StreamTopicConfig.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2713
> [ISSUE #2713] Method checks the size of a collection against zero rather than using isEmpty() [StreamTopicConfig]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/consumergroup/ConsumerGroupTopicConfig.java
Fixes #2738.
- If yes, how is the feature documented?
> [ISSUE #2738] Method calls equals on an enum instance [ConsumerGroupTopicConfig]. Change it to ==

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2712
> [ISSUE #2712] Method checks the size of a collection against zero rather than using isEmpty() [ConsumerManager]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/recommend/EventMeshRecommendImpl.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2717
> [ISSUE #2717] Method checks the size of a collection against zero rather than using isEmpty() [ConsumerManager]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RejectClientBySubSystemHandler.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2705
> [ISSUE #2705] Method handle(HttpExchange) manually handles closing an auto-closeable resource [RejectClientBySubSystemHandler]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshStartup.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/Server.java
Fixes #2766 .
fix EventMeshServer pmd test error
refactor:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshStartup.java
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/Server.java .
> [ISSUE #2766] fix EventMeshServer pmd test error

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2658
> [ISSUE #2658] Method uses immediate execution of a block of code that is often not used [RemoteUnSubscribeEventProcessor]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/Client.java
Fixes #2735 .
Method builds a list from one element using Arrays.asList [HttpClientGroupMapping]
refactor
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java .
> [ISSUE #2735] Method builds a list from one element using Arrays.asList [HttpClientGroupMapping]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/ConsumerGroupTopicConf.java
Fixes #2774 .
fix ConsumerGroupTopicConf pmd test error 
refactor  eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/ConsumerGroupTopicConf.java.
> [ISSUE #2774] fix ConsumerGroupTopicConf pmd test error 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2708
> [ISSUE #2708] Method stores return result in local before immediately returning it [ClientSessionGroupMapping]

- build.gradle
- eventmesh-trace-plugin/eventmesh-trace-jaeger/build.gradle
- eventmesh-trace-plugin/eventmesh-trace-jaeger/gradle.properties
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/java/org/apache/eventmesh/trace/jaeger/JaegerTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/java/org/apache/eventmesh/trace/jaeger/common/JaegerConstants.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/java/org/apache/eventmesh/trace/jaeger/config/JaegerConfiguration.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/test/java/org/apache/eventmesh/trace/jaeger/config/JaegerConfigurationTest.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/test/resources/jaeger.properties
- settings.gradle
Fixes #2788.
Add Jaeger tracing plugin config. 
Add the base framework of the `eventmesh-trace-jaeger` module and the implementation of the config.
> [ISSUE #2788] Add Jaeger tracing plugin config

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java
Fixes #2780 .
fix EventMeshUtil pmd test warning
refactor EventMeshUtil.java.
> [ISSUE #2780] fix EventMeshUtil pmd test warning

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/amqp/AmqpMessage.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/consumer/AmqpConsumerImpl.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/consumer/QueueConsumerMapping.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/amqp/downstreamstrategy/RandomDispatchStrategy.java
> [ISSUE #2516] AmqpConsumer bugfix

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
Fixes #2728 .
*This method checks for the presence of a key in a map using containsKey(), before attempting to fetch the value of the key using get(). This equates to doing two map lookups in a row.*
*Refactored code to do mapLookUp once and then check non null , if null then create a new list else add to existing list.*
> [ISSUE #2728] Method check a map with containsKey(), before using get() [SubscribeProcessor]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HandleMsgContext.java
Fixes #2734 .
Method builds a list from one element using Arrays.asList [HandleMsgContext]
refactor eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HandleMsgContext.java ,
use Collections.singletonList().
> [ISSUE #2734] Method builds a list from one element using Arrays.asList [HandleMsgContext]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java
Fixes #2737 .
Method calls equals on an enum instance [ConsumerManager]
refactor 
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java,
Change it to use "==" or "! =".
> [ISSUE #2737] Method calls equals on an enum instance [ConsumerManager]

- eventmesh-dashboard/pages/eventCatalogs/EventCatalogs.tsx
- eventmesh-dashboard/pages/eventCatalogs/SchemaView.tsx
- eventmesh-dashboard/pages/eventCatalogs/index.ts
- eventmesh-dashboard/pages/eventCatalogs/types.ts
Fixes #2808
To add Event Catalogs feature
- Added Event catalogs list
- Added Create schema
- Added View scheme details
No need
> [ISSUE #2808] [Feature] Dashboard-Add event catalogs

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java
Fixes https://github.com/apache/incubator-eventmesh/issues/2672
> [ISSUE #2672] Method appears to call the same method on the same object redundantly [SendAsyncMessageProcessor]

- tools/dependency-check/known-dependencies.txt
- tools/third-party-licenses/licenses/java/LICENSE-jackson-jr-objects.txt
- tools/third-party-licenses/licenses/java/LICENSE-kotlin-stdlib-common.txt
- tools/third-party-licenses/licenses/java/LICENSE-kotlin-stdlib-jdk7.txt
- tools/third-party-licenses/licenses/java/LICENSE-kotlin-stdlib-jdk8.txt
- tools/third-party-licenses/licenses/java/LICENSE-kotlin-stdlib.txt
- tools/third-party-licenses/licenses/java/LICENSE-okio-jvm.txt
Fixes #2814 .
fix license check error.
add license file
> [ISSUE #2814] license check error

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventmeshRebalanceImpl.java
Fixes #2716 .
[Enhancement] Method checks the size of a collection against zero rather than using isEmpty() [EventmeshRebalanceImpl]
Replaced size() method using MapUtils.isEmpty().
#2716 
@tarunsamanta2k20
> col.isEmpty()_1

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/model/RequestParam.java
Fixes #<XXXX>.
[Enhancement] Method checks the size of a collection against zero rather than using isEmpty() [RequestParam]
Replace size() using MapUtils.isEmpty() and removed null check.
#2720 
@tarunsamanta2k20
> col.isEmpty()

- eventmesh-dashboard/components/navigation/MenuItem.tsx
- eventmesh-dashboard/components/navigation/Menus.tsx
- eventmesh-dashboard/components/navigation/MenusMobile.tsx
- eventmesh-dashboard/pages/eventCatalogs/EventCatalogs.tsx
- eventmesh-dashboard/pages/eventCatalogs/SchemaView.tsx
- eventmesh-dashboard/pages/eventCatalogs/index.ts
- eventmesh-dashboard/pages/eventCatalogs/types.ts
- eventmesh-dashboard/pages/workflows/create.tsx
- eventmesh-dashboard/pages/workflows/details.tsx
- eventmesh-dashboard/pages/workflows/index.ts
- eventmesh-dashboard/pages/workflows/workflows.tsx
Fixes #2828 Missing Apache header in some code files of the Dashboard.
Added Apache header in navigation menu, workflows, event catalogs files
Added Apache header in navigation menu, workflows, event catalogs files
No need
> [ISSUE #2828] Added Apache header in navigation menu, workflows, event catalogs files

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/Config.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigService.java
- eventmesh-trace-plugin/eventmesh-trace-api/src/main/java/org/apache/eventmesh/trace/api/common/EventMeshTraceConstants.java
- eventmesh-trace-plugin/eventmesh-trace-api/src/main/java/org/apache/eventmesh/trace/api/config/ExporterConfiguration.java
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/PinpointTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/test/java/org/apache/eventmesh/trace/pinpoint/config/PinpointConfigurationTest.java
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/test/resources/exporter.properties
- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/ZipkinTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/test/java/org/apache/eventmesh/trace/zipkin/config/ZipkinConfigurationTest.java
- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/test/resources/exporter.properties
Fixes #2576.
Enhancement the config manage for project
[1] Add repeatable functionality to A for tagging multiple configuration fields on a class
[2] ExporterConfiguration config improve and UT
> [ISSUE #2576] Improve configuration management of TracePlugin

- eventmesh-runtime/conf/eventmesh.properties
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/controller/EventMeshAdminController.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ConfigurationHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/HTTPClientHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/MetricsHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/response/GetConfigurationResponse.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/response/GetMetricsResponse.java
> [ISSUE #2831] Fix project compile error

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
> remove the recursive method to solve the stackoverflow error

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java
> [ISSUE #2760] Method appears to call the same method on the same object redundantly [ReplyMessageProcessor]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
> [ISSUE #2667]  Method appears to call the same method on the same object redundantly [LocalUnSubscribeEventProcessor]

- eventmesh-sdk-go/common/id/id_snake_test.go
- eventmesh-sdk-go/grpc/client.go
- eventmesh-sdk-go/grpc/client_test.go
- eventmesh-sdk-go/grpc/dispatcher_test.go
- eventmesh-sdk-go/grpc/fake_grpcserver.go
- eventmesh-sdk-go/grpc/grpc_suite_test.go
- eventmesh-sdk-go/grpc/heartbeat_test.go
Fixes #<XXXX>.
fix eventmesh-sdk-go test error
use ginkgo test framework refactor test code.
> [ISSUE #2855] eventmesh-sdk-go test error

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java
> [ISSUE #2664] Method appears to call the same method on the same object redundantly [BatchSendMessageProcessor]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/Package.java
> [ISSUE #2650] Class defines a computed serialVersionUID that doesn't equate to the calculated value [Package] 

- build.gradle
- eventmesh-trace-plugin/eventmesh-trace-jaeger/build.gradle
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/java/org/apache/eventmesh/trace/jaeger/JaegerTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/java/org/apache/eventmesh/trace/jaeger/config/JaegerConfiguration.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.trace.api.EventMeshTraceService
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/resources/jaeger.properties
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/test/java/org/apache/eventmesh/trace/jaeger/JaegerTraceServiceTest.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/test/resources/jaeger.properties
Fixes #2789.
Add Jaeger tracing plugin service. 
Demo video:
https://user-images.githubusercontent.com/33992371/211131331-8b966711-415c-4f00-96a8-062418a3119f.mp4
Implement JaegerTraceService and unit tests. 
> [ISSUE #2789] Add Jaeger tracing plugin service

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
> [ISSUE #2666] Method appears to call the same method on the same object redundantly [LocalSubscribeEventProcessor]

- docs/en/design-document/13-jaeger.md
- docs/zh/desing-document/13-jaeger.md
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/test/java/org/apache/eventmesh/trace/jaeger/JaegerTraceServiceTest.java
Fixes #2790.
Add Jaeger tracing plugin en&zh docs. 
Add Jaeger tracing plugin en&zh docs. 
- If yes, how is the feature documented? (docs)
> [ISSUE #2790] Add Jaeger tracing plugin docs

- tools/dependency-check/known-dependencies.txt
> [ISSUE #2870]update known dependencies file

- eventmesh-catalog-go/internal/dal/catalog.go
- eventmesh-catalog-go/internal/dal/config.go
- eventmesh-workflow-go/cmd/controller/workflow.go
- eventmesh-workflow-go/internal/dal/workflow.go
Fixes #2880 .
optimize workflow dashboard controller module
1. optimize workflow controller save api
2. modify catalog dal module
> [ISSUE #2880] optimize workflow dashboard controller module

- eventmesh-sdk-go/http/consumer/consumer_suite_test.go
- eventmesh-sdk-go/http/consumer/eventmesh_http_consumer.go
- eventmesh-sdk-go/http/consumer/eventmesh_http_consumer_test.go
Fixes #2885 .
eventmesh-sdk-go http consumer subscribe bug
remove duplicate element 
> [ISSUE #2885] eventmesh-sdk-go http consumer subscribe bug

- eventmesh-workflow-go/internal/dal/workflow.go
Fixes #2894.
Optimize workflow save interface
Optimize workflow save interface
> [ISSUE #2894] optimize workflow save dal logic

- eventmesh-sdk-go/http/producer/cloudevent_producer_test.go
- eventmesh-sdk-go/http/producer/eventmesh_message_producer_test.go
- eventmesh-sdk-go/http/producer/producer_suite_test.go
Fixes #2897 .
refactor eventmesh-sdk-go http.producer module test code
refactor test code using ginkgo test framework.
> [ISSUE #2897] refactor eventmesh-sdk-go http.producer module test code

- eventmesh-dashboard/package.json
> [ISSUE #2908] Remove the override of @chakra-ui/system

- gradle.properties
update gradle.properties, prepare for 1.8.0 release
> Prepare for 1.8.0 release

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
Fixes #2714 .
#2714 
@tarunsamanta2k20
> [ISSUE #2714] Method checks the size of a collection against zero rather than using isEmpty() [HttpClientGroupMapping]

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/CloudEventProducer.java
Method checks the size of a collection against zero rather than using isEmpty(), I have changed that for better code clarity.
Fixes #<XXXX>.
> Used isEmpty() instead of making comparison

- .licenserc.yaml
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/CloudEventProducer.java
Fixes #2945 .
fix license check error
add DISCLAIMER in .licenserc.yaml
>  [ISSUE #2945] fix license check error

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpCommand.java
Fixes #<XXXX>.
This pr request will fix the issue #2648 
> [ISSUE #2648] Class defines a computed serialVersionUID that doesn't equate to the calculated value [HttpCommand] 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventmeshRebalanceImpl.java
> [ISSUE #2731] Method calls keySet() just to call contains, use containsKey instead [EventmeshRebalanceImpl]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventmeshRebalanceImpl.java
Fixes #2731 .
Want to start contributing in Open Source
Changed the method call from mySet.keySet().contains("foo") to mySet.containsKey("foo")
> Issue #2731 Update EventmeshRebalanceImpl.java

- .licenserc.yaml
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/CloudEventProducer.java
> Revert "Used isEmpty() instead of making comparison"

- eventmesh-trace-plugin/eventmesh-trace-api/src/main/java/org/apache/eventmesh/trace/api/TracePluginFactory.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/java/org/apache/eventmesh/trace/jaeger/JaegerTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/test/java/org/apache/eventmesh/trace/jaeger/JaegerTraceServiceTest.java
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/PinpointTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/config/PinpointConfiguration.java
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/exporter/PinpointSpanExporter.java
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/test/java/org/apache/eventmesh/trace/pinpoint/PinpointTraceServiceTest.java
- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/ZipkinTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/test/java/org/apache/eventmesh/trace/zipkin/ZipkinTraceServiceTest.java
Fixes #2956 .
refactor eventmesh-trace-plugin module
1.reduce unnecessary dependencies.
2.use public method access class field.
3.delete unnecessary class fields.
4.shutdownhook thread setDaemon(true).
5.shutdown method add code of release necessary resources .
> [ISSUE #2956] refactor eventmesh-trace-plugin module

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/SimpleMessageWrapper.java
> [ISSUE #2647] rebuild serialVersionUID (#2647)

- docs/en/design-document/01-workflow.md
Reverts apache/incubator-eventmesh#2959
> Revert "Update 01-workflow.md"

- eventmesh-common/src/main/java/org/apache/eventmesh/common/exception/JsonException.java
Fixes #2644 
- Rebuild JsonException serialVersionUID
> [ISSUE #2644]Rebuild JsonException serialVersionUID

- eventmesh-sdk-go/README.md
Fixes #2968
- Polish eventmesh-sdk-go README.md document
> [ISSUE #2968]Polish eventmesh-sdk-go README.md document

- eventmesh-server-go/examples/webhook/main.go
> [ISSUE #2922] Fix go server security issue

- .licenserc.yaml
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/controller/ClientManageController.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/controller/ClientManageControllerTest.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/CloudEventProducer.java
- eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManager.java
- eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java
- eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java
- eventmesh-webhook/eventmesh-webhook-admin/src/test/java/org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManagerTest.java
Fixes #2939 .
refactor org.apache.eventmesh.webhook.admin submodule
1.rename AdminWebHookConfigOperationManage to AdminWebHookConfigOperationManager.
2.import lombok @Slf4j annotation to simplify code.
> [ISSUE #2939] refactor org.apache.eventmesh.webhook.admin submodule

- .licenserc.yaml
- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/Config.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigInfo.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigService.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/convert/converter/ObjectConverter.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/CloudEventProducer.java
Fixes #2942 .
Config Annotation add reloadMethodName attribute
Config Annotation add reloadMethodName attribute
> [ISSUE #2942] Config Annotation add reloadMethodName attribute

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java
Method calls equals on an enum instance #2983
Fixes #<XXXX>.
> Changed the equals method on enum to ==

- docs/en/design-document/01-workflow.md
- docs/zh/design-document/01-workflow.md
Fixes #3029 
*Fix AsyncAPI official website is incorrect in 01-workflow.md*
> [ISSUE #3029]Fix AsyncAPI official website is incorrect in 01-workflow.md

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/Operation.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java
- eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/PropertiesUtilsTest.java
Fixes #3026 
- Remove unused imports in eventmesh-common module
> [ISSUE #3026]Remove unused imports in eventmesh-common module

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java
> [ISSUE #3042] fix check style issue to unblock CI

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TopicHandler.java
Fixes #3020 
- Get String bytes by StandardCharsets.UTF_8
> [ISSUE #3020]Get String bytes by StandardCharsets.UTF_8

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumer.java
- eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumerTest.java
> [ISSUE #3056] fix ci check error for testBuildSubscription method

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ConfigurationHandler.java
Fixes #3005 .
*Change to use try-with-resources to manage resources.*
> [ISSUE #3005]Change to use try-with-resources to manage resources.

- docs/en/instruction/01-store-with-docker.md
- docs/zh/instruction/01-store-with-docker.md
Fixes #3022 
- Polish 01-store-with-docker.md cn and en document rocketmq image of docker pull
> [ISSUE #3022]Polish 01-store-with-docker.md cn and en document rocketmq image of docker pull

- style/copyright/Apache.xml
Fixes #3038 
*Add apache copyright xml for IDEA*
> [ISSUE #3038]Add apache copyright xml for IDEA

- eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java
Fixes #3040 .
add the callback method for kafka producer.
> [ISSUE #3040] fix issue that producer will throw 'publish error' caused by operation timeout with kafka connector

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/AbstractProducerHttpClient.java
> [ISSUE #2970] Method invocation 'getRetCode' may produce 'NullPointerException'[AbstractProducerHttpClient]

- docs/zh/introduction.md
Fixes #2990 
*Translation introduction.md (EN->CN)*
> [ISSUE #2990]Translation introduction.md (EN->CN)

- eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookMQProducer.java
Fixes #3065 .
refactor WebHookMQProducer
1.add final modifier
2.add transient modifiers
3.remove unused code.
> [ISSUE #3065] refactor WebHookMQProducer fix pmdTest warning

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigService.java
Fixes #3070 
*Refactor and optimize the ConfigService class*
> [ISSUE #3070]Refactor and optimize the ConfigService class

- eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/cloudevent/RabbitmqCloudEvent.java
- eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/utils/ByteArrayUtils.java
> [ISSUE #2949] Fix deserialization security risks of rabbitmq connector

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/NetUtils.java
- eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/NetUtilsTest.java
Fixes #3080 
*Refactor NetUtils*
> [ISSUE #3080] Refactor NetUtils

- eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerRunner.java
Fixes #3077 .
The kafka consumer will only consume once, and break the while, which will cause the consumer doesn't consume the data.
> [ISSUE #3077] fix kafka consumer not consume data

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/ThreadUtils.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/AsyncPubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/BroadCastPubClient.java
Fixes #3078
*Refactor ThreadUtils*
> [ISSUE #3078]Refactor ThreadUtils

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
Fixes #3108 
* Remove EventMeshServer duplicate code and polish code style*
> [ISSUE #3108]  Remove EventMeshServer duplicate code and polish code style

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/controller/ClientManageController.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ConfigurationHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfiguration.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcpConnectionHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventMeshRebalanceService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventmeshRebalanceImpl.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/retry/EventMeshTcpRetryer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/boot/EventMeshServerTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfigurationTest.java
Fixes #3120 
*Change the EventMeshTCPConfiguration property from public to private*
> [ISSUE #3120]Change the EventMeshTCPConfiguration property from public to private

- eventmesh-spi/build.gradle
- eventmesh-spi/src/main/java/org/apache/eventmesh/spi/EventMeshExtensionFactory.java
- eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/EventMeshUrlClassLoader.java
- eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/JarExtensionClassLoader.java
- eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/MetaInfExtensionClassLoader.java
- eventmesh-spi/src/test/java/org/apache/eventmesh/spi/EventMeshExtensionFactoryTest.java
Fixes #3116 
-  *Refactor ExtensionClassLoader implement*
-  *add some test cases*
-  *polish code style*
> [ISSUE #3116]Refactor ExtensionClassLoader implement

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/ConfigMonitorService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPMessageHandler.java
Fixes #3072 
*Optimize thread names for thread pools*
> [ISSUE #3072]Optimize thread names for thread pools

- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
Fixes https://github.com/apache/incubator-eventmesh/issues/3086
> [ISSUE #3086] Method invocation may produce 'NullPointerException'

- style/eventmesh-code-style.xml
Fixes #3114 
*[ISSUE #3114]Add eventmesh code style xml for intellij IDEA*
How to use:
> [ISSUE #3114]Add eventmesh code style xml for intellij IDEA

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/retry/HttpRetryer.java
Fixes #3104.
Set fields to `final` in the class `HttpRetryer.java`
> [ISSUE #3104] Set fields to final in HttpRetryer

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #3137.
Fixed typo on 23d line of PULL_REQUEST_TEMPLATE.md 
> [ISSUE #3137] Fixed typo on 23d line of PULL_REQUEST_TEMPLATE.md

- README.md
- README.zh-CN.md
Fixes #3124 
*Fix the incorrect link associated with the Contributing Guideline in the README.md file*
> [ISSUE #3124]Fix the incorrect link associated with the Contributing Guideline in the README.md file

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
Fixes #3103 
- Collapase `Exception` into one branch.
> [ISSUE #3103] collapase Exception

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPClient.java
Fixes #3093.
Removed redundant if statements that were always true on lines 106, 114.  
> [ISSUE #3093] Removed redundant null checks from close()

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/GrpcClientHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/HTTPClientHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RegistryHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TCPClientHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TopicHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/request/CreateTopicRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/request/DeleteGrpcClientRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/request/DeleteHTTPClientRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/request/DeleteTCPClientRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/request/DeleteTopicRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/response/Error.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/response/GetClientResponse.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/response/GetConfigurationResponse.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/response/GetMetricsResponse.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/response/GetRegistryResponse.java
Fixes #3140 
*Modify request and response packages class attributes public to private*
> [ISSUE #3140]Modify request and response packages class attributes public to private

- eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/consumer/PulsarConsumerImpl.java
Fixes #3089 .
Corrected string format message.
- If yes, how is the feature documented? (**not applicable)**
- If a feature is not applicable for documentation, explain why? (**bug fix)**
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation. **(not applicable)**
> [ISSUE #3089] Format string '"Failed to connect pulsar with exception: %"' is malformed

- docs/en/instruction/01-store-with-docker.md
Fixes #3074 
*Polish 01-store-with-docker.md documnet*
> [ISSUE #3074]Polish 01-store-with-docker.md document

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/MetricsHandler.java
Fixes #3017
Specify `Charset` via constant var defined in Constants.java, locating at MetricsHandler.java.
> [ISSUE #3017] Specify `charset` explicitly for conversion between string and byte

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPClient.java
Fixes #3094 .
Remove redundant `if` branch for defensive NPE
Locating at `org.apache.eventmesh.client.tcp.impl.cloudevent.CloudEventTCPClient`
- Line 77: reformat spaces;
- Line 98: remoe `if` branch;
- Line102: remove `if` branch;
> [ISSUE #3094] Discard redundant defensive NPE

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpEventWrapper.java
Fixes #<XXXX>.
Locating at `org.apache.eventmesh.common.protocol.http.HttpEventWrapper`
- Line 87, 104: null ptr check and constant definition reference replacing declaring explicitly
- Line 184, 203, 205: optimize spaces for code style
> [ISSUE #3171] NPE check

- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/ProducerImpl.java
Fixes #3087  .
Added check to avoid NPE.
> [ISSUE #3087] Method invocation 'toString' may produce 'NullPointerException'

- eventmesh-connector-plugin/eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/connector/ConnectorResourceService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/connector/ConnectorResource.java
Fixes #3184
*Refactor ConnectorResource*
> [ISSUE #3184]Refactor ConnectorResource

- docs/en/instruction/03-demo.md
- docs/zh/instruction/03-demo.md
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/EventMeshAsyncSubscribe.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/EventMeshSubscribeBroadcast.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/EventMeshSubscribeReply.java
Fixes #3182
*Rename eventmesh-examples module some classes name.*
> [ISSUE #3182]Rename eventmesh-examples module some classes name

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/codec/Codec.java
> [ISSUE #3183]Refactor Codec

- eventmesh-common/src/test/java/org/apache/eventmesh/common/loadbalance/WeightRandomLoadBalanceSelectorTest.java
Fixes #3169 .
To optimize `Code-Style`, locating at `org.apache.eventmesh.common.loadbalance.WeightRandomLoadBalanceSelectorTest`
> [ISSUE #3169] Replace `print` with `logger`

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/trace/Trace.java
> [ISSUE #3196]Refactor Trace

- eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/JsonUtilsTest.java
Fixes #3167
*Fix JsonUtilsTest NPE*
> [ISSUE #3167] Fix JsonUtilsTest NPE

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/PubClientImpl.java
Fixes #3166 .
Locating at org/apache/eventmesh/runtime/client/impl/PubClientImpl.java
- Line 92: spaces
- Line 95, 96: ignored Exception comment
- Line 191: blank line
- Line 210, 213, 223, 236: discard unnecessary `return`
> [ISSUE #3166] Discard unnecessary `return`

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/MetricsHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcBootstrap.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHttpBootstrap.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTcpBootstrap.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java
- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/test/java/org/apache/eventmesh/trace/zipkin/TracePluginFactoryTest.java
- style/checkStyle.xml
Fixes #3203 
*Remove java modules unused import*
> [ISSUE #3203]Add unused import check rule for code style

- eventmesh-admin/eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/response/TopicResponse.java
Fixes #3197
*Optimize TopicResponse toString method*
> [ISSUE #3197]Optimize TopicResponse toString method

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/registry/Registry.java
Fixes #3129 
*Refactor Registry*
> [ISSUE #3129]Refactor Registry

- eventmesh-common/src/main/java/org/apache/eventmesh/common/loadbalance/LoadBalanceType.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/SubscriptionMode.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/SubscriptionType.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/StatusCode.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/common/ClientRetCode.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/common/ClientType.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/common/EventMeshRetCode.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/common/ProtocolVersion.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/common/RequestCode.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/common/RequestURI.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/OPStatus.java
Fixes #3202 
Enum type should be immutable, we should set fields to final.
Remove unused setters and make fields to final.
> [ISSUE #3202] Remove unused setters in enum type

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/SubStreamHandler.java
Fixes #3208 
*Remove redundant log placeholders*
> [ISSUE #3208]Remove redundant log placeholders

- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/PushConsumerImpl.java
Fixes #3088 .
Added check to avoid NPE.
> [ISSUE #3088] Argument 'msg.getSubject()' might be null

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
Fixes #3164 .
- decrease hash table operation
- clean code
- trade off O(1) cost and code cleaner
Locating at org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
- spaces;
- blank line;
- Line 138: iterator rather than `for`;
- Line 391, 449: remove unnecessary `containsKey()`, trade off `put()` O(1) cost and code cleaner
> [ISSUE #3164] Decrease op of hash table

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/convert/ConvertValue.java
Fixes #3082.
Replaced orElse() with orElseGet() on line 61
> [ISSUE #3082] Replaced orElse() with orElseGet() on line 61

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncSubClient.java
Fixes #3157 
Locating at org/apache/eventmesh/runtime/demo/SyncSubClient.java
- Line 39: Reformat code;
- Line 48: Logging with placeholder;
> [ISSUE #3157] Using placeholder

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncPubClient.java
Fixes #3156 .
Locating at org/apache/eventmesh/runtime/demo/SyncPubClient.java.
- Line 33: Reforamt code;
- Line 42: Logging with placeholder;
> [ISSUE #3156] Method passes a concatenated string to SLF4J's or Log4j2's format string[SyncPubClient]

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/RequestContext.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/PubClientImpl.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/SubClientImpl.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/AsyncSubClient.java
Fixes #3154 #3153  #3152 #3151 .
- Reformat code;
- Logging with placeholder;
> [ISSUE #3154] Logging with placeholder

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/PubClientImpl.java
Fixes #3149
*Method prints the stack trace replace with logger.*
> [ISSUE #3149]Method prints the stack trace replace with logger

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/HTTPClientHandler.java
Fixes #3000 .
string comparision chnage in 3 lines in handle(HttpExchange httpExchange) method in HTTPClientHandler.java
> [ISSUE #3000]Replace str.equals("someOtherString") to ("someOtherString").equals(str) in line 179,182,185

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/convert/ConvertValue.java
- eventmesh-common/src/test/java/org/apache/eventmesh/common/file/WatchFileManagerTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/RequestContext.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/PubClientImpl.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/SubClientImpl.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/AsyncSubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CClientDemo.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncPubClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/SyncSubClient.java
Fixes #3155 .
Locating at eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CClientDemo.java
- Line 54: Replace `==` with `Objects::equals`
- Line 57: Logging with placeholder
> [ISSUE #3155] Method passes a concatenated string to SLF4J's or Log4j2's format string[CClientDemo] 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/EventHandler.java
Fixes #2998.
literal string comparision changed in 4 lines in handle(HttpExchange httpExchange) method in EventHandler.java
> [ISSUE #2998] Method makes literal string comparisons passing the literal as an argument [EventHandler]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/MetricsHandler.java
Fixes #3001.
literal string comparision changed in 2 lines in handle(HttpExchange httpExchange) method in MetricsHandler.java
> [ISSUE #3001]Method makes literal string comparisons passing the literal as an argument [MetricsHandler]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TCPClientHandler.java
Fixes #3003 .
literal string comparision changed in 2 lines in handle(HttpExchange httpExchange) method in TCPClientHandler.java
> [ISSUE #3003] Method makes literal string comparisons passing the literal as an argument [TCPClientHandler]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TopicHandler.java
Fixes #3004 .
literal string comparision changed in 4 lines in handle(HttpExchange httpExchange) method in TopicHandler.java
> [ISSUE #3004] Method makes literal string comparisons passing the literal as an argument [TopicHandler]

- docs/zh/design-document/07-tracing.md
Fixes #3222 
*Translation Distributed Tracing doc (EN->CN)*
> [ISSUE #3222]Translation Distributed Tracing doc (EN->CN)

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/SystemUtils.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/ThreadUtils.java
- eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/SystemUtilsTest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHttpBootstrap.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/common/ServiceState.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumer/SubscriptionManager.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/producer/EventMeshProducer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcpConnectionHandler.java
Fixes #3201 
Optimize remote service related code
> [ISSUE #3201]Optimize remote service related code

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/handler/RedirectClientByPathHandlerTest.java
Fixes #3161 .
Locating at org/apache/eventmesh/runtime/admin/handler/RedirectClientByPathHandlerTest.java
- Line 104, 125: Reformat code tyle;
- Line 114: Replacing primitive type with Boxed type;
> [ISSUE #3161] Specify Boxed type clearly

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshGrpcConfiguration.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfiguration.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/config/EventMeshGrpcClientConfig.java
Fixes #3249 
*Fix lombok compilation warnings*
1.  add @EqualsAndHashCode(callSuper = true)
2. setting useTls = false
> [ISSUE #3249]Fix lombok compilation warnings

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/producer/EventMeshProducer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/producer/ProducerManager.java
Fixes #3242 
*Refactor EventMeshProducer*
> [ISSUE #3242]Refactor EventMeshProducer

- eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/JarExtensionClassLoader.java
Fixes #3269 
*Fix load plugin failure*
> [ISSUE #3269]Fix load plugin failure

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/util/HttpUtils.java
Fixes #3251 
*Refactor sdk-java module HttpUtils*
> [ISSUE #3251]Refactor sdk-java module HttpUtils

- eventmesh-connector-plugin/eventmesh-connector-kafka/build.gradle
- eventmesh-connector-plugin/eventmesh-connector-knative/build.gradle
- eventmesh-connector-plugin/eventmesh-connector-pravega/build.gradle
- eventmesh-connector-plugin/eventmesh-connector-pulsar/build.gradle
- eventmesh-connector-plugin/eventmesh-connector-rabbitmq/build.gradle
- eventmesh-connector-plugin/eventmesh-connector-redis/build.gradle
- eventmesh-connector-plugin/eventmesh-connector-rocketmq/build.gradle
- eventmesh-examples/build.gradle
- eventmesh-metrics-plugin/eventmesh-metrics-api/build.gradle
- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/build.gradle
- eventmesh-protocol-plugin/eventmesh-protocol-api/build.gradle
- eventmesh-registry-plugin/eventmesh-registry-consul/build.gradle
- eventmesh-registry-plugin/eventmesh-registry-etcd/build.gradle
- eventmesh-registry-plugin/eventmesh-registry-nacos/build.gradle
- eventmesh-registry-plugin/eventmesh-registry-zookeeper/build.gradle
- eventmesh-sdk-java/build.gradle
- eventmesh-security-plugin/eventmesh-security-auth-http-basic/build.gradle
- eventmesh-trace-plugin/eventmesh-trace-api/build.gradle
- eventmesh-trace-plugin/eventmesh-trace-jaeger/build.gradle
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/build.gradle
- eventmesh-trace-plugin/eventmesh-trace-zipkin/build.gradle
- eventmesh-webhook/eventmesh-webhook-admin/build.gradle
- eventmesh-webhook/eventmesh-webhook-api/build.gradle
- eventmesh-webhook/eventmesh-webhook-receive/build.gradle
Fixes #3265 
*Remove the version number of the Lombok submodule and inherit the version number from the parent module*
> [ISSUE #3265]Remove lombok version from submodule

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java
Fixes https://github.com/apache/incubator-eventmesh/issues/3085 .
Modifications
updated integer based for loop over a list using For Each loop at line 1538.
> [ISSUE #3085] Method uses integer based for loops to iterate over a List

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/EventMeshMessageProducer.java
made the changes mentioned in issue #3257 .
looking forward for any other changes.
> [#3257] Null Pointer Exception

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/EventMeshMessageProducer.java
> Fix Typo in HTTP Example

- eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/ConsumerImpl.java
- eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerRunner.java
Fixes #3306.
Kafka connectors may raise two exceptions during the polling process.
1. when the consumer polls but is not subscribed to any topic, the thread raises an exception and the consumer shuts down permanently. 
2. RecordDeserializationException, which happens when the consumer fails to deserialize a record. 
For the first problem, I added a check on the subscription of the consumer. 
The second issue is a bit more tricky. It was a bug in initializing the Kafka consumer. The added lines will fix the bug for the following reasons:
kafka client use Class.forName(trimmed, true, Utils.getContextOrKafkaClassLoader()) to get the Class object, and the create the instance, the key point is the classLoader, which is specified by the last param, the implementation of method …
> [ISSUE #3306] Fix the Initialization of Deserializer on Kafka Connector

- eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/config/ConfigurationHolder.java
Fixes #3315 
*Modify ConfigurationHolder class attributes public to private*
> [ISSUE #3315]Modify ConfigurationHolder class attributes public to private

- README.md
see: https://github.com/badges/shields/issues/8671
> Fix workflow badge route

- eventmesh-registry-plugin/eventmesh-registry-nacos/src/main/java/org/apache/eventmesh/registry/nacos/service/NacosRegistryService.java
Fixes #2934.
Removing register info from eventMeshRegisterInfoMap
> [ISSUE #2934] Removing register info from eventMeshRegisterInfoMap

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/connector/ConnectorResource.java
Closes #3235.
Replaced lambda with method reference
> [ISSUE #3235] Replaced lambda with method reference

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java
Fixes #3290 
*Refactor ConsumerManager *
1. remove useless attributes
2. optimize code style
> [ISSUE #3290]Refactor ConsumerManager

- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/admin/RocketMQAdmin.java
- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/admin/command/Command.java
- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/ClientConfiguration.java
- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/RocketMQConsumerImpl.java
- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/RocketMQProducerImpl.java
- eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/test/java/org/apache/eventmesh/connector/rocketmq/config/ClientConfigurationTest.java
Fixes #3312 
*Modify ClientConfiguration class attributes public to private*
> [ISSUE #3312]Modify ClientConfiguration class attributes public to private

- eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/config/ClientConfiguration.java
- eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerImpl.java
- eventmesh-connector-plugin/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/producer/KafkaProducerImpl.java
- eventmesh-connector-plugin/eventmesh-connector-kafka/src/test/java/org/apache/eventmesh/connector/kafka/config/ClientConfigurationTest.java
Fixes #3317 
*Modify kafka module ClientConfiguration class attributes public to private*
> [ISSUE #3317]Modify kafka module ClientConfiguration class attributes public to private

- eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/http/SendMessageBatchV2ProtocolResolver.java
> fixes #3253

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/RequestContext.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java
Fixes #3267 
*Refactor RequestContext*
CountDownLatch replace with CompletableFuture
> [ISSUE #3267] Refactor RequestContext

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/event/ConsumerGroupStateEvent.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/event/ConsumerGroupTopicConfChangeEvent.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java
Fixes #3336 
*Modify consumergroup.event packages class attributes public to private*
> [ISSUE #3336]Modify consumergroup.event packages class attributes public to private

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/codec/Codec.java
Fixes #3343 
*Optimize Codec.Encoder and Codec.Decoder*
> [ISSUE #3343]Optimize Codec.Encoder and Codec.Decoder

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/CommonConfiguration.java
- eventmesh-common/src/test/java/org/apache/eventmesh/common/config/CommonConfigurationTest.java
- eventmesh-common/src/test/resources/configuration.properties
- eventmesh-runtime/build.gradle
- eventmesh-runtime/conf/eventmesh.properties
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/controller/ClientManageController.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/plugin/MQAdminWrapper.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/plugin/MQConsumerWrapper.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/plugin/MQProducerWrapper.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/producer/EventMeshProducer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/producer/EventMeshProducer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/storage/StorageResource.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/admin/controller/ClientManageControllerTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/boot/EventMeshServerTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/configuration/EventMeshGrpcConfigurationTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfigurationTest.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfigurationTest.java
- eventmesh-runtime/src/test/resources/configuration.properties
Fixes #3382
*update eventmesh-runtime module for using storage api*
> [ISSUE #3382]update eventmesh-runtime module for using storage api

- eventmesh-examples/build.gradle
Fixes #3420
*update eventmesh-examples module for using storage api*
> [ISSUE #3420]update eventmesh-examples module for using storage api

- eventmesh-admin/eventmesh-admin-rocketmq/build.gradle
Fixes #3419
*update eventmesh-admin module for using storage api*
> [ISSUE #3419]update eventmesh-admin module for using storage api

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/FileLoad.java
- eventmesh-registry-plugin/eventmesh-registry-api/src/main/java/org/apache/eventmesh/api/registry/RegistryService.java
Fixes #3384 .
*Remove the public modifier from the interface method*
> [ISSUE #3384]Remove the public modifier from the interface method

- eventmesh-metrics-plugin/eventmesh-metrics-api/src/main/java/org/apache/eventmesh/metrics/api/model/HttpSummaryMetrics.java
> [ISSUE #3252] Field may be 'final'[HttpSummaryMetrics]

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/CloudEventProducer.java
Fixes #2972 .
- Does this pull request introduce a new feature? (yes / no) - no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) - not applicable
- If a feature is not applicable for documentation, explain why? - minor issue fix
> [ISSUE #2972] Require null check

- .asf.yaml
> [ISSUE #3423]Notifications redirect to issues@eventmesh.apache.org

- eventmesh-runtime/conf/eventmesh.properties
- eventmesh-webhook/eventmesh-webhook-admin/src/test/resources/eventmesh.properties
- eventmesh-webhook/eventmesh-webhook-receive/build.gradle
- eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookController.java
- eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/WebHookMQProducer.java
- eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/config/ReceiveConfiguration.java
- eventmesh-webhook/eventmesh-webhook-receive/src/test/java/org/apache/eventmesh/webhook/receive/config/ReceiveConfigurationTest.java
- eventmesh-webhook/eventmesh-webhook-receive/src/test/resources/eventmesh.properties
> [ISSUE #3421] update eventmesh-webhook module for using storage api

- build.gradle
- eventmesh-runtime/build.gradle
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/storage/StorageResource.java
Fixes #3434 
*Fix Can't load the StorageResourceService plugin*
> [ISSUE #3434]Fix Can't load the StorageResourceService plugin

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
Fixes #3406 
Improve code readability by removing the nested if loop
merge two nested if loops into one
- If a feature is not applicable for documentation, explain why? code refactor for improved readability
> [ISSUE #3406] Improve code readability

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/SubscriptionItem.java
Fixes #2645 
generated serialVersionID using IDE
> [ISSUE #2645] Class defines a computed serialVersionUID that doesn't equate to the calculated value [SubscriptionItem]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/retry/EventMeshTcpRetryer.java
Fixes #3363 
* Modify DownStreamMsgContext's attributes public to private*
> [ISSUE #3363] Modify DownStreamMsgContext's attributes public to private

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/SessionContext.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/UnSubscribeTask.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/tcp/EventMeshTcpMonitor.java
> [ISSUE #3348]Modify SessionContext's public attributes to private

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java
Fixes #3254 .
Removed static parameter 'threadNum'
> [ISSUE #3254]  removed static  parameter 'threadNum'

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowListenClientByTopicHandler.java
Fixes #3404.
*Use isEmpty() to check whether the collection is empty or not*
> [ISSUE #3404] Use isEmpty() to check whether the collection is empty or not.[ ShowListenClientByTopicHandler]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcpConnectionHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/tcp/EventMeshTcpMonitor.java
Fixes #3341 
*Remove EventMeshTcpConnectionHandler.connections keyword static*
> [ISSUE #3341]Remove EventMeshTcpConnectionHandler.connections keyword static

- eventmesh-connector-plugin/eventmesh-connector-mongodb/build.gradle
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/consumer/MongodbReplicaSetConsumer.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/consumer/MongodbStandaloneConsumer.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/producer/MongodbProducer.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/producer/MongodbReplicaSetProducer.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/java/org/apache/eventmesh/connector/mongodb/producer/MongodbStandaloneProducer.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/resources/META-INF.eventmesh/org.apache.eventmesh.api.connector.ConnectorResourceService
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/resources/META-INF.eventmesh/org.apache.eventmesh.api.consumer.Consumer
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/resources/META-INF.eventmesh/org.apache.eventmesh.api.producer.Producer
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/main/resources/mongodb-client.properties
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/test/java/org/apache/eventmesh/connector/mongodb/MongodbConnectorTest.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/test/java/org/apache/eventmesh/connector/mongodb/MongodbServer.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/test/java/org/apache/eventmesh/connector/mongodb/MongodbServerTest.java
- eventmesh-connector-plugin/eventmesh-connector-mongodb/src/test/resources/mongodb-client.properties
> [ISSUE #2495] Add mongodb connector producer

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/HTTPTrace.java
Fixes #3418 .
Added the requirements at line 39,57,61,83
> [ISSUE #3418] optimizing the code[HTTPTrace.java]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/producer/ProducerTopicManager.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
Fixes #3431 
*Fix ProducerTopicManager throw NPE when runtime module started*
> [ISSUE #3431]Fix ProducerTopicManager throw NPE when runtime module started

- eventmesh-common/src/main/java/org/apache/eventmesh/common/config/FileLoad.java
Fixes #3084 .
1. Specified charset with input-stream-reader API.
2. Used try-with-resources and handled io stream close.
> [ISSUE #3084] Reliance on default encoding[FileLoad]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
Fixes #3412 
Maked Logger a static final constant.
> ISSUE #3412: Make Logger a static final constant

- eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/util/EventMeshClientUtilTest.java
fixed Null pointer exception error.
> fixes #3258

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerGroupManager.java
Fixes #3288 
*Refactor ConsumerGroupManager*
optimize logic
> [ISSUE #3288]Refactor ConsumerGroupManager

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPMessageHandler.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/http/HTTPMetricsServer.java
Fixes #3292 
*Modify EventMeshHTTPServer class attributes public to private and remove transient keyword*
> [ISSUE #3292]Modify EventMeshHTTPServer class attributes public to private

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
Fixes #3413.
Updated the logger to private static final so that one instance of it shared across objects of class.
Updated the loggers to private static final in RemoteSubscribeEventProcessor class
> [Issue #3413]Updated logger to static final

- eventmesh-registry-plugin/eventmesh-registry-consul/src/main/java/org/apache/eventmesh/registry/consul/service/ConsulRegistryService.java
- eventmesh-registry-plugin/eventmesh-registry-consul/src/test/java/ConsulRegistryServiceTest.java
- eventmesh-registry-plugin/eventmesh-registry-etcd/src/main/java/org/apache/eventmesh/registry/etcd/service/EtcdRegistryService.java
- eventmesh-registry-plugin/eventmesh-registry-etcd/src/test/java/org/apache/eventmesh/registry/etcd/service/EtcdRegistryServiceTest.java
- eventmesh-registry-plugin/eventmesh-registry-nacos/src/main/java/org/apache/eventmesh/registry/nacos/service/NacosRegistryService.java
- eventmesh-registry-plugin/eventmesh-registry-nacos/src/test/java/org/apache/eventmesh/registry/nacos/service/NacosRegistryServiceTest.java
- eventmesh-registry-plugin/eventmesh-registry-zookeeper/src/main/java/org/apache/eventmesh/registry/zookeeper/service/ZookeeperRegistryService.java
- eventmesh-registry-plugin/eventmesh-registry-zookeeper/src/test/java/org/apache/eventmesh/registry/zookeeper/service/ZookeeperRegistryServiceTest.java
> [ISSUE #3329]Optimize RegistryService implments init,start,shutdown method

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/producer/EventMeshProducer.java
Fixes #3458 
*Fix EventMeshHttpProducer publish Read timed out*
> [ISSUE #3458]Fix EventMeshHttpProducer publish Read timed out

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
Fixes #3417.
Changed anonymous class to lambda
Replaced anonymous class with lambda at line no. 182 in HeartBeatProcessore.java
- Does this pull request introduces a new feature? (yes / no)no
>  Fixes #3417

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/CloudEventProducer.java
Fixes #2974
Update to remove concatenation and instead use placeholders for logging.
> [ISSUE #2974] logging concat update

- gradle.properties
Fix build on jdk17
Use MaxMetaspaceSize instead of MaxPermSize
> [ISSUE #3496] Fix build on jdk17

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ConsumerService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/HeartbeatService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ProducerService.java
Fixes #3489 
*Add @Override annotation for methods*
> [ISSUE #3489]Add @Override annotation for methods

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Fix deprecated methods, support build of gradle 8
> [ISSUE #3496] Support build of gradle 8

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/HTTPClientHandler.java
Fixes #3008  .
Used try-with-resources to manage resources.
> [Enhancement] Method manually handles closing an auto-closeable resource [HTTPClientHandler] #3008

- eventmesh-storage-plugin/eventmesh-storage-api/src/main/java/org/apache/eventmesh/api/exception/OnExceptionContext.java
- eventmesh-storage-plugin/eventmesh-storage-api/src/main/java/org/apache/eventmesh/api/exception/StorageRuntimeException.java
- eventmesh-storage-plugin/eventmesh-storage-kafka/src/main/java/org/apache/eventmesh/storage/kafka/consumer/ConsumerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-kafka/src/main/java/org/apache/eventmesh/storage/kafka/producer/ProducerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-mongodb/src/main/java/org/apache/eventmesh/storage/mongodb/exception/MongodbStorageException.java
- eventmesh-storage-plugin/eventmesh-storage-pravega/src/main/java/org/apache/eventmesh/storage/pravega/PravegaProducerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-pravega/src/main/java/org/apache/eventmesh/storage/pravega/exception/PravegaStorageException.java
- eventmesh-storage-plugin/eventmesh-storage-pulsar/src/main/java/org/apache/eventmesh/storage/pulsar/client/PulsarClientWrapper.java
- eventmesh-storage-plugin/eventmesh-storage-pulsar/src/main/java/org/apache/eventmesh/storage/pulsar/consumer/PulsarConsumerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-pulsar/src/main/java/org/apache/eventmesh/storage/pulsar/producer/AbstractProducer.java
- eventmesh-storage-plugin/eventmesh-storage-pulsar/src/main/java/org/apache/eventmesh/storage/pulsar/producer/PulsarProducerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-rabbitmq/src/main/java/org/apache/eventmesh/storage/rabbitmq/exception/RabbitmqStorageException.java
- eventmesh-storage-plugin/eventmesh-storage-rabbitmq/src/main/java/org/apache/eventmesh/storage/rabbitmq/producer/RabbitmqProducer.java
- eventmesh-storage-plugin/eventmesh-storage-redis/src/main/java/org/apache/eventmesh/storage/redis/client/RedissonClient.java
- eventmesh-storage-plugin/eventmesh-storage-redis/src/main/java/org/apache/eventmesh/storage/redis/producer/RedisProducer.java
- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/consumer/PushConsumerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/exception/RMQMessageFormatException.java
- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/exception/RMQTimeoutException.java
- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/producer/AbstractProducer.java
- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/producer/ProducerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/test/java/org/apache/eventmesh/storage/rocketmq/producer/ProducerImplTest.java
- eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/producer/StandaloneProducer.java
Fixes #3545 
*Rename StorageConnectorRuntimeException to StorageRuntimeException*
> [ISSUE #3545]Rename StorageConnectorRuntimeException to StorageRuntimeException

- eventmesh-storage-plugin/eventmesh-storage-kafka/src/main/java/org/apache/eventmesh/storage/kafka/producer/ProducerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-knative/src/main/java/org/apache/eventmesh/storage/knative/producer/ProducerImpl.java
hot fix for master branch checkstyle broken
> hot fix for checkstyle import

- eventmesh-common/src/main/java/org/apache/eventmesh/common/EventMeshMessage.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/enums/EventMeshProtocolType.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/CloudEventsAsyncSubscribe.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/CloudEventsSubscribeReply.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/EventMeshAsyncSubscribe.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/EventMeshSubscribeBroadcast.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/EventMeshSubscribeReply.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowExpressAsyncSubscribe.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowOrderAsyncSubscribe.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/WorkflowPaymentAsyncSubscribe.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumer.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/CloudEventProducer.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/EventMeshGrpcProducer.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/EventMeshMessageProducer.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/GrpcProducer.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/util/EventMeshClientUtil.java
- eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/consumer/EventMeshGrpcConsumerTest.java
- eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/producer/EventMeshGrpcProducerTest.java
- eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/producer/EventMeshMessageProducerTest.java
- eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/util/EventMeshClientUtilTest.java
Fixes #3339 
*Refactor EventMeshGrpcProducer*
> [ISSUE #3339]Refactor EventMeshGrpcProducer

- .github/workflows/ci.yml
Fixes #3561 . 
See #3561 .
See #3561 .
> [ISSUE #3561] Speed up CI

- build.gradle
- tools/dependency-check/known-dependencies.txt
Bump zookeeper from 3.4.6 to 3.7.1, that's a regular dependency update
> Bump zookeeper from 3.4.6 to 3.7.1

- .github/dependabot.yml
- .github/workflows/ci.yml
Fixes #3559 
See #3559 
See #3559 
> [ISSUE #3559] Config dependadot

- eventmesh-storage-plugin/eventmesh-storage-redis/src/main/java/org/apache/eventmesh/storage/redis/client/RedissonClient.java
- eventmesh-storage-plugin/eventmesh-storage-redis/src/main/java/org/apache/eventmesh/storage/redis/cloudevent/CloudEventCodec.java
Fixes https://github.com/apache/eventmesh/issues/3586
Refactor CloudEventCodec singleton instantiation
> [ISSUE #3586] Refactor CloudEventCodec singleton instantiation

- eventmesh-storage-plugin/eventmesh-storage-rabbitmq/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.api.storage.StorageResourceService
Fixes #3597 
*Fix load RabbitmqStorageResourceService failure*
> [ISSUE #3597]Fix load RabbitmqStorageResourceService failure

- eventmesh-storage-plugin/eventmesh-storage-knative/src/main/java/org/apache/eventmesh/storage/knative/storage/StorageResourceServiceKnativeImpl.java
Fixes #3595 
*Fix Throw StorageResourceServiceKnativeImpl StorageResourceServiceKnativeImpl when start runtime with start.sh*
> [ISSUE #3595]Fix throw StorageResourceServiceKnativeImpl StorageResourceServiceKnativeImpl when start runtime with start.sh

- eventmesh-storage-plugin/eventmesh-storage-pulsar/src/main/java/org/apache/eventmesh/storage/pulsar/client/PulsarClientWrapper.java
> [ISSUE #3484] Did code optimization in PulsarClientWrapper. Closes #3484

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
Fixes #3401.
*Remove CompleteHandler<HttpCommand> with lambda*
*Code optimization with lambda*
*Replaced CompleteHandler<HttpCommand> with lambda.*
> Fix patch 3401

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
Fixes #3388.
*The code processing logic here is the same. If the same logic is truly needed for both instances, then in an if chain they should be combined, or for a switch, one should fall through to the other.*
*Join two if statements that perform same code logic.*
> Refactor: No changes to code processing logic

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/HttpTinyClientTest.java
Fixes #3518 
I've swapped the actual and expected values in the lines 47,48,63,64,75,76.
No
Not Applicable
This is just an enhancement. Not a feature of itself.
> [ISSUE #3518]Swap these 2 arguments so they are in the correct order: expected value, actual value.[HttpTinyClientTest]

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/PubClientImpl.java
Fixes #3517 
I have swapped the actual and expected values in the lines 137-155.
No
Not Applicable
> [ISSUE #3517]Swap these 2 arguments so they are in the correct order: expected value, actual value.[PubClientImpl]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
Fixes #3403 .
*Substituted anonymous inner class with lambda expression in SubscribeProcessor.java*
>  [Enhancement] Make this anonymous inner class a lambda[SubscribeProcessor] #3403 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/EventHandler.java
Fixes #3398 .
*Code optimization on EventHandler.java*
*Returning HashMap instead null in line 83, line 108 removed out.close()*
- If yes, how is the feature documented? (not applicable )
> [ISSUE #3398] Do some code optimization.[EventHandler] 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/grpc/EventMeshGrpcMonitor.java
Fixes #3645 
Included "final" in the lines 41, 42, 44, 46. Removed curly braces at line 61.
> [ISSUE #3645]Some optimization of the code.[EventMeshGrpcMonitor]

- eventmesh-storage-plugin/eventmesh-storage-pulsar/src/test/java/org/apache/eventmesh/storage/pulsar/config/ClientConfigurationTest.java
Fixes #3512 
Swapped actual and expected values at lines 46-48.
> [ISSUE #3512]Swap these 2 arguments so they are in the correct order: expected value, actual value.[ClientConfigurationTest]

- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/test/java/org/apache/eventmesh/storage/rocketmq/utils/BeanUtilsTest.java
Fixes #3508 .
*Do some code optimization*
> [ISSUE #3508] Do some code optimization [BeanUtilsTest.java]

- eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/tcp/TcpMessageProtocolResolver.java
Fixes #3648 
Included "import java.util.Objects;" at line 28. Included "Object.requireNonNull()" at line 80.
> [ISSUE #3648]A "NullPointerException" could be thrown; "resolveFormat()" can return null

- eventmesh-registry-plugin/eventmesh-registry-nacos/src/main/java/org/apache/eventmesh/registry/nacos/service/NacosRegistryService.java
Fixes #3504 
Returns empty map/list instead of null in lines 197 and 258.
> [ISSUE #3504]Return an empty map/collection instead of null.[NacosRegistryService] 

- eventmesh-storage-plugin/eventmesh-storage-rabbitmq/src/test/java/org/apache/eventmesh/storage/rabbitmq/cloudevent/RabbitmqCloudEventTest.java
Fixes #3510 
Swapped actual and expected values in lines 52,62,68.
> [ISSUE #3510]Swap these 2 arguments so they are in the correct order: expected value, actual value.[RabbitmqCloudEventTest]

- eventmesh-storage-plugin/eventmesh-storage-kafka/src/test/java/org/apache/eventmesh/storage/kafka/config/ClientConfigurationTest.java
Fixes #3514.
*Swapped the expected and actual values in assertEquals*
*The expected and actual values were swapped in the assertions, fixed it by swapping them so that the assertions accurately check the configuration values*
*Swapped the actual and expected value*
> [ISSUE #3514] Swap these 2 arguments so they are in the correct order: expected value, actual value.[ClientConfigurationTest]

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/configuration/EventMeshTCPConfigurationTest.java
Fixes #3519 
Swapped actual and expected values in the lines 44-68.
> [ISSUE #3519]Swap these 2 arguments so they are in the correct order: expected value, actual value.[EventMeshTCPConfigurationTest]

- eventmesh-storage-plugin/eventmesh-storage-redis/src/test/java/org/apache/eventmesh/storage/redis/config/RedisPropertiesTest.java
Fixes #3509 
Swapped actual and expected values in the lines 37-39 and 45.
No
Not Applicable
> [ISSUE #3509]Swap these 2 arguments so they are in the correct order: expected value, actual value.[RedisPropertiesTest]

- eventmesh-storage-plugin/eventmesh-storage-pravega/src/test/java/org/apache/eventmesh/storage/pravega/config/PravegaStorageConfigTest.java
Fixes #3513 .
Motivation
Explain why you want to make the changes and what problem you're trying to solve.
I am contributing for the first time, it will help to keep me motivated to learn and help the community
Modifications
Describe the modifications you've done.
Swapped actual and expected values in the line 50,51,53,54,56-58.
Documentation
Does this pull request introduce a new feature? no
If yes, how is the feature documented? not applicable
> [ISSUE #3513] Swap these 2 arguments so they are in the correct order: expected value, actual value.[PravegaStorageConfigTest]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java
Fixes #2980
Enhancement Request
Substituted Map.get & Map.put combined logic with Map.computeIfAbsent in UnSubscribeProcessor.java
- If a feature is not applicable for documentation, explain why? - code refactor
> [ISSUE #2980] Can be replaced with single 'Map.computeIfAbsent' method call[UnSubscribeProcessor]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/GoodbyeTask.java
Fixes #3462 .
*Set anonymous internal class Runnable to lambda, deleted one comment.*
> [ISSUE #3462] Do some code optimization[GoodbyeTask]  #3462 

- eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/CloudEventsProtocolAdaptor.java
Fixes #3649 .
*Added Objects.requireNonNull() in line 121 and 130 as well as the import java.util.Objects.*
- If yes, how is the feature documented? (not applicable )
> [ISSUE #3649] Method invocation may produce 'NullPointerException'.[CloudEventsProtocolAdaptor]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RegistryHandler.java
Fixes #3002.
in string comparison the literal was the second arg, getting compared against an object, possibility of NPE
flipped the order of string, using literal to call the .equals
> [ISSUE #3002] flipped the string comparison 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
Fixes #2979.
we were doing a get, then a null check, if null then we were creating an empty list and inserting that in a map.
replaced 'get + null check + creating empty list' with computeIfAbsent
> [ISSUE #2979] replaced 'get + null check + creating empty list' 

- .gitignore
Fixes #3699 
*Add gitignore for github codespaces open eventmesh*
> [ISSUE #3699]Add gitignore for github codespaces open eventmesh

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java
Fixes #3730 
Reduced the total number of continue statements used in lines 125, 152
> [ISSUE #3730]Reduce the total number of continue statements in this loop.[HeartBeatProcessor]

- eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/PropertiesUtilsTest.java
Fixes #3718 
Swapped actual and expected values at lines 54, 55.
> [ISSUE #3718]Swap these 2 arguments so they are in the correct order: expected value, actual value.[PropertiesUtilsTest]

- eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/protocol/GithubProtocol.java
Fixes #3720 
change to use Boolean.FALSE to avoid NullPointException
> use a primitive boolean expression in GithubProtocol

- eventmesh-spi/src/main/java/org/apache/eventmesh/spi/loader/JarExtensionClassLoader.java
Fixes #3726.
Optimize code.
Replace lambda with method reference
> [ISSUE #3726]Lambda can be replaced with method reference[JarExtensionClassLoader]

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/selector/ServiceInstance.java
Fixes #2977.
serialVersionUID was invalid
generated a new serialVersionUID
> [ISSUE #2977] generated a new serialVersionUID 

- eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/NetUtilsTest.java
Fixes #3719 
Swapped expected and actual values.
> [ISSUE #3719]Swap these 2 arguments so they are in the correct order: expected value, actual value.[NetUtilsTest]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/BatchPublishMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/HeartbeatProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/ReplyMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/RequestMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/SendAsyncMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ProducerService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/AdminShutdownProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcpMessageDispatcher.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HelloTask.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageAckTask.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/RecommendTask.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/UnSubscribeTask.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/Utils.java
Fixes #3729.
Aoid `Invoke method(s) only conditionally`.
Make `Logger` field `final`.
Reuse variable `remoteAddr`.
Add `final` to `Logger`.
> [ISSUE #3729]Do some code optimization[AdminShutdownProcessor]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HandlerService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/RemoteUnSubscribeEventProcessor.java
Fixes #3731
Fixes #3732
Aoid `Invoke method(s) only conditionally` and reuse variable.
Remove variable `requestIp` and reuse `remoteAddr`.
> [ISSUE #3731]Invoke method(s) only conditionally.

- README.zh-CN.md
Fixes #3588 
*Optimize README.zh-CN.md*
> [ISSUE #3588]Optimize README.zh-CN.md

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java
Fixes #3733.
Aoid `Invoke method(s) only conditionally` and reuse variable.
Reuse variable `remoteAddr`.
> [ISSUE #3733] Invoke method(s) only conditionally.[SendAsyncMessageProcessor]

- eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/http/SendMessageBatchV2ProtocolResolver.java
Fixes #3652.
*there were duplicate code in the file, refactored the duplicate code to a method and refactored further to make the code more readable*
*refactored the code, extracted a new method and used switch to make code more readable*
> [ISSUE #3652] refactored the code, extracted a new method and used switch

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/registry/Registry.java
Fixes #3414.
Use method reference. Adjust syschronized scope
> [ISSUE #3414]Replace this lambda with method reference 'Registry::registryBuilder'. 

- eventmesh-webhook/eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/Manufacturer.java
used putIfAbsent()  and used cconcurrentHashMap.
> [ISSUE #3481] Replace this "Map.containsKey()" with a call to "Map.computeIfAbsent()". 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/Utils.java
- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/util/EventMeshClientUtil.java
Fixes #3465.
- Does this pull request introduce a new feature? / no
> [ISSUE #3465]Do some code optimization[EventMeshUtil]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AbstractHTTPPushRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPClientPool.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPMessageHandler.java
> [ISSUE #3461]Do some code optimization[HTTPMessageHandler]

- eventmesh-storage-plugin/eventmesh-storage-pravega/src/main/java/org/apache/eventmesh/storage/pravega/client/SubscribeTask.java
Fixes #3502 
At line 50,
a. Extracted common part
b. Reduced the total number of continue statements in this loop to use at most one.
> [ISSUE #3502]Some optimization of the code.[SubscribeTask]

- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/cloudevent/impl/RocketMQMessageWriter.java
> [ISSUE #3722]Do some code optimization[RocketMQMessageWriter]

- eventmesh-storage-plugin/eventmesh-storage-rabbitmq/src/main/java/org/apache/eventmesh/storage/rabbitmq/cloudevent/RabbitmqCloudEventWriter.java
> [ISSUE #3723]Not annotated parameter overrides @ParametersAreNonnullByDefault parameter[RabbitmqCloudEventWriter]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java
Fixes #<3400>.
Do some code optimization
a. Remove invalid code.
b. Use Objects.requireNonNull() to avoid NPE.
c. Replace "Collections.EMPTY_LIST" by "Collections.emptyList()".
> [ISSUE #3400] Do some code optimization.[WebhookPushRequest] 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshCloudEventWriter.java
Remove reduntand initializer
add @Nonnull
> [ISSUE #3646] Some optimization of the code.[EventMeshCloudEventWriter]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageV2Processor.java
Fixes #3392.
a.changed from public to private
b.added Objects.requireNonNull method to object.
> [ISSUE #3392] Do some code optimization.[BatchSendMessageV2Processor]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java
Fixes #3391.
a.changed from public to private 
b.removed commented code.
> [ISSUE #3391] Do some code optimization.[BatchSendMessageProcessor]

- eventmesh-storage-plugin/eventmesh-storage-kafka/src/main/java/org/apache/eventmesh/storage/kafka/consumer/KafkaConsumerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-knative/src/main/java/org/apache/eventmesh/storage/knative/consumer/KnativeConsumerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-pravega/src/main/java/org/apache/eventmesh/storage/pravega/PravegaConsumerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-pulsar/src/main/java/org/apache/eventmesh/storage/pulsar/consumer/PulsarConsumerImpl.java
- eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/consumer/StandaloneConsumerAdaptor.java
Fixes #3724.
Process NPE and Optimize variable definition.
> [ISSUE #3724]Do some code optimization[PulsarConsumerImpl]

- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/java/org/apache/eventmesh/trace/jaeger/JaegerTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/PinpointTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/ZipkinTraceService.java
Fixes #3721.
Aoid `Not annotated parameter overrides @ParametersAreNonnullByDefault`
Correct a wrong variable in anonymous inner class in `ZipkinTraceService#inject()`.
> [ISSUE #3721]Do some code optimization[JaegerTraceService]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshCloudEventWriter.java
- eventmesh-storage-plugin/eventmesh-storage-knative/src/main/java/org/apache/eventmesh/storage/knative/cloudevent/impl/KnativeMessageWriter.java
- eventmesh-storage-plugin/eventmesh-storage-pravega/src/main/java/org/apache/eventmesh/storage/pravega/client/PravegaCloudEventWriter.java
Fixes #3725.
Aoid `Not annotated parameter overrides @ParametersAreNonnullByDefault parameter`.
Add `@Nonnull` or `@Nullable`.
> [ISSUE #3725]Not annotated parameter overrides @ParametersAreNonnullByDefault parameter[PravegaCloudEventWriter]

- eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/http/SendMessageBatchV2ProtocolResolver.java
- eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/http/SendMessageRequestProtocolResolver.java
- eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/http/SendMessageBatchV2ProtocolResolver.java
- eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/http/SendMessageRequestProtocolResolver.java
Fixes #3473.
Reuse code logic and use some api provided officially.
> [ISSUE #3473]The code processing logic is the same in both places.

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/ClientAckContext.java
Fixes #3393 
Motivation
Explain why you want to make the changes and what problem you're trying to solve.
I am interested in open source, it will help to keep me motivated to learn and help the community
Modifications
Describe the modifications you've done.
Did some code optimization in line 49,58
Documentation
Does this pull request introduce a new feature? no
If yes, how is the feature documented? not applicable
> [ISSUE #3393] Do some code optimization.[ClientAckContext]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ConfigurationHandler.java
> [ISSUE #3013] Updated ConfigurationHandler.java 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/HTTPClientHandler.java
> [ISSUE #3016] Found reliance on default encoding: String.getBytes() [HTTPClientHandler]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RegistryHandler.java
> [ISSUE #3018] Found reliance on default encoding: String.getBytes() [RegistryHandler]

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java
> [ISSUE #3466] Save and re-use this "Random"

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/BatchPublishMessageProcessor.java
Fixes #3390 .
imported the Objects class and
added Objects.requireNonNull().
> [ISSUE #3390] "getExtension()" can return null.[BatchPublishMessageProcessor]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java
Fixes #3728 
Replaced "Map.get()" and condition with a call to "Map.computeIfAbsent()" at line 92.
> [ISSUE #3728] Replace this "Map.get()" and condition with a call to "Map.computeIfAbsent()". [ConsumerManager]

- eventmesh-registry-plugin/eventmesh-registry-etcd/src/main/java/org/apache/eventmesh/registry/etcd/service/EtcdRegistryService.java
Fixes #3505 .
wanted to contribute back to community
optimization.
> [ISSUE #3505] Do some code optimization[EtcdRegistryService]

- eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java
Fixes #3654.
*New methods are created getUserAgent, getPackageMsg, getEventMeshMessage.*
*the code was reusable so extracted as method.*
> [ISSUE #3654] Code reuse is extracted as a method.[EventMeshTestUtils]

- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/utils/CloudEventUtils.java
Fixes #3829 
Replaced `replaceAll()` with `replace()` at line 88
Removed `e.printStackTrace()` at line 128
> [ISSUE #3829]Do some code optimization.[CloudEventUtils]

- eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/WebhookFileListener.java
Fixes #3821 .
changed to concatenation so that saves time.
> [ISSUE#3821][Enhancement] Change this hard-coding.[WebhookFileListener]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/constants/EventMeshConstants.java
Fixes #3389 .
imported the StandardCharsets class and 
changed to StandardCharsets.UTF_8
> [ISSUE #3389] Replace Charset.forName() call with StandardCharsets.UTF_8

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HelloTask.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/RecommendTask.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/UnSubscribeTask.java
> [ISSUE #3843]Simplify code in some subclasses of AbstractTask and related class

- eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/admin/StandaloneAdmin.java
Fixes #3823 .
code optimisation.
stored the calculated value in variable then passed in to the object .
> [ISSUE #3823]Math operands should be cast before assignment.

- eventmesh-storage-plugin/eventmesh-storage-api/src/main/java/org/apache/eventmesh/api/AsyncConsumeContext.java
- eventmesh-storage-plugin/eventmesh-storage-api/src/main/java/org/apache/eventmesh/api/EventMeshAsyncConsumeContext.java
- eventmesh-storage-plugin/eventmesh-storage-kafka/src/main/java/org/apache/eventmesh/storage/kafka/consumer/KafkaConsumerRunner.java
- eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/task/Subscribe.java
Fixes #3846.
See "Enhancement Request" in [issue](https://github.com/apache/eventmesh/issues/3846#issue-1688747051)
See "Describe the solution you'd like" in [issue](https://github.com/apache/eventmesh/issues/3846#issue-1688747051)
> [ISSUE #3846]Remove the redundant method declaration in hierarchy.

- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/test/java/org/apache/eventmesh/storage/rocketmq/utils/BeanUtilsTest.java
Fixes #3831 
Swapped values in lines 92,109.
> [ISSUE #3831]Change this assertion to not compare two literals

- eventmesh-common/src/main/java/org/apache/eventmesh/common/EventMeshThreadFactory.java
Fixes #3835 
Added `final` at line 31, and `@Nonnull` annotation at line 65.
> [ISSUE #3835]Add final and @Nonnull[EventMeshThreadFactory]

- eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/tcp/TcpMessageProtocolResolver.java
- eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver/tcp/TcpMessageProtocolResolver.java
Fixes #3852.
See detail in issue "Enhancement Request"
See detail in issue "Describe the solution you'd like".
> [ISSUE #3852]Replace some logic with existing APIs. Merge some logic.

- eventmesh-storage-plugin/eventmesh-storage-kafka/src/main/java/org/apache/eventmesh/storage/kafka/producer/ProducerImpl.java
Fixes #3832 
Added `final` to line 47. 
Added `Objects.requireNonNull()` to avoid NPE at line 110
> [ISSUE #3832]Do some code optimization.[storage ProducerImpl]

- eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java
Fixes #3466 
Save and re-use this "Random"
> [ISSUE #3466]Save and re-use this "Random"

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/TCPClientHandler.java
Fixes #3011 .
This method allocates and uses an auto closeable resource. However, it manually closes the resource in a finally block. While this is correct management, it doesn't rely on the idiomatic way available to JDK 7 and above, allows for possible subtle problems, and complicates the reading of code by developers
use of try-with-resources.
> [ISSUE #3011] Method manually handles closing an auto-closeable resource [TCPClientHandler]

- eventmesh-storage-plugin/eventmesh-storage-rocketmq/src/main/java/org/apache/eventmesh/storage/rocketmq/utils/CloudEventUtils.java
Fixes #3868.
See "Enhancement Request" in [issue](https://github.com/apache/eventmesh/issues/3868#issue-1696862806).
See "Describe the solution you'd like" in [issue](https://github.com/apache/eventmesh/issues/3868#issue-1696862806).
> [ISSUE #3868]Method buildCloudEventPropertyKey() in CloudEventUtils return a param immediately 

- eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver/HttpRequestProtocolResolver.java
Fixes #3472 
Imported `java.util.Objects`
Used `Objects.requireNonNull()` at line 95
> [ISSUE #3472]Do some code optimization[HttpProtocolAdaptor]

- eventmesh-workflow-go/README.md
> remove eventmesh-workflow-go folder

- eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/Application.java
- eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/ConnectorWorker.java
- eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/SinkWorker.java
- eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/SourceWorker.java
- eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/api/config/PubSubConfig.java
- eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/api/connector/Connector.java
- eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/util/ConfigUtil.java
- eventmesh-connectors/sink-connector-rocketmq/src/main/java/org/apache/eventmesh/sink/connector/rocketmq/config/ConnectorConfig.java
- eventmesh-connectors/sink-connector-rocketmq/src/main/resources/config.yml
- eventmesh-connectors/source-connector-rocketmq/src/main/java/org/apache/eventmesh/source/connector/rocketmq/config/ConnectorConfig.java
- eventmesh-connectors/source-connector-rocketmq/src/main/resources/config.yml
Fixes #3985 
- *Fix cannot resolve method getSubystem in PubSubConfig*
- *Fix code style*
> [ISSUE #3985]Fix cannot resolve method getSubystem in PubSubConfig and code style

- eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/http/util/HttpUtilsTest.java
Fixes #3948 
*Add HttpUtils test case*
> [ISSUE #3948]Add HttpUtils test case

- eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/common/MessageUtilsTest.java
Fixes #3950 
*Add MessageUtils unit test case*
> [ISSUE #3950]Add MessageUtils unit test case

- eventmesh-storage-plugin/eventmesh-storage-pravega/src/main/java/org/apache/eventmesh/storage/pravega/client/PravegaClient.java
> [ISSUE #3503] Replace this call to "replaceAll()" by a call to the "replace()" method.[PravegaClient]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/trace/TraceUtils.java
> [ISSUE #3964] Catch Exception instead of Throwable.

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/HttpRequestProcessor.java
> [ISSUE #3908] Code optimization [HttpRequestProcessor]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RejectClientBySubSystemHandler.java
> [ISSUE #3905] Method needlessly defines parameter with concrete classes[RejectClientBySubSystemHandler]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/message/PushMessageResponseBody.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/message/ReplyMessageResponseBody.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/message/SendMessageBatchResponseBody.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/message/SendMessageBatchV2ResponseBody.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/message/SendMessageResponseBody.java
Fixes #3931 
*Optimize Body extends class toString method*
> [ISSUE #3931]Optimize Body extends class toString method

- README.zh-CN.md
Fixes #3942 
*Update README.zh-CN.md*
> [ISSUE #3942]Update README.zh-CN.md

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshServer.java
Fixes #3952 
*Optimize EventMeshServer#EventMeshServer method*
> [ISSUE #3952]Optimize EventMeshServer#EventMeshServer method

- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SinkWorker.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
Fixes #4038 
*Optimize eventmesh-openconnect log print*
> [ISSUE #4038]Optimize eventmesh-openconnect log print

- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SinkWorker.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
> [ISSUE #4044] Remove duplicate init connector operation in worker

- eventmesh-storage-plugin/eventmesh-storage-mongodb/src/main/java/org/apache/eventmesh/storage/mongodb/utils/MongodbCloudEventUtil.java
- eventmesh-storage-plugin/eventmesh-storage-rabbitmq/src/main/java/org/apache/eventmesh/storage/rabbitmq/utils/ByteArrayUtils.java
> [ISSUE #4031] Specifies the default character set

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
> [ISSUE #4111] Made an explicit  null check on the map

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/IPUtils.java
Fixes #3901 .
*The method doesn't need to be defined with concrete classes*
*Replaced List with collection*
> [ISSUE #3901] Method needlessly defines parameter with concrete classes [IPUtils]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/utils/HttpExchangeUtils.java
Fixes #4017 .
*Using try-with-resources to manage resources*
> [ISSUE #4017] Resources may not be released.

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java
[ISSUE #4141] Fix the GRPC subscribe error
> [ISSUE #4141] Fix the GRPC subscribe error

- eventmesh-connectors/eventmesh-connector-openfunction/build.gradle
- eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/client/CallbackServiceGrpc.java
> [ISSUE #4150]Fix ci compile error for JDK 11 in eventmesh-connector-openfunction

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/PushContext.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/EventMeshTcpSendResult.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/UpStreamMsgContext.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java
Fixes #4107 #4106 #4104 #4103.
the changes are pretty straightforward, we can make the fields final
made fields final 
also, some cleanup suggested by IDE
> [ISSUE #4107] made fields final 

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java
> [ISSUE #4109 ] Code Optimization.[ClientGroupWrapper]

- build.gradle
- eventmesh-common/build.gradle
- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/JsonUtils.java
- eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/JsonUtilsTest.java
- tools/dependency-check/known-dependencies.txt
Fixes #4161 
*Fix JsonUtils not support serialize java.time.LocalDate*
> [ISSUE #4161]Fix JsonUtils not support serialize java.time.LocalDate

- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/controller/SubController.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/AbstractPublishBatchCloudEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/AbstractPublishCloudEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/BatchPublishCloudEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/HeartbeatProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/PublishCloudEventsProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/ReplyMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/RequestCloudEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/SubscribeProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/SubscribeStreamProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/UnsubscribeProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ConsumerService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/HeartbeatService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/PublisherService.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java
- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/SubStreamHandler.java
- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/util/EventMeshCloudEventBuilder.java
- eventmesh-sdks/eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/grpc/util/EventMeshCloudEventBuilderTest.java
Fixes #4164
- Fix EventMeshGrpcConsumer client subscribe topic error
- Rename  some method of ServiceUtils class 
> [ISSUE #4164]Fix EventMeshGrpcConsumer client subscribe topic error

- eventmesh-connectors/eventmesh-connector-openfunction/gradle.properties
- eventmesh-connectors/eventmesh-connector-rocketmq/gradle.properties
- gradle.properties
> update release version

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpEventWrapper.java
Fixes #3836.
Add proper access modifiers in HttpEventWrapper
* Make headerMap and sysHeaderMap **transient**
* Make httpMethod, httpVersion, reqTime, resTime private
> [ISSUE #3836] Add proper access modifers for HttpEventWrapper

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java
Fixes #4197.
Use switch case instead of if-else statement in [https://github.com/apache/eventmesh/blob/master/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java](url)
at lines 204-208,240-247,251-258
*Explaination*
It is more efficient to use switch than if-else in making judgments for Enum types.
Optimised code to use switch case instead of if-else statement
- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)
> [ISSUE #4197] Use switch instead of if else

- eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/config/OpenFunctionServerConfig.java
- eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/sink/config/OpenFunctionSinkConfig.java
- eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/source/config/OpenFunctionSourceConfig.java
- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/config/RocketMQServerConfig.java
- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/sink/config/RocketMQSinkConfig.java
- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/source/config/RocketMQSourceConfig.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/config/SinkConfig.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/config/SourceConfig.java
- eventmesh-trace-plugin/eventmesh-trace-api/src/main/java/org/apache/eventmesh/trace/api/AbstractTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-jaeger/src/main/java/org/apache/eventmesh/trace/jaeger/JaegerTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-pinpoint/src/main/java/org/apache/eventmesh/trace/pinpoint/PinpointTraceService.java
- eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin/ZipkinTraceService.java
Fixes #4213 
- Resolve the compilation warning for the lombok annotation @Data
> [ISSUE#4213]Resolve the compilation warning for the lombok annotation @Data

- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/EventMeshMessageProducer.java
Fixes #4084 
Removed stack trace at line 119
> [ISSUE #4084]Method prints the stack trace to the console[EventMeshMessageProducer]

- eventmesh-webhook/eventmesh-webhook-receive/src/main/java/org/apache/eventmesh/webhook/receive/storage/HookConfigOperationManager.java
Fixes #4227.
Redundantly throwed exception removed.
> [ISSUE #4227] Use switch...case... instead of if...else... for HookConfigOperationManager

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/producer/ProducerManager.java
Fixes #4018 
Added `final` in lines 31,33.
Removed the redundant `null` initialization at lines 48 and 69.
> [ISSUE #4018] Code optimization.[ProducerManager]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java
Fixes #4200 .
his changes resolves #4200  by using short-circuit-logic & add `Objects.requireNonNull()`
`eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java` line 89, 92, 95, 147
- If yes, how is the feature documented? -
- If a feature is not applicable for documentation, explain why? -
> [ISSUE #4200]Do some code optimization.[ServiceUtils]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/Subscription.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java
- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java
- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPSubClient.java
Fixes #4021.
this changes resolves #4021 by replace LinkedList with ArrayList.
`eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/Subscription.java` line 27.
`eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshGrpcServer.java` line 279
`eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java` line 213
`eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/cloudevent/CloudEventTCPSubClient.java` line 59
`eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPSubClient.java` line 51
FILE DOESN'T EXIST:
`eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/prot …
> [ISSUE #4021] Replace LinkedList by ArrayList

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/HttpResponseUtils.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/ValueComparator.java
Fixes #4202.
- add 'serialVersionUID'.
- Extraction as a method.
> [ISSUE #4202] Do some code optimization.[util]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/EventMeshHTTPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/CreateTopicProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/DeleteTopicProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/QuerySubscriptionProcessor.java
Fixes #4245 .
fix start failed
fix start failed
> [ISSUE #4245] Fix start eventmesh failed.

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/AssertUtils.java
- eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/AssertUtilsTest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java
Fixes https://github.com/apache/eventmesh/issues/4252
Minor refactoring on `AssertUtils ` class
> [ISSUE #4252] Minor refactoring for AssertUtils class

- eventmesh-registry-plugin/eventmesh-registry-nacos/src/main/java/org/apache/eventmesh/registry/nacos/config/NacosRegistryConfiguration.java
- eventmesh-registry-plugin/eventmesh-registry-nacos/src/main/java/org/apache/eventmesh/registry/nacos/service/NacosRegistryService.java
- eventmesh-runtime/conf/eventmesh.properties
> [ISSUE #4288] Enable the nacos plugin to support namespace

- eventmesh-connectors/eventmesh-connector-redis/build.gradle
- eventmesh-connectors/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/cloudevent/CloudEventCodec.java
- eventmesh-connectors/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/sink/connector/RedisSinkConnector.java
- eventmesh-connectors/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/source/connector/RedisSourceConnector.java
- eventmesh-connectors/eventmesh-connector-redis/src/main/resources/sink-config.yml
- eventmesh-connectors/eventmesh-connector-redis/src/main/resources/source-config.yml
- eventmesh-storage-plugin/eventmesh-storage-redis/src/main/java/org/apache/eventmesh/storage/redis/cloudevent/CloudEventCodec.java
Fixes #4032.
Add support for cloudevent data encoding and decoding with the way in redis-storage.
> [Feature #4032] Fix redis codec

- eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/RemoteSubscribeInstance.java
Fixes #4283.
Add event-bridge example
> [ISSUE #4283] Add event-bridge example

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/MessageUtils.java
> [ISSUE #4354] Fix spelling mistake

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/StreamPushRequest.java
> [ISSUE #4191] Do some code optimization.[StreamPushRequest]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java
Fixes #4190 
Complete some code optimizations for the EventMeshConsumer class
Fix three optimizations mentioned in issue #4190.
> [ISSUE #4190] Code optimization for the EventMeshConsumer class.

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/SubscribeStreamProcessor.java
Fixes #4196 .
For Fixing the issue #4196 
Fixing the issue #4196 
> [ISSUE #4196] [Enhancement] Dereference of 'subscriptionItems' may produce NPE.

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcpMessageDispatcher.java
Fixes #4203 .
Fixes the issue #4203 
Fixes the issue #4203 
> [ISSUE #4203] [Enhancement] Do some code optimization.[EventMeshTcpMessageDispatcher]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer.java
Fixes #4363
Completed several fixes missing in #4190 
Part of #4190 has been done in PR #4359.
> [ISSUE #4363] Do some code optimization.[EventMeshConsumer]

- eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/service/SubService.java
Fixes #4360 .
fix unSubscribeUrl cannot be null.
fix unSubscribeUrl cannot be null.
> [ISSUE 4360] Fix unSubscribeUrl cannot be null.

- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/source/config/SourceConnectorConfig.java
- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/resources/source-config.yml
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/data/RecordOffset.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/data/RecordPartition.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/storage/ConnectorRecordPartition.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-nacos/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/nacos/NacosConfigService.java
> [ISSUE #4366] When listens for remote nacos offset configuration, ConnectorRecordPartition deserialization fails.

- eventmesh-connectors/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/sink/connector/KafkaSinkConnector.java
- eventmesh-connectors/eventmesh-connector-kafka/src/main/java/org/apache/eventmesh/connector/kafka/source/connector/KafkaSourceConnector.java
- eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/sink/connector/OpenFunctionSinkConnector.java
- eventmesh-connectors/eventmesh-connector-openfunction/src/main/java/org/apache/eventmesh/connector/openfunction/source/connector/OpenFunctionSourceConnector.java
- eventmesh-connectors/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/sink/connector/PulsarSinkConnector.java
- eventmesh-connectors/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/source/connector/PulsarSourceConnector.java
- eventmesh-connectors/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/sink/connector/RedisSinkConnector.java
- eventmesh-connectors/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/source/connector/RedisSourceConnector.java
- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/sink/connector/RocketMQSinkConnector.java
- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/source/config/SourceConnectorConfig.java
- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/source/connector/RocketMQSourceConnector.java
- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/resources/source-config.yml
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/Application.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SinkWorker.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/connector/Connector.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/connector/ConnectorContext.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/connector/SinkConnectorContext.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/connector/SourceConnectorContext.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/data/RecordOffset.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/data/RecordPartition.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/storage/ConnectorRecordPartition.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-nacos/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/nacos/NacosConfigService.java
> [ISSUE #4379] Enable manually commit offset in rocketmq source connector

- eventmesh-connectors/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/source/connector/RocketMQSourceConnector.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
> [ISSUE #4388] Improve the rocketmq source connector offset ack

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/Body.java
Fixes #4406 
- Optimize Body#buildBody method
> [ISSUE #4406]Optimize Body#buildBody method

- eventmesh-connectors/eventmesh-connector-knative/gradle.properties
- eventmesh-connectors/eventmesh-connector-mongodb/gradle.properties
- eventmesh-connectors/eventmesh-connector-redis/gradle.properties
- tools/dependency-check/known-dependencies.txt
> [ISSUE #4435] Fix license check error

- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
Fixes #4450.
Add retry strategy for sourceWorker.
> [ISSUE #4450] Add retry strategy for sourceWorker.

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/AbstractRetryer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/retry/GrpcRetryer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/retry/HttpRetryer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/retry/EventMeshTcpRetryer.java
Fixes #4456.
NPE
Remove incorrect local variable
> [ISSUE #4456] startup failure caused by Retryer

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CClientDemo.java
Fixes #4089.
replace with lambda.
> [ISSUE #4089] Anonymous new can be replaced with lambda.[CClientDemo]

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/consumergroup/StreamTopicConfig.java
Fixes #4192.
1. I deleted the transient
2. I created a method to get information on the specification
3. I optimized the code
Optimize this class to make the code more concise as needed
I try to submit the code and hope it doesn't go wrong
> [ISSUE #4192] Do some code optimization.[StreamTopicConfig]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java
- eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/MeshMessageProtocolAdaptor.java
- eventmesh-protocol-plugin/eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/MeshMessageProtocolConstant.java
- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/util/EventMeshCloudEventBuilder.java
Fixes #4472 
- Fix MeshMessageProtocolAdaptor#fromCloudEvent throw NPE
> [ISSUE #4472]Fix MeshMessageProtocolAdaptor#fromCloudEvent throw NPE

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/impl/SubClientImpl.java
> [ISSUE #3516] Do some code optimization.[SubClientImpl]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/RegistryRequest.java
Fixes #4026.
Changed == to equals()
> [ISSUE #4026] Comparison using reference equality instead of value equality.[RegistryRequest]

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/boot/EventMeshServerTest.java
>  [ISSUE #3520]Swap these 2 arguments so they are in the correct order: expected value, actual value.[EventMeshServerTest]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/Constants.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/JsonUtils.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/common/SpringApplicationContextHolder.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/config/EventMeshAutoConfiguration.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/server/SpringConnectServer.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/EventMeshConsumerMetadata.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/EventMeshListener.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/EventMeshListenerBeanPostProcessor.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/EventMeshMessageListener.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/EventMeshMessageListenerBeanPostProcessor.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/config/SpringSinkConfig.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/connector/SinkConnectorConfig.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/connector/SpringSinkConnector.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/sink/connector/SpringSinkConnectorCreateServiceImpl.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/resources/META-INF/eventmesh/org.apache.eventmesh.openconnect.api.ConnectorCreateService
- eventmesh-connectors/eventmesh-connector-spring/src/main/resources/sink-config.yml
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/Application.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/ConnectorCreateService.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/CCSubClient.java
Fixes #4414 .
Add spring sink connector.
Add `@EventMeshListener` annotation, support annotation add on method, deserialization through method imported parameters.
> [ISSUE #4414] Add spring sink connector.

- eventmesh-sdks/eventmesh-sdk-rust/Cargo.toml
- eventmesh-sdks/eventmesh-sdk-rust/rust-toolchain.toml
Fixes #4503 
- Rust sdk use nightly toolchain
- add rust-toolchain.toml file
> [ISSUE #4503]Rust sdk use nightly toolchain

- eventmesh-connectors/eventmesh-connector-spring/build.gradle
- eventmesh-connectors/eventmesh-connector-spring/src/test/java/org/apache/eventmesh/connector/spring/source/connector/SpringSourceConnectorTest.java
Fixes #4508 .
- Add unit test for SpringSourceConnector.
- Resolve dependency confilct.
> [ISSUE#4508] Add unit test for SpringSourceConnector.

- eventmesh-webhook/eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java
Fixes #4517.
Replace `@ # $ % ^ & * , / \` to `.` instead of encoding them.
> [ISSUE #4517] Fix Webhook callback path is not a valid Nacos dataId

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java
- eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/model/TopicMetadata.java
> [ISSUE #3906] Do some code optimization.[EventMeshUtil]

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/NetUtils.java
- eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/model/TopicMetadata.java
> [ISSUE #3902] Do some code optimization.[NetUtils]

- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/source/MessageSendingOperations.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/source/connector/SpringSourceConnector.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/callback/SendExcepionContext.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/callback/SendMessageCallback.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/api/callback/SendResult.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/data/ConnectRecord.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/data/DefaultKeyValue.java
- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/data/KeyValue.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractTCPServer.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/CreateTopicProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/DeleteTopicProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalUnSubscribeEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/QuerySubscriptionProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SendSyncMessageProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java
- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/consumer/SubStreamHandler.java
- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/consumer/EventMeshHttpConsumer.java
Fixes #4529 .
Add sendcallback for springConnector SDK.
> [ISSUE #4529] Add sendcallback for springConnector.

- eventmesh-connectors/eventmesh-connector-redis/src/test/java/org/apache/eventmesh/connector/redis/source/connector/RedisSourceConnectorTest.java
- eventmesh-connectors/eventmesh-connector-redis/src/test/resources/source-config.yml
Fixes #4530 .
Add unit test for RedisSourceConnector.
> [ISSUE#4530] Add unit test for RedisSourceConnector.

- eventmesh-examples/build.gradle
- eventmesh-examples/src/main/java/org/apache/eventmesh/spring/SpringBootDemoApplication.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/spring/pub/SpringPubController.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/spring/sub/SpringSubHandler.java
- eventmesh-examples/src/main/resources/server-config.yml
- eventmesh-examples/src/main/resources/sink-config.yml
- eventmesh-examples/src/main/resources/source-config.yml
Fixes #4552 .
Add example for spring connector sdk.
> [ISSUE#4552] Add example for spring connector sdk.

- eventmesh-connectors/README.md
Fix #4559 
Update eventmesh-connector readme file.
> [ISSUE#4559] Update eventmesh-connector readme file.

- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusGrpcExporter.java
- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusHttpExporter.java
- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusTcpExporter.java
- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/utils/PrometheusExporterUtils.java
> [ISSUE #4201] optimize the code of metrics

- eventmesh-connectors/eventmesh-connector-openfunction/build.gradle
- eventmesh-connectors/eventmesh-connector-openfunction/src/test/java/org/apache/eventmesh/connector/openfunction/source/connector/OpenFunctionSourceConnectorTest.java
Fixes #4547 .
OpenFunctionConnector module was lacking test cases.
Added test file for OpenFunction Source Connector. Explored SpringSourceConnector and based on that the changes were added.
> [ISSUE #4547] Add unit test for OpenFunctionSourceConnector.

- build.gradle
- eventmesh-runtime/build.gradle
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/WebhookUtil.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/WebhookUtilTest.java
Fixes #4564.
*validating the input url to avoid SSRF attacks*
*org.apache.eventmesh.runtime.util.WebhookUtil#obtainDeliveryAgreement
in this method i added targetUrl validation, to do so i added commons-validator:commons-validator lib 
and use org.apache.commons.validator.routines.UrlValidator#isValid method, 
and add new test case org.apache.eventmesh.runtime.util.WebhookUtilTest#testObtainDeliveryAgreementWithInvalidTargetUrl 
and update the test case 
org.apache.eventmesh.runtime.util.WebhookUtilTest#testObtainDeliveryAgreement*
- Does this pull request introduce a new feature? (yes / no)      no
- If a feature is not documented …
> [ISSUE #4564] add url validation to avoid SSRF

- eventmesh-examples/src/main/java/org/apache/eventmesh/grpc/sub/app/SpringBootDemoApplication.java
- eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/SpringBootDemoApplication.java
Fixes #4581.
#4581
avoid http demo and grpc demo rely on tcp runtime 
> [ISSUE #4581]  http demo rely on tcp runtime

- eventmesh-connectors/eventmesh-connector-dingtalk/src/main/java/org/apache/eventmesh/connector/dingtalk/common/constants/ConnectRecordExtensionKeys.java
- eventmesh-connectors/eventmesh-connector-dingtalk/src/main/java/org/apache/eventmesh/connector/dingtalk/sink/connector/DingDingSinkConnector.java
- eventmesh-connectors/eventmesh-connector-dingtalk/src/test/java/org/apache/eventmesh/connector/dingtalk/sink/connector/DingDingSinkConnectorTest.java
- eventmesh-connectors/eventmesh-connector-spring/src/main/java/org/apache/eventmesh/connector/spring/source/connector/SpringSourceConnector.java
- eventmesh-connectors/eventmesh-connector-spring/src/test/java/org/apache/eventmesh/connector/spring/source/connector/SpringSourceConnectorTest.java
- eventmesh-examples/src/main/resources/application.properties
- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusGrpcExporter.java
- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusHttpExporter.java
- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/metrics/PrometheusTcpExporter.java
- eventmesh-metrics-plugin/eventmesh-metrics-prometheus/src/main/java/org/apache/eventmesh/metrics/prometheus/utils/PrometheusExporterUtils.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/SourceWorker.java
- eventmesh-openconnect/eventmesh-openconnect-java/src/main/java/org/apache/eventmesh/openconnect/util/CloudEventUtil.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractTCPServer.java
Fixes #4580 .
Modifications:
- Integrates spring environment properties with `CloudEvent` and `ConnectRecord` extensions.
> [ISSUE#4580] Connector extension supports spring environment variables.

- .github/workflows/greetings.yml
> [ISSUE #4585] The first-interaction ci check error

- build.gradle
- eventmesh-connectors/eventmesh-connector-wechat/build.gradle
- eventmesh-connectors/eventmesh-connector-wechat/src/main/java/org/apache/eventmesh/connector/wechat/config/WeChatConnectServerConfig.java
- eventmesh-connectors/eventmesh-connector-wechat/src/main/java/org/apache/eventmesh/connector/wechat/server/WeChatConnectServer.java
- eventmesh-connectors/eventmesh-connector-wechat/src/main/java/org/apache/eventmesh/connector/wechat/sink/config/SinkConnectorConfig.java
- eventmesh-connectors/eventmesh-connector-wechat/src/main/java/org/apache/eventmesh/connector/wechat/sink/config/WeChatSinkConfig.java
- eventmesh-connectors/eventmesh-connector-wechat/src/main/java/org/apache/eventmesh/connector/wechat/sink/connector/TemplateMessageResponse.java
- eventmesh-connectors/eventmesh-connector-wechat/src/main/java/org/apache/eventmesh/connector/wechat/sink/connector/WeChatSinkConnector.java
- eventmesh-connectors/eventmesh-connector-wechat/src/main/resources/server-config.yml
- eventmesh-connectors/eventmesh-connector-wechat/src/main/resources/sink-config.yml
- eventmesh-connectors/eventmesh-connector-wechat/src/test/java/org/apache/eventmesh/connector/wechat/sink/connector/WeChatSinkConnectorTest.java
- eventmesh-connectors/eventmesh-connector-wechat/src/test/resources/server-config.yml
- eventmesh-connectors/eventmesh-connector-wechat/src/test/resources/sink-config.yml
- settings.gradle
Fixes #4410.
*add new feature wechat sink connector*
*add new module eventmesh-connector-wechat in eventmesh-connector*
- Does this pull request introduce a new feature? (yes / no) yes
> [ISSUE #4410]add wechat sink connector

- eventmesh-connectors/eventmesh-connector-dingtalk/src/main/java/org/apache/eventmesh/connector/dingtalk/common/constants/ConnectRecordExtensionKeys.java
- eventmesh-connectors/eventmesh-connector-dingtalk/src/main/java/org/apache/eventmesh/connector/dingtalk/config/DingDingMessageTemplateType.java
- eventmesh-connectors/eventmesh-connector-dingtalk/src/main/java/org/apache/eventmesh/connector/dingtalk/sink/connector/DingDingSinkConnector.java
- eventmesh-connectors/eventmesh-connector-dingtalk/src/test/java/org/apache/eventmesh/connector/dingtalk/sink/connector/DingDingSinkConnectorTest.java
- eventmesh-connectors/eventmesh-connector-wecom/src/main/java/org/apache/eventmesh/connector/wecom/config/WeComMessageTemplateType.java
- eventmesh-connectors/eventmesh-connector-wecom/src/main/java/org/apache/eventmesh/connector/wecom/constants/ConnectRecordExtensionKeys.java
- eventmesh-connectors/eventmesh-connector-wecom/src/main/java/org/apache/eventmesh/connector/wecom/sink/connector/WeComSinkConnector.java
- eventmesh-connectors/eventmesh-connector-wecom/src/test/java/org/apache/eventmesh/connector/wecom/connector/WeComSinkConnectorTest.java
- eventmesh-examples/src/main/resources/application.properties
> [ISSUE#4590] WeCom/DingTalk connector extension supports spring environment variables

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/ProtocolKey.java
- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/demo/BroadCastSubClient.java
Fixes #4623 
- Fix CloudEvents variable names do not support underscores
> [ISSUE #4623]Fix cloudEvents variable names do not support underscores

- eventmesh-sdks/eventmesh-sdk-rust/src/common/protocol_key.rs
- eventmesh-sdks/eventmesh-sdk-rust/src/grpc/grpc_consumer.rs
- eventmesh-sdks/eventmesh-sdk-rust/src/model/message.rs
- eventmesh-sdks/eventmesh-sdk-rust/src/model/subscription.rs
- eventmesh-sdks/eventmesh-sdk-rust/src/net.rs
Fixes #4625 
- fix grpc request reply can not work
> [ISSUE #4625]fix grpc request reply can not work

- build.gradle
Fixes #4647.
fix binary package runtime failure.
complete the missing import and fix the binary package running exception.
> [ISSUE #4647] Fix binary package runtime failure.

- eventmesh-connectors/eventmesh-connector-lark/README.md
- eventmesh-connectors/eventmesh-connector-rabbitmq/README.md
- eventmesh-connectors/eventmesh-connector-rabbitmq/README_CN.md
> [ISSUE #4607] Documentation Needed for eventmesh-connector-rabbitmq

- eventmesh-connectors/eventmesh-connector-http/README.md
- eventmesh-connectors/eventmesh-connector-http/README_CN.md
Fixes #4656 .
- Add docs for the http connector
> [ISSUE #4656] Documentation Needed for eventmesh-connector-http

- eventmesh-connectors/eventmesh-connector-slack/README.md
- eventmesh-connectors/eventmesh-connector-slack/README_CN.md
Fixes #4612 .
Add documentation for slack sink connector.
> [ISSUE #4661] Add documentation for slack sink connector.

- eventmesh-connectors/eventmesh-connector-wecom/README.md
- eventmesh-connectors/eventmesh-connector-wecom/README_CN.md
Fixes #4663 .
Add documentation for wecom sink connector.
> [ISSUE #4663] Add documentation for wecom sink connector.

- tools/third-party-licenses/LICENSE
- tools/third-party-licenses/NOTICE
close #4671 
- Update LICENSE and NOTICE
> [ISSUE #4671]Update LICENSE and NOTICE

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/codec/Codec.java
- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java
> [ISSUE #4677] tcp codec enhancement

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/TCPClient.java
- eventmesh-sdks/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/TcpClient.java
> [ISSUE #4695] Fix tcp client not thread safe

- eventmesh-connectors/eventmesh-connector-openfunction/src/test/java/org/apache/eventmesh/connector/openfunction/sink/connector/OpenFunctionSinkConnectorTest.java
Fixes #4548
OpenFunctionSinkConnector did not have any test cases.
A new class called OpenFunctionSinkConnectorTest was added with two test cases.
> Added tests for OpenFunctionSinkConnector

- eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/IPUtils.java
> [ISSUE #4654]Get Ip address problem when run example code

- eventmesh-operator/Dockerfile
- eventmesh-operator/Makefile
- eventmesh-operator/config/rbac/role.yaml
- eventmesh-operator/config/rbac/role_binding.yaml
- eventmesh-operator/config/rbac/service_account.yaml
- eventmesh-operator/config/samples/eventmesh_operator.yaml
- eventmesh-operator/controllers/eventmesh_runtime/runtime_controller.go
Fixes #4728 .
Implementation of deploying eventmesh-operator to a k8s cluster to deploy eventmesh components with one click.
Implementation of deploying eventmesh-operator to a k8s cluster to deploy eventmesh components with one click.
> [ISSUE #4728] Deploy eventmesh-operator on k8s cluster.

- NOTICE
- tools/third-party-licenses/NOTICE
Fixes #4761 
Please read https://github.com/apache/eventmesh/issues/4761 for docs information.
Update copyright year to 2024
> [ISSUE #4761] Update copyright year to 2024 (#4761)

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/EventHandler.java
Fixes  https://github.com/apache/eventmesh/issues/3014
see: https://github.com/apache/eventmesh/issues/3014
make code more consistance
> [ISSUE #3014]Replace encoding using the static variable DEFAULT_CHARSET

- eventmesh-openconnect/eventmesh-openconnect-offsetmgmt-plugin/eventmesh-openconnect-offsetmgmt-api/src/main/java/org/apache/eventmesh/openconnect/offsetmgmt/api/storage/OffsetStorageWriterImpl.java
Fixes https://github.com/apache/eventmesh/issues/4795
Motivation
replace this exception with log print and return false.
Modifications
Documentation
Does this pull request introduce a new feature? no
> [ISSUE #4795] Replace this exception in beginFlush() with log print and return false

- .github/workflows/stale.yml
Fixes #4849
Please see https://github.com/apache/eventmesh/issues/4849.
Enlarge `operations-per-run` to `300`.
> [ISSUE #4849] Enlarge stale bot `operations-per-run` to process more issues

- eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/DeleteTopicProcessor.java
> [ISSUE ##4865] Improve readability of failed topic list log

- eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/config/HttpRetryConfig.java
- eventmesh-connectors/eventmesh-connector-http/src/main/resources/sink-config.yml
- eventmesh-connectors/eventmesh-connector-http/src/test/resources/sink-config.yml
Fixes #4873
Optimize some configuration information of HTTP Sink Connector
1. Remove the ssl field from the config file, this field is not valid
2. Change the default value of maxRetries to 2
> [ISSUE #4873] Optimize some configuration information of HTTP Sink Connector

- .github/dependabot.yml
- .github/workflows/auto-dependabot.yml
Fixes #4929
This PR is a copy of https://github.com/apache/eventmesh-dashboard/pull/145.
Please see #4929.
Approve if the PR author is dependabot.
'Approve if the PR author is dependabot' or 'Approve if the PR branch starts with `dependabot/`' are both workable ways to auto-approve the PR. However, the latter will also approve if the PR is submitted from a forked repo, which is a little insecure.
c.f.: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
logs: https://github.com/Pil0tXia/eventmesh-dashboard/actions/runs/9249439014, https://github.com/Pil0tXia/eventmesh-dashboard/actions/runs/9249493904
- If a feature …
> [ISSUE #4929] Auto approve when dependabot's branch is changed by committers

- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/EventMeshCloudEventWriterTest.java
> [ISSUE #4993] Unit test for EventMeshCloudEventWriter.java

- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/header/client/HeartbeatRequestHeader.java
- eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/header/client/UnRegRequestHeader.java
- eventmesh-connectors/eventmesh-connector-jdbc/src/main/resources/source-config.yml
- eventmesh-operator/README.md
- eventmesh-runtime/scripts/client_manage.sh
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/MessageUtils.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/TCPClient.java
- eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/util/RemotingHelperTest.java
- eventmesh-sdks/eventmesh-sdk-c/configs/rmb.conf
- eventmesh-sdks/eventmesh-sdk-java/src/test/java/org/apache/eventmesh/client/tcp/common/EventMeshTestUtils.java
> [ISSUE #5162] Remove and replace sensitive information involved in code

- .asf.yaml
change the protected branch to develop temporarily for remove the sensitive info at master branch
> Update .asf.yaml 

- eventmesh-connectors/eventmesh-connector-http/src/main/java/org/apache/eventmesh/connector/http/sink/handler/AbstractHttpSinkHandler.java
Fixes #5177
Refer to [#5177](https://github.com/apache/eventmesh/issues/5177) for specific details.
> [ISSUE#5177] Incorrect attribute assignment in BROADCAST strategy of AbstractHttpSinkHandler

- eventmesh-connectors/eventmesh-connector-file/src/test/java/org/apache/eventmesh/connector/file/sink/connector/FileSinkConnectorTest.java
- eventmesh-connectors/eventmesh-connector-file/src/test/java/org/apache/eventmesh/connector/file/source/connector/FileSourceConnectorTest.java
Fixes https://github.com/apache/eventmesh/issues/4642
Motivation
Modifications
Added new tests for FileSinkConnector.java located at [eventmesh-connectors/eventmesh-connector-file/src/main/java/org/apache/eventmesh/connector/file]
Documentation
If yes, how is the feature documented? (not applicable)
> [ISSUE #4642] unit test for FileSinkConnectorTest.java
